<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2 Estatística Descritiva | Fundamentos de Estatística para Ciência de Dados</title>
  <meta name="description" content="Este é o livro da disciplina Fundamentos de Estatística para Ciência de Dados da PUCRS-UOL escrito no RStudio. Sinta-se à vontade para compartilhar e colaborar https://github.com/filipezabala/fdepcdd" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="2 Estatística Descritiva | Fundamentos de Estatística para Ciência de Dados" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Este é o livro da disciplina Fundamentos de Estatística para Ciência de Dados da PUCRS-UOL escrito no RStudio. Sinta-se à vontade para compartilhar e colaborar https://github.com/filipezabala/fdepcdd" />
  <meta name="github-repo" content="filipezabala/fdepcdd" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2 Estatística Descritiva | Fundamentos de Estatística para Ciência de Dados" />
  
  <meta name="twitter:description" content="Este é o livro da disciplina Fundamentos de Estatística para Ciência de Dados da PUCRS-UOL escrito no RStudio. Sinta-se à vontade para compartilhar e colaborar https://github.com/filipezabala/fdepcdd" />
  

<meta name="author" content="Filipe J. Zabala" />


<meta name="date" content="2020-11-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="introducao.html"/>
<link rel="next" href="probabilidade.html"/>
<script src="libs/header-attrs-2.5/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.2/htmlwidgets.js"></script>
<link href="libs/rglwidgetClass-2/rgl.css" rel="stylesheet" />
<script src="libs/rglwidgetClass-2/rglClass.src.js"></script>
<script src="libs/CanvasMatrix4-2016/CanvasMatrix.src.js"></script>
<script src="libs/rglWebGL-binding-0.100.54/rglWebGL.js"></script>
<link href="libs/crosstalk-1.1.0.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.0.1/js/crosstalk.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefácio</a></li>
<li class="chapter" data-level="1" data-path="introducao.html"><a href="introducao.html"><i class="fa fa-check"></i><b>1</b> Introdução</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introducao.html"><a href="introducao.html#ferramentas"><i class="fa fa-check"></i><b>1.1</b> Ferramentas</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="introducao.html"><a href="introducao.html#r"><i class="fa fa-check"></i><b>1.1.1</b> R</a></li>
<li class="chapter" data-level="1.1.2" data-path="introducao.html"><a href="introducao.html#rstudio"><i class="fa fa-check"></i><b>1.1.2</b> RStudio</a></li>
<li class="chapter" data-level="1.1.3" data-path="introducao.html"><a href="introducao.html#python"><i class="fa fa-check"></i><b>1.1.3</b> Python</a></li>
<li class="chapter" data-level="1.1.4" data-path="introducao.html"><a href="introducao.html#jasp"><i class="fa fa-check"></i><b>1.1.4</b> JASP</a></li>
<li class="chapter" data-level="1.1.5" data-path="introducao.html"><a href="introducao.html#stan"><i class="fa fa-check"></i><b>1.1.5</b> Stan</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="introducao.html"><a href="introducao.html#materiais-de-apoio"><i class="fa fa-check"></i><b>1.2</b> Materiais de apoio</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="introducao.html"><a href="introducao.html#página-do-professor-filipe-zabala"><i class="fa fa-check"></i><b>1.2.1</b> Página do professor Filipe Zabala</a></li>
<li class="chapter" data-level="1.2.2" data-path="introducao.html"><a href="introducao.html#khan-academy"><i class="fa fa-check"></i><b>1.2.2</b> Khan Academy</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introducao.html"><a href="introducao.html#algarismos-e-numeros"><i class="fa fa-check"></i><b>1.3</b> Algarismos e Números</a></li>
<li class="chapter" data-level="1.4" data-path="introducao.html"><a href="introducao.html#porcentagens-decimais-e-milhares"><i class="fa fa-check"></i><b>1.4</b> Porcentagens, Decimais e Milhares</a></li>
<li class="chapter" data-level="1.5" data-path="introducao.html"><a href="introducao.html#o-senhor-x"><i class="fa fa-check"></i><b>1.5</b> O Senhor <span class="math inline">\(X\)</span></a></li>
<li class="chapter" data-level="1.6" data-path="introducao.html"><a href="introducao.html#somatorio"><i class="fa fa-check"></i><b>1.6</b> Somatório</a></li>
<li class="chapter" data-level="1.7" data-path="introducao.html"><a href="introducao.html#arredondamento-e-truncagem"><i class="fa fa-check"></i><b>1.7</b> Arredondamento e Truncagem</a></li>
<li class="chapter" data-level="1.8" data-path="introducao.html"><a href="introducao.html#outros"><i class="fa fa-check"></i><b>1.8</b> Outros símbolos e expressões</a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="introducao.html"><a href="introducao.html#alfabeto-grego"><i class="fa fa-check"></i><b>1.8.1</b> Alfabeto grego</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html"><i class="fa fa-check"></i><b>2</b> Estatística Descritiva</a>
<ul>
<li class="chapter" data-level="2.1" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#variáveis"><i class="fa fa-check"></i><b>2.1</b> Variáveis</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#variavel-qualitativa-nominal"><i class="fa fa-check"></i><b>2.1.1</b> Variável qualitativa nominal</a></li>
<li class="chapter" data-level="2.1.2" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#variavel-qualitativa-ordinal"><i class="fa fa-check"></i><b>2.1.2</b> Variável qualitativa ordinal</a></li>
<li class="chapter" data-level="2.1.3" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#variavel-quantitativa-discreta"><i class="fa fa-check"></i><b>2.1.3</b> Variável quantitativa discreta</a></li>
<li class="chapter" data-level="2.1.4" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#variavel-quantitativa-continua"><i class="fa fa-check"></i><b>2.1.4</b> Variável quantitativa contínua</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#distribuicao-de-frequencia"><i class="fa fa-check"></i><b>2.2</b> Distribuição de Frequência</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#db-rol-eo"><i class="fa fa-check"></i><b>2.2.1</b> Dados brutos, Rol e Estatísticas de Ordem</a></li>
<li class="chapter" data-level="2.2.2" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#tab-freq-univ-discr"><i class="fa fa-check"></i><b>2.2.2</b> Tabela de frequência univariada discreta</a></li>
<li class="chapter" data-level="2.2.3" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#tab-freq-univ-cont"><i class="fa fa-check"></i><b>2.2.3</b> Tabela de frequência univariada contínua</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#posicao"><i class="fa fa-check"></i><b>2.3</b> Medidas de Posição (ou Localização)</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#minmax"><i class="fa fa-check"></i><b>2.3.1</b> Mínimo e Máximo</a></li>
<li class="chapter" data-level="2.3.2" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#mas"><i class="fa fa-check"></i><b>2.3.2</b> Média (Aritmética Simples)</a></li>
<li class="chapter" data-level="2.3.3" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#total"><i class="fa fa-check"></i><b>2.3.3</b> Total</a></li>
<li class="chapter" data-level="2.3.4" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#mquadr"><i class="fa fa-check"></i><b>2.3.4</b> Média Quadrática</a></li>
<li class="chapter" data-level="2.3.5" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#moda"><i class="fa fa-check"></i><b>2.3.5</b> Moda</a></li>
<li class="chapter" data-level="2.3.6" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#separatrizes"><i class="fa fa-check"></i><b>2.3.6</b> Separatrizes</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#medidas-de-dispersão-ou-variabilidade"><i class="fa fa-check"></i><b>2.4</b> Medidas de Dispersão (ou Variabilidade)</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#amplitude"><i class="fa fa-check"></i><b>2.4.1</b> Amplitude</a></li>
<li class="chapter" data-level="2.4.2" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#variância"><i class="fa fa-check"></i><b>2.4.2</b> Variância</a></li>
<li class="chapter" data-level="2.4.3" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#desvio-padrão"><i class="fa fa-check"></i><b>2.4.3</b> Desvio Padrão</a></li>
<li class="chapter" data-level="2.4.4" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#coeficiente-de-variação"><i class="fa fa-check"></i><b>2.4.4</b> Coeficiente de variação</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#outras-medidas"><i class="fa fa-check"></i><b>2.5</b> Outras medidas</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#assimetria-ou-obliquidade"><i class="fa fa-check"></i><b>2.5.1</b> Assimetria (ou Obliquidade)</a></li>
<li class="chapter" data-level="2.5.2" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#curtose"><i class="fa fa-check"></i><b>2.5.2</b> Curtose</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#visualização"><i class="fa fa-check"></i><b>2.6</b> Visualização</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#menu-de-opções"><i class="fa fa-check"></i><b>2.6.1</b> Menu de opções</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="probabilidade.html"><a href="probabilidade.html"><i class="fa fa-check"></i><b>3</b> Probabilidade</a>
<ul>
<li class="chapter" data-level="3.1" data-path="probabilidade.html"><a href="probabilidade.html#propriedades"><i class="fa fa-check"></i><b>3.1</b> Propriedades</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="probabilidade.html"><a href="probabilidade.html#propriedades-fundamentais-axiomas-de-kolmogorov"><i class="fa fa-check"></i><b>3.1.1</b> Propriedades fundamentais (Axiomas de Kolmogorov)</a></li>
<li class="chapter" data-level="3.1.2" data-path="probabilidade.html"><a href="probabilidade.html#propriedades-secundárias"><i class="fa fa-check"></i><b>3.1.2</b> Propriedades secundárias</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="probabilidade.html"><a href="probabilidade.html#r-como-um-conjunto-de-tabelas-estatísticas"><i class="fa fa-check"></i><b>3.2</b> R como um conjunto de tabelas estatísticas</a></li>
<li class="chapter" data-level="3.3" data-path="probabilidade.html"><a href="probabilidade.html#distribuição-normal"><i class="fa fa-check"></i><b>3.3</b> Distribuição Normal</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="probabilidade.html"><a href="probabilidade.html#normal-univariada"><i class="fa fa-check"></i><b>3.3.1</b> Normal univariada</a></li>
<li class="chapter" data-level="3.3.2" data-path="probabilidade.html"><a href="probabilidade.html#normal-bivariada"><i class="fa fa-check"></i><b>3.3.2</b> Normal bivariada</a></li>
<li class="chapter" data-level="3.3.3" data-path="probabilidade.html"><a href="probabilidade.html#normal-multivariada"><i class="fa fa-check"></i><b>3.3.3</b> Normal multivariada</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="amostragem.html"><a href="amostragem.html"><i class="fa fa-check"></i><b>4</b> Amostragem</a>
<ul>
<li class="chapter" data-level="4.1" data-path="amostragem.html"><a href="amostragem.html#definições-básicas"><i class="fa fa-check"></i><b>4.1</b> Definições básicas</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="amostragem.html"><a href="amostragem.html#unidade-elementar"><i class="fa fa-check"></i><b>4.1.1</b> Unidade Elementar</a></li>
<li class="chapter" data-level="4.1.2" data-path="amostragem.html"><a href="amostragem.html#unidade-amostral"><i class="fa fa-check"></i><b>4.1.2</b> Unidade Amostral</a></li>
<li class="chapter" data-level="4.1.3" data-path="amostragem.html"><a href="amostragem.html#sistema-de-referências"><i class="fa fa-check"></i><b>4.1.3</b> Sistema de referências</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="amostragem.html"><a href="amostragem.html#universo-mathcalu"><i class="fa fa-check"></i><b>4.2</b> Universo <span class="math inline">\(\mathcal{U}\)</span></a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="amostragem.html"><a href="amostragem.html#parâmetros"><i class="fa fa-check"></i><b>4.2.1</b> Parâmetros</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="amostragem.html"><a href="amostragem.html#amostras"><i class="fa fa-check"></i><b>4.3</b> Amostras</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="amostragem.html"><a href="amostragem.html#plano-amostral"><i class="fa fa-check"></i><b>4.3.1</b> Plano Amostral</a></li>
<li class="chapter" data-level="4.3.2" data-path="amostragem.html"><a href="amostragem.html#distribuições-amostrais"><i class="fa fa-check"></i><b>4.3.2</b> Distribuições amostrais</a></li>
<li class="chapter" data-level="4.3.3" data-path="amostragem.html"><a href="amostragem.html#amostra-representativa"><i class="fa fa-check"></i><b>4.3.3</b> Amostra representativa</a></li>
<li class="chapter" data-level="4.3.4" data-path="amostragem.html"><a href="amostragem.html#tipos-de-amostras"><i class="fa fa-check"></i><b>4.3.4</b> Tipos de amostras</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="amostragem.html"><a href="amostragem.html#principais-técnicas-de-amostragem"><i class="fa fa-check"></i><b>4.4</b> Principais técnicas de amostragem</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="amostragem.html"><a href="amostragem.html#amostragem-aleatória-simples"><i class="fa fa-check"></i><b>4.4.1</b> Amostragem Aleatória Simples</a></li>
<li class="chapter" data-level="4.4.2" data-path="amostragem.html"><a href="amostragem.html#amostragem-sistemática"><i class="fa fa-check"></i><b>4.4.2</b> Amostragem Sistemática</a></li>
<li class="chapter" data-level="4.4.3" data-path="amostragem.html"><a href="amostragem.html#amostragem-estratificada"><i class="fa fa-check"></i><b>4.4.3</b> Amostragem Estratificada</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="amostragem.html"><a href="amostragem.html#cálculo-do-tamanho-da-amostra"><i class="fa fa-check"></i><b>4.5</b> Cálculo do tamanho da amostra</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="amostragem.html"><a href="amostragem.html#média"><i class="fa fa-check"></i><b>4.5.1</b> Média</a></li>
<li class="chapter" data-level="4.5.2" data-path="amostragem.html"><a href="amostragem.html#proporção"><i class="fa fa-check"></i><b>4.5.2</b> Proporção</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="amostragem.html"><a href="amostragem.html#para-saber-mais"><i class="fa fa-check"></i><b>4.6</b> Para saber mais</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="inferencia-classica.html"><a href="inferencia-classica.html"><i class="fa fa-check"></i><b>5</b> Inferência Clássica</a>
<ul>
<li class="chapter" data-level="5.1" data-path="inferencia-classica.html"><a href="inferencia-classica.html#estimação-pontual"><i class="fa fa-check"></i><b>5.1</b> Estimação Pontual</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="inferencia-classica.html"><a href="inferencia-classica.html#estimadores-e-suas-propriedades"><i class="fa fa-check"></i><b>5.1.1</b> Estimadores e suas propriedades</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="inferencia-classica.html"><a href="inferencia-classica.html#estimação-por-intervalo-de-confiança"><i class="fa fa-check"></i><b>5.2</b> (Estimação por) Intervalo de Confiança</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="inferencia-classica.html"><a href="inferencia-classica.html#média-1"><i class="fa fa-check"></i><b>5.2.1</b> Média</a></li>
<li class="chapter" data-level="5.2.2" data-path="inferencia-classica.html"><a href="inferencia-classica.html#proporção-1"><i class="fa fa-check"></i><b>5.2.2</b> Proporção</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="inferencia-classica.html"><a href="inferencia-classica.html#estimação-por-teste-de-hipóteses"><i class="fa fa-check"></i><b>5.3</b> (Estimação por) Teste de Hipóteses</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="inferencia-classica.html"><a href="inferencia-classica.html#testes-paramétricos-univariados"><i class="fa fa-check"></i><b>5.3.1</b> Testes Paramétricos Univariados</a></li>
<li class="chapter" data-level="5.3.2" data-path="inferencia-classica.html"><a href="inferencia-classica.html#testes-paramétricos-bivariados"><i class="fa fa-check"></i><b>5.3.2</b> Testes Paramétricos Bivariados</a></li>
<li class="chapter" data-level="5.3.3" data-path="inferencia-classica.html"><a href="inferencia-classica.html#testes-paramétricos-multivariados"><i class="fa fa-check"></i><b>5.3.3</b> Testes Paramétricos Multivariados</a></li>
<li class="chapter" data-level="5.3.4" data-path="inferencia-classica.html"><a href="inferencia-classica.html#testes-não-paramétricos-univariados"><i class="fa fa-check"></i><b>5.3.4</b> Testes Não Paramétricos Univariados</a></li>
<li class="chapter" data-level="5.3.5" data-path="inferencia-classica.html"><a href="inferencia-classica.html#testes-não-paramétricos-bivariados"><i class="fa fa-check"></i><b>5.3.5</b> Testes Não Paramétricos Bivariados</a></li>
<li class="chapter" data-level="5.3.6" data-path="inferencia-classica.html"><a href="inferencia-classica.html#testes-não-paramétricos-multivariados"><i class="fa fa-check"></i><b>5.3.6</b> Testes Não Paramétricos Multivariados</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="inferencia-classica.html"><a href="inferencia-classica.html#exercícios"><i class="fa fa-check"></i><b>5.4</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="inferencia-bayesiana.html"><a href="inferencia-bayesiana.html"><i class="fa fa-check"></i><b>6</b> Inferência Bayesiana</a>
<ul>
<li class="chapter" data-level="6.1" data-path="inferencia-bayesiana.html"><a href="inferencia-bayesiana.html#princípios-de-verossimilhança-suficiência-e-condicionalidade"><i class="fa fa-check"></i><b>6.1</b> Princípios de verossimilhança, suficiência e condicionalidade</a></li>
<li class="chapter" data-level="6.2" data-path="inferencia-bayesiana.html"><a href="inferencia-bayesiana.html#distribuição-a-priori"><i class="fa fa-check"></i><b>6.2</b> Distribuição a priori</a></li>
<li class="chapter" data-level="6.3" data-path="inferencia-bayesiana.html"><a href="inferencia-bayesiana.html#estimação-pontual-1"><i class="fa fa-check"></i><b>6.3</b> Estimação Pontual</a></li>
<li class="chapter" data-level="6.4" data-path="inferencia-bayesiana.html"><a href="inferencia-bayesiana.html#estimação-por-intervaloregiões-de-credibilidade"><i class="fa fa-check"></i><b>6.4</b> (Estimação por) Intervalo/Regiões de Credibilidade</a></li>
<li class="chapter" data-level="6.5" data-path="inferencia-bayesiana.html"><a href="inferencia-bayesiana.html#estimação-por-teste-de-hipóteses-1"><i class="fa fa-check"></i><b>6.5</b> (Estimação por) Teste de Hipóteses</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="inferencia-bayesiana.html"><a href="inferencia-bayesiana.html#fatores-de-bayes"><i class="fa fa-check"></i><b>6.5.1</b> Fatores de Bayes</a></li>
<li class="chapter" data-level="6.5.2" data-path="inferencia-bayesiana.html"><a href="inferencia-bayesiana.html#fbst---full-bayesian-significance-test"><i class="fa fa-check"></i><b>6.5.2</b> FBST - <em>Full Bayesian Significance Test</em></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="modelos-lineares.html"><a href="modelos-lineares.html"><i class="fa fa-check"></i><b>7</b> Modelos Lineares</a>
<ul>
<li class="chapter" data-level="7.1" data-path="modelos-lineares.html"><a href="modelos-lineares.html#correlacao"><i class="fa fa-check"></i><b>7.1</b> Correlação</a></li>
<li class="chapter" data-level="7.2" data-path="modelos-lineares.html"><a href="modelos-lineares.html#regressão-linear-simples"><i class="fa fa-check"></i><b>7.2</b> Regressão Linear Simples</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="modelos-lineares.html"><a href="modelos-lineares.html#modelo"><i class="fa fa-check"></i><b>7.2.1</b> Modelo</a></li>
<li class="chapter" data-level="7.2.2" data-path="modelos-lineares.html"><a href="modelos-lineares.html#estimativas-dos-parâmetros"><i class="fa fa-check"></i><b>7.2.2</b> Estimativas dos parâmetros</a></li>
<li class="chapter" data-level="7.2.3" data-path="modelos-lineares.html"><a href="modelos-lineares.html#análise-de-diagnóstico"><i class="fa fa-check"></i><b>7.2.3</b> Análise de diagnóstico</a></li>
<li class="chapter" data-level="7.2.4" data-path="modelos-lineares.html"><a href="modelos-lineares.html#modelo-rpo"><i class="fa fa-check"></i><b>7.2.4</b> Modelo RPO</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="modelos-lineares.html"><a href="modelos-lineares.html#regressão-linear-múltipla"><i class="fa fa-check"></i><b>7.3</b> Regressão Linear Múltipla</a></li>
<li class="chapter" data-level="7.4" data-path="modelos-lineares.html"><a href="modelos-lineares.html#regressão-logística"><i class="fa fa-check"></i><b>7.4</b> Regressão Logística</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="modelos-lineares.html"><a href="modelos-lineares.html#variáveis-bináriasdicotômicas"><i class="fa fa-check"></i><b>7.4.1</b> Variáveis binárias/dicotômicas</a></li>
<li class="chapter" data-level="7.4.2" data-path="modelos-lineares.html"><a href="modelos-lineares.html#o-modelo-de-regressão-logística"><i class="fa fa-check"></i><b>7.4.2</b> O modelo de regressão logística</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="aprendizadodemaquina.html"><a href="aprendizadodemaquina.html"><i class="fa fa-check"></i><b>8</b> Aprendizado de Máquina</a>
<ul>
<li class="chapter" data-level="8.1" data-path="aprendizadodemaquina.html"><a href="aprendizadodemaquina.html#análise-de-componentes-principais-pca"><i class="fa fa-check"></i><b>8.1</b> Análise de Componentes Principais (<em>PCA</em>)</a></li>
<li class="chapter" data-level="8.2" data-path="aprendizadodemaquina.html"><a href="aprendizadodemaquina.html#técnicas-de-agrupamento"><i class="fa fa-check"></i><b>8.2</b> Técnicas de Agrupamento</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="aprendizadodemaquina.html"><a href="aprendizadodemaquina.html#medidas-de-similaridade-e-dissimilaridade"><i class="fa fa-check"></i><b>8.2.1</b> Medidas de similaridade e dissimilaridade</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="aprendizadodemaquina.html"><a href="aprendizadodemaquina.html#métodos-hierárquicos"><i class="fa fa-check"></i><b>8.3</b> Métodos hierárquicos</a></li>
<li class="chapter" data-level="8.4" data-path="aprendizadodemaquina.html"><a href="aprendizadodemaquina.html#métodos-não-hierárquicos-de-particionamento"><i class="fa fa-check"></i><b>8.4</b> Métodos não hierárquicos (de particionamento)</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="aprendizadodemaquina.html"><a href="aprendizadodemaquina.html#k-médias"><i class="fa fa-check"></i><b>8.4.1</b> K-médias</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="seriestemporais.html"><a href="seriestemporais.html"><i class="fa fa-check"></i><b>9</b> Séries Temporais</a>
<ul>
<li class="chapter" data-level="9.1" data-path="seriestemporais.html"><a href="seriestemporais.html#impacto-causal"><i class="fa fa-check"></i><b>9.1</b> Impacto Causal</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="referências.html"><a href="referências.html"><i class="fa fa-check"></i><b>10</b> Referências</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Fundamentos de Estatística para Ciência de Dados</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="estatistica-descritiva" class="section level1" number="2">
<h1><span class="header-section-number">2</span> Estatística Descritiva</h1>
<p>A <em>Estatística Descritiva</em> está diretamente ligada à organização e descrição dos dados. É utilizada para avaliar como as observações se distribuem, onde estão posicionadas e como se apresentam em termos de dispersão e associação. Neste capítulo serão introduzidos conceitos e métodos descritivos, ponto de partida da <em>análise exploratória de dados</em>, passo fundamental para análises estatísticas mais avançadas.</p>
<div id="variáveis" class="section level2" number="2.1">
<h2><span class="header-section-number">2.1</span> Variáveis</h2>
<p>Variável é uma característica medida nos universos ou amostras. As <em>variáveis qualitativas</em> ou <em>atributos</em> avaliam características não numéricas no conjunto de interesse, como gênereo, time de futebol e nível de escolaridade. As <em>variáveis quantitativas</em> medem características numéricas, como número de alunos prestando atenção ou tempo de uma música em segundos. Podem ser classificadas conforme a Figura a seguir.</p>
<center>
<img src="img/variavel.png" />
</center>
<div id="variavel-qualitativa-nominal" class="section level3" number="2.1.1">
<h3><span class="header-section-number">2.1.1</span> Variável qualitativa nominal</h3>
<p>Variáveis <em>qualitativas nominais</em> possuem o menor grau de informação dentre os quatro tipos propostos, permitindo apenas a avaliação de frequências e ordenações arbitrárias. Aplicam-se em avaliações de grupos não ordenados, tais como ‘gênero’, ‘religião’, ‘raça’, ‘cor preferida’, ‘bairro onde reside’, ‘time de futebol do coração’, etc.</p>

<div class="example">
<p><span id="exm:var-nominal" class="example"><strong>Example 2.1  </strong></span>(Time de futebol do coração) Suponha um lugar onde tudo seja tratado de maneira dicotômica. Como exercício, no primeiro dia de aula de Estatística as pessoas são questionadas quanto ao ‘time de futebol do coração’ através do voto secreto em uma cédula, onde estão listados os dois times locais. Não existe informação prévia que obrigue a dispor na listagem qualquer time antes ou depois de outro. Por este motivo optou-se pela ordenação alfabética – apesar do princípio de tumulto –, resultando na lista</p>
<center>
<img src="img/maragato_ximango.png" />
</center>
<p>Os mais tradicionalistas gritavam palavras de ordem, preferindo a grafia</p>
<center>
<img src="img/chimango_maragato.png" />
</center>
</div>
</div>
<div id="variavel-qualitativa-ordinal" class="section level3" number="2.1.2">
<h3><span class="header-section-number">2.1.2</span> Variável qualitativa ordinal</h3>
<p>Variáveis <em>qualitativas ordinais</em> possuem grau de informação maior em relação às nominais pois são dotadas de uma ordenação prévia, permitindo comparações entre as observações. As variáveis de natureza ordinal são utilizadas quando avaliam-se medidas tais como ‘colocação em um torneio esportivo’, ‘grau de escolaridade’, ‘classificação de um restaurante quanto à qualidade da comida’, etc.</p>

<div class="example">
<span id="exm:var-ordinal1" class="example"><strong>Example 2.2  </strong></span>(Colocação no vestibular) A variável ‘colocação geral no vestibular’ é classificada como qualitativa ordinal pois indica a ordenação do vestibulando em comparação aos demais, mesmo que não se conheça a nota final de cada candidato. <span class="math inline">\(\\\)</span>
</div>

<div class="example">
<span id="exm:var-ordinal2" class="example"><strong>Example 2.3  </strong></span>(Escala de Likert) Quando deseja-se medir o grau de satisfação em relação a algum bem ou serviço, pode-se utilizar a Escala de Likert de <span class="math inline">\(k\)</span> níveis. Uma vantagem de utilizar <span class="math inline">\(k\)</span> par é que obriga-se o respondente a se posicionar a favor/contra, acima/abaixo. Se um empresário utilizar <span class="math inline">\(k=4\)</span>, pode fazer 1: Ruim, 2: Regular, 3: Bom, 4: Ótimo. Se <span class="math inline">\(k=5\)</span>, pode-se considerar 1: Péssimo, 2: Ruim, 3: Regular, 4: Bom, 5: Ótimo. <span class="math inline">\(\\\)</span>
</div>

<div class="example">
<span id="exm:var-ordinal3" class="example"><strong>Example 2.4  </strong></span>Corrida maluca) Suponha uma corrida disputada em Imaginationland<a href="#fn9" class="footnote-ref" id="fnref9"><sup>9</sup></a>, na qual Rubinho Barrichello tenha chegado na primeira colocação e Ayrton Senna na décima nona. As únicas informações de que dispomos apontam que i) Barrichello chegou antes de Senna, ii) ninguém chegou antes de Barrichello, iii) há 17 intermediários e iv) de fato, tudo aconteceu em Imaginationland. <span class="math inline">\(\\\)</span>
</div>
</div>
<div id="variavel-quantitativa-discreta" class="section level3" number="2.1.3">
<h3><span class="header-section-number">2.1.3</span> Variável quantitativa discreta</h3>
<p>Uma variável <em>quantitativa discreta</em> assume apenas valores inteiros, i.e., discretos. Tecnicamente as variáveis discretas são caracterizadas por conjuntos enumeráveis<a href="#fn10" class="footnote-ref" id="fnref10"><sup>10</sup></a> finitos ou infinitos.</p>

<div class="example">
<span id="exm:var-discr1" class="example"><strong>Example 2.5  </strong></span>(Número de filhos) Suponha que deseja-se observar o número de filhos de mulheres atendidas em um hospital. Para cada mulher entrevistada, o conjunto de possíveis respostas para a pergunta ‘quantos filhos a senhora tem?’ é <span class="math inline">\(F = \lbrace 0, 1, 2, \ldots, k \rbrace\)</span>, onde <span class="math inline">\(k\)</span> é o número máximo de filhos que uma mulher possa ter ao longo de sua vida. O recorde mundial é <span class="math inline">\(k=69\)</span>, atribuído à russa Valentina Vassilyeva. Este é um conjunto enumerável finito. <span class="math inline">\(\\\)</span>
</div>

<div class="example">
<span id="exm:var-discr2" class="example"><strong>Example 2.6  </strong></span>(Pontos em um dado lançado <span class="math inline">\(k\)</span> vezes) Suponha <span class="math inline">\(k\)</span> lançamentos de um dado. Em cada lançamento é anotada a face resultante, somada aos valores obtidos nos <span class="math inline">\(k-1\)</span> lançamentos anteriores. O conjunto de possíveis resultados deste experimento é <span class="math inline">\(S = \lbrace k, k+1, \ldots, 6k \rbrace\)</span>. Este é um conjunto enumerável finito. Como exercício, faça <span class="math inline">\(k=4\)</span> e releia a sentença anterior substituindo os valores. <span class="math inline">\(\\\)</span>
</div>

<div class="example">
<span id="exm:var-discr3" class="example"><strong>Example 2.7  </strong></span>(Consumo de uma engrenagem moto-contínua) Suponha uma engrenagem eterna, com consumo medido em PAB<a href="#fn11" class="footnote-ref" id="fnref11"><sup>11</sup></a>. O conjunto do número possível de passos é <span class="math inline">\(S = \lbrace 1, 2, \ldots \rbrace\)</span>. Este é um conjunto enumerável infinito. <span class="math inline">\(\\\)</span>
</div>

<div class="example">
<span id="exm:var-discr4" class="example"><strong>Example 2.8  </strong></span>(Pilcher’s Squad) Norman Pilcher foi o criador da Drug Squad, e ganhou notoriedade nos anos 60 por prender artistas como Mick Jagger e John Lennon. O conjunto de artistas que o Sargento Pilcher poderia prender é <span class="math inline">\(A = \lbrace a_{1}, a_{2}, \ldots, a_{k} \rbrace\)</span>, onde <span class="math inline">\(k\)</span> representa o número de artistas disponíveis para serem presos. Este é um conjunto enumerável finito. <span class="math inline">\(\\\)</span>
</div>
</div>
<div id="variavel-quantitativa-continua" class="section level3" number="2.1.4">
<h3><span class="header-section-number">2.1.4</span> Variável quantitativa contínua</h3>
<p>A classe de variáveis <em>quantitativas contínuas</em> é caracterizada por permitir a observação de qualquer subconjunto dos números reais como resultado, i.e., permite resultados não inteiros. É utilizada para avaliar tempo, distâncias, áreas, volumes ou qualquer outra grandeza numérica de caráter não enumerável<a href="#fn12" class="footnote-ref" id="fnref12"><sup>12</sup></a>. Tal como nas variáveis discretas, é possível avaliar relações matemáticas entre os valores observados.</p>

<div class="example">
<span id="exm:var-cont1" class="example"><strong>Example 2.9  </strong></span>(Proporção de bulímicas) Suponha que um grupo de pesquisadores está interessado em avaliar a ‘proporção de mulheres bulímicas no Rio Grande do Sul’. Este valor está obrigatoriamente entre 0 e 1 (ou 0% e 100%), podendo ser representado pelo conjunto não enumerável <span class="math inline">\(\Omega = \lbrace b \in \mathbb{R} : 0 \le b\le 1 \rbrace\)</span>. <span class="math inline">\(\\\)</span>
</div>

<div class="example">
<span id="exm:var-cont2" class="example"><strong>Example 2.10  </strong></span>(Idade) A variável ‘idade’ é classificada como quantitativa contínua por representar uma noção temporal. Caso haja interesse, pode-se dizer que em certo instante do tempo João apresentou <span class="math inline">\(31.990192013071629871269817323644\)</span> anos de idade. Na prática, porém, geralmente as idades são truncadas, sendo que João provavelmente afirmaria ter 31 anos de idade mesmo um dia antes do seu 32aniversário. Na melhor das situações as idades são observadas com precisão de dias, calculando-se a idade do indivíduo pela diferença entre o dia de hoje e o seu dia de nascimento, convertendo o valor para anos. O conjunto dos possíveis tempos de vida de um ser humano é dado por <span class="math inline">\(\Omega = \lbrace t \in \mathbb{R} : 0 &lt; t \le T \rbrace\)</span>, onde <span class="math inline">\(T\)</span> é a idade máxima em anos que um ser humano pode atingir. Segundo o , <span class="math inline">\(T=122.44931506849315\)</span>, alcançado pela francesa Jeanne Louise Calment. <span class="math inline">\(\Omega\)</span> é dito não enumerável visto não ser possível contabilizar o seu número de elementos. <span class="math inline">\(\\\)</span>
</div>

<div class="example">
<p><span id="exm:var-cont3" class="example"><strong>Example 2.11  </strong></span>(Descendo o nível) Suponha que um grupo de pessoas foi avaliado em relação à variável ‘idade’ medida em anos, considerando-se a hora e minuto do nascimento. É possível transformá-la na variável ‘idade discreta’ simplesmente truncando os valores observados. Da mesma forma, pode-se tranformá-la na variável ‘idade ordinal’, classificando-a de acordo com a tabela a seguir.</p>
<table>
<thead>
<tr class="header">
<th align="center">i</th>
<th align="center">Faixa etária</th>
<th align="center">Classificação</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">Até 10 anos</td>
<td align="center">Criança</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">10 <span class="math inline">\(\vdash\)</span> 13</td>
<td align="center">Pré-adolescente</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">13 <span class="math inline">\(\vdash\)</span> 18</td>
<td align="center">Adolescente</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">18 <span class="math inline">\(\vdash\)</span> 35</td>
<td align="center">Adulto jovem</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">35 <span class="math inline">\(\vdash\)</span> 45</td>
<td align="center">Adulto</td>
</tr>
<tr class="even">
<td align="center">6</td>
<td align="center">45 <span class="math inline">\(\vdash\)</span> 65</td>
<td align="center">Adulto maduro</td>
</tr>
<tr class="odd">
<td align="center">7</td>
<td align="center">65 <span class="math inline">\(\vdash\)</span> 75</td>
<td align="center">Idoso jovem</td>
</tr>
<tr class="even">
<td align="center">8</td>
<td align="center">75 +</td>
<td align="center">Idoso</td>
</tr>
</tbody>
</table>
Note que se uma pessoa tem 31.990192013071629871269817323644 anos de idade (contínua), pode-se considerar a idade truncada de 31 anos (discreta) e classificá-la como um ‘adulto jovem’ (ordinal). Porém, dado que uma pessoa é classificada como adulto jovem, é possível apenas afirmar que ela tem idade entre 18 anos (completos) e 35 anos (incompletos) segundo a classificação proposta. <span class="math inline">\(\\\)</span>
</div>
<p>Cada tipo de variável apresenta um nível de informação que deve ser respeitado. É possível ir de um nível maior de classificação para um nível menor, mas jamais ao contrário. É válido lembrar que perde-se informação ao descer o nível de classificação da variável. É bastante comum, porém, encontrar trabalhos utilizando níveis de classificação inapropriados, conduzindo a técnicas não adequadas que implicam em conclusões equivocadas.</p>

<div class="exercise">
<p><span id="exr:class-var" class="exercise"><strong>Exercise 2.1  </strong></span>Classifique as variáveis abaixo (qualitativa nominal/ordinal, quantitativa discreta/contínua).</p>
<ol style="list-style-type: lower-alpha">
<li>Número de geladeiras em casa</li>
<li>Temperaturas da água da piscina em um dia de verão</li>
<li>Número de suicídios em uma cidade no decorrer do ano passado</li>
<li>Concentração de chumbo em uma amostra de água</li>
<li>Lista de editoras de livros</li>
<li>Grau de satisfação dos clientes que frequentam uma rinha de galo</li>
<li>Marcas de amaciantes para roupas</li>
<li>Tempo que um paciente sobrevive após determinado diagnóstico</li>
<li>Participação de mercado (<em>market share</em>)</li>
<li>Classificação em uma corrida de banheiras</li>
<li>Tempo final de cada corredor</li>
<li>Lista dos nomes das banheiras participantes, tal como ‘Dick Vigarista’ e ‘Trollface’</li>
<li>Distância de Estambul ao Rio de Janeiro<br />
</li>
</ol>
</div>
</div>
</div>
<div id="distribuicao-de-frequencia" class="section level2" number="2.2">
<h2><span class="header-section-number">2.2</span> Distribuição de Frequência</h2>
<div id="db-rol-eo" class="section level3" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Dados brutos, Rol e Estatísticas de Ordem</h3>
<p>Quando observa-se alguma variável de interesse, em geral anotam-se os resultados na ordem em que aparecem. Esta lista de dados não ordenada é conhecida como <em>lista de dados brutos</em>. Quando ordenam-se estes dados – em ordem crescente ou decrescente – obtém-se um <em>rol</em>, dando origem às <em>estatísticas de ordem</em>. Em uma distribuição de <span class="math inline">\(n\)</span> elementos <span class="math inline">\(x_{1}\)</span>, <span class="math inline">\(x_{2}\)</span>, <span class="math inline">\(\ldots\)</span>, <span class="math inline">\(x_{n}\)</span> observados sequencialmente, denotam-se os dados ordenados de forma crescente por <span class="math inline">\(x_{(1)}\)</span>, <span class="math inline">\(x_{(2)}\)</span>, <span class="math inline">\(\ldots\)</span>, <span class="math inline">\(x_{(n)}\)</span> e, analogamente, <span class="math inline">\(x_{(n)}\)</span>, <span class="math inline">\(x_{(n-1)}\)</span>, <span class="math inline">\(\ldots\)</span>, <span class="math inline">\(x_{(1)}\)</span> para a ordenação decrescente.</p>

<div class="example">
<p><span id="exm:rol1" class="example"><strong>Example 2.12  </strong></span>(Rol) Se ordenarmos os dados observados da variável <span class="math inline">\(X\)</span>:‘número de passos até a lixiera mais próxima’, obtemos o rol conforme tabela a seguir. O menor número de passos caminhados foi sete, representado por <span class="math inline">\(x_{(1)}=7\)</span>, e o maior foi quatrocentos e dois, representado por <span class="math inline">\(x_{(6)}=402\)</span>.</p>
<table>
<thead>
<tr class="header">
<th align="center"><span class="math inline">\(x_{(1)}\)</span></th>
<th align="center"><span class="math inline">\(x_{(2)}\)</span></th>
<th align="center"><span class="math inline">\(x_{(3)}\)</span></th>
<th align="center"><span class="math inline">\(x_{(4)}\)</span></th>
<th align="center"><span class="math inline">\(x_{(5)}\)</span></th>
<th align="center"><span class="math inline">\(x_{(6)}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">7</td>
<td align="center">20</td>
<td align="center">124</td>
<td align="center">186</td>
<td align="center">191</td>
<td align="center">402</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="estatistica-descritiva.html#cb28-1"></a>(x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">186</span>,<span class="dv">402</span>,<span class="dv">191</span>,<span class="dv">20</span>,<span class="dv">7</span>,<span class="dv">124</span>))  <span class="co"># Criando e apresentando o vetor original de dados brutos</span></span></code></pre></div>
<pre><code>## [1] 186 402 191  20   7 124</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="estatistica-descritiva.html#cb30-1"></a><span class="kw">sort</span>(x)                         <span class="co"># Apresentando o rol, ou vetor ordenado. Teste ?order</span></span></code></pre></div>
<pre><code>## [1]   7  20 124 186 191 402</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="estatistica-descritiva.html#cb32-1"></a><span class="kw">sort</span>(x, <span class="dt">decreasing =</span> T)         <span class="co"># Ordem decrescente, onde T indica TRUE (padrão: FALSE)</span></span></code></pre></div>
<pre><code>## [1] 402 191 186 124  20   7</code></pre>
<p>Em um primeiro momento estas definições podem parecer ultrapassadas, mas são de grande importância na construção de métodos avançados de análise de dados. Como atualmente trabalham-se com bases de dados em formato eletrônico, em geral é fácil realizar a ordenação de grandes volumes de dados. É importante ressaltar, porém, que em certos casos é necessário muito poder de processamento para executar tais ordenações, podendo se tornarem impraticáveis pelo alto custo computacional.</p>

<div class="exercise">
<p><span id="exr:rol2" class="exercise"><strong>Exercise 2.2  </strong></span>Considere o conjunto de dados <span class="math inline">\(10,-4,5,7,1,3,9\)</span>.</p>
<ol style="list-style-type: lower-alpha">
<li>Obtenha o rol.</li>
<li>Indique e interprete <span class="math inline">\(x_{(4)}\)</span>.</li>
</ol>
</div>

<div class="exercise">
<p><span id="exr:unnamed-chunk-9" class="exercise"><strong>Exercise 2.3  </strong></span>Utilizando a função <code>sort</code>, encontre o rol das colunas <code>filhos</code> e <code>altura</code> disponíveis em <a href="http://filipezabala.com/data/hospital.txt" class="uri">http://filipezabala.com/data/hospital.txt</a>.</p>
</div>
</div>
<div id="tab-freq-univ-discr" class="section level3" number="2.2.2">
<h3><span class="header-section-number">2.2.2</span> Tabela de frequência univariada discreta</h3>
<p>Listas muito longas, ainda que ordenadas, não costumam ser de fácil compreensão. Assim, a <em>tabela de frequência univariada discreta</em> é uma boa maneira de consolidar os dados de uma variável que assuma, como regra-de-bolso, até 10 diferentes valores. Esta tabela deve apresentar pelo menos uma coluna descrevendo a variável de interesse e uma coluna com a <em>frequência (da classe)</em>, i.e., o número de observações contempladas em cada categoria. Sugere-se também a apresentação de uma coluna indicando a classe, denotada por <span class="math inline">\(i\)</span> conforme Tabela a seguir.</p>
<table>
<colgroup>
<col width="7%" />
<col width="8%" />
<col width="8%" />
<col width="9%" />
<col width="19%" />
<col width="9%" />
<col width="25%" />
<col width="12%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"><span class="math inline">\(i\)</span></th>
<th align="center"><span class="math inline">\(x_{i}\)</span></th>
<th align="center"><span class="math inline">\(f_{i}\)</span></th>
<th align="center"><span class="math inline">\(f_{r_{i}}\)</span></th>
<th align="center"><span class="math inline">\(F_{i}\)</span></th>
<th align="center"><span class="math inline">\(F_{r_{i}}\)</span></th>
<th align="center"><span class="math inline">\(\Finv_{i}\)</span></th>
<th align="center"><span class="math inline">\(\Finv_{r_{i}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center"><span class="math inline">\(x_{1}\)</span></td>
<td align="center"><span class="math inline">\(f_{1}\)</span></td>
<td align="center"><span class="math inline">\(f_{1}/n\)</span></td>
<td align="center"><span class="math inline">\(F_{1}=f_{1}\)</span></td>
<td align="center"><span class="math inline">\(F_{1}/n\)</span></td>
<td align="center"><span class="math inline">\(\Finv_{1}=\Finv_{2}+f_{1}=n\)</span></td>
<td align="center"><span class="math inline">\(\Finv_{1}/n=1\)</span></td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center"><span class="math inline">\(x_{2}\)</span></td>
<td align="center"><span class="math inline">\(f_{2}\)</span></td>
<td align="center"><span class="math inline">\(f_{2}/n\)</span></td>
<td align="center"><span class="math inline">\(F_{2}=F_{1}+f_{2}\)</span></td>
<td align="center"><span class="math inline">\(F_{2}/n\)</span></td>
<td align="center"><span class="math inline">\(\Finv_{2}=\Finv_{3}+f_{2}\)</span></td>
<td align="center"><span class="math inline">\(\Finv_{2}/n\)</span></td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center"><span class="math inline">\(x_{3}\)</span></td>
<td align="center"><span class="math inline">\(f_{3}\)</span></td>
<td align="center"><span class="math inline">\(f_{3}/n\)</span></td>
<td align="center"><span class="math inline">\(F_{3}=F_{2}+f_{3}\)</span></td>
<td align="center"><span class="math inline">\(F_{3}/n\)</span></td>
<td align="center"><span class="math inline">\(\Finv_{3}=\Finv_{4}+f_{3}\)</span></td>
<td align="center"><span class="math inline">\(\Finv_{3}/n\)</span></td>
</tr>
<tr class="even">
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="odd">
<td align="center"><span class="math inline">\(k-2\)</span></td>
<td align="center"><span class="math inline">\(x_{k-2}\)</span></td>
<td align="center"><span class="math inline">\(f_{k-2}\)</span></td>
<td align="center"><span class="math inline">\(f_{k-2}/n\)</span></td>
<td align="center"><span class="math inline">\(F_{k-2}=F_{k-3}+f_{k-2}\)</span></td>
<td align="center"><span class="math inline">\(F_{k-2}/n\)</span></td>
<td align="center"><span class="math inline">\(\Finv_{k-2}=\Finv_{k-1}+f_{k-2}\)</span></td>
<td align="center"><span class="math inline">\(\Finv_{k-2}/n\)</span></td>
</tr>
<tr class="even">
<td align="center"><span class="math inline">\(k-1\)</span></td>
<td align="center"><span class="math inline">\(x_{k-1}\)</span></td>
<td align="center"><span class="math inline">\(f_{k-1}\)</span></td>
<td align="center"><span class="math inline">\(f_{k-1}/n\)</span></td>
<td align="center"><span class="math inline">\(F_{k-1}=F_{k-2}+f_{k-1}\)</span></td>
<td align="center"><span class="math inline">\(F_{k-1}/n\)</span></td>
<td align="center"><span class="math inline">\(\Finv_{k-1}=\Finv_{k}+f_{k-1}\)</span></td>
<td align="center"><span class="math inline">\(\Finv_{k-1}/n\)</span></td>
</tr>
<tr class="odd">
<td align="center"><span class="math inline">\(k\)</span></td>
<td align="center"><span class="math inline">\(x_{k}\)</span></td>
<td align="center"><span class="math inline">\(f_{k}\)</span></td>
<td align="center"><span class="math inline">\(f_{k}/n\)</span></td>
<td align="center"><span class="math inline">\(F_{k}=F_{k-1}+f_{k}=n\)</span></td>
<td align="center"><span class="math inline">\(F_{k}/n=1\)</span></td>
<td align="center"><span class="math inline">\(\Finv_{k}=f_{k}\)</span></td>
<td align="center"><span class="math inline">\(\Finv_{k}/n\)</span></td>
</tr>
<tr class="even">
<td align="center">Total</td>
<td align="center">-</td>
<td align="center"><span class="math inline">\(n\)</span></td>
<td align="center">1</td>
<td align="center">-</td>
<td align="center">-</td>
<td align="center">-</td>
<td align="center">-</td>
</tr>
</tbody>
</table>
<p>Para a classe genérica <span class="math inline">\(i\)</span> são calculadas as seguintes frequências:<br />
- <span class="math inline">\(f_{i}\)</span>: Frequência (simples/absoluta)<br />
- <span class="math inline">\(f_{r_{i}}\)</span>: Frequência relativa<br />
- <span class="math inline">\(F_{i}\)</span>: Frequência acumulada<br />
- <span class="math inline">\(F_{r_{i}}\)</span>: Frequência acumulada relativa<br />
- <span class="math inline">\(\Finv_{i}\)</span>: Frequência acumulada inversa<br />
- <span class="math inline">\(\Finv_{r_{i}}\)</span>: Frequência acumulada inversa relativa</p>

<div class="example">
<p><span id="exm:filhos" class="example"><strong>Example 2.13  </strong></span>(Número de filhos revisitado) Do Exemplo <a href="estatistica-descritiva.html#exm:var-discr1">2.5</a> observou-se a variável</p>
<blockquote>
<p><span class="math inline">\(X\)</span>: ‘número de filhos de mulheres atendidas em um hospital de Porto Alegre em 2019’.</p>
</blockquote>
<p>A Tabela a seguir apresenta os dados na ordem em que foram observados. Este tipo de apresentação é bastante completo, mas dificulta a extração de informações relevantes. Como exercício, indique o número máximo de filhos observados na amostra.</p>
<table>
<thead>
<tr class="header">
<th align="center"><span class="math inline">\(i\)</span></th>
<th align="center"><span class="math inline">\(x_{i}\)</span></th>
<th align="center"><span class="math inline">\(i\)</span></th>
<th align="center"><span class="math inline">\(x_{i}\)</span></th>
<th align="center"><span class="math inline">\(i\)</span></th>
<th align="center"><span class="math inline">\(x_{i}\)</span></th>
<th align="center"><span class="math inline">\(i\)</span></th>
<th align="center"><span class="math inline">\(x_{i}\)</span></th>
<th align="center"><span class="math inline">\(i\)</span></th>
<th align="center"><span class="math inline">\(x_{i}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">2</td>
<td align="center">21</td>
<td align="center">2</td>
<td align="center">41</td>
<td align="center">1</td>
<td align="center">61</td>
<td align="center">3</td>
<td align="center">81</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">0</td>
<td align="center">22</td>
<td align="center">3</td>
<td align="center">42</td>
<td align="center">1</td>
<td align="center">62</td>
<td align="center">0</td>
<td align="center">82</td>
<td align="center">1</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">1</td>
<td align="center">23</td>
<td align="center">1</td>
<td align="center">43</td>
<td align="center">4</td>
<td align="center">63</td>
<td align="center">2</td>
<td align="center">83</td>
<td align="center">2</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">2</td>
<td align="center">24</td>
<td align="center">2</td>
<td align="center">44</td>
<td align="center">1</td>
<td align="center">64</td>
<td align="center">0</td>
<td align="center">84</td>
<td align="center">2</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">4</td>
<td align="center">25</td>
<td align="center">2</td>
<td align="center">45</td>
<td align="center">1</td>
<td align="center">65</td>
<td align="center">2</td>
<td align="center">85</td>
<td align="center">2</td>
</tr>
<tr class="even">
<td align="center">6</td>
<td align="center">2</td>
<td align="center">26</td>
<td align="center">1</td>
<td align="center">46</td>
<td align="center">3</td>
<td align="center">66</td>
<td align="center">2</td>
<td align="center">86</td>
<td align="center">2</td>
</tr>
<tr class="odd">
<td align="center">7</td>
<td align="center">1</td>
<td align="center">27</td>
<td align="center">4</td>
<td align="center">47</td>
<td align="center">1</td>
<td align="center">67</td>
<td align="center">2</td>
<td align="center">87</td>
<td align="center">2</td>
</tr>
<tr class="even">
<td align="center">8</td>
<td align="center">4</td>
<td align="center">28</td>
<td align="center">0</td>
<td align="center">48</td>
<td align="center">1</td>
<td align="center">68</td>
<td align="center">1</td>
<td align="center">88</td>
<td align="center">4</td>
</tr>
<tr class="odd">
<td align="center">9</td>
<td align="center">2</td>
<td align="center">29</td>
<td align="center">1</td>
<td align="center">49</td>
<td align="center">4</td>
<td align="center">69</td>
<td align="center">2</td>
<td align="center">89</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center">10</td>
<td align="center">3</td>
<td align="center">30</td>
<td align="center">6</td>
<td align="center">50</td>
<td align="center">2</td>
<td align="center">70</td>
<td align="center">3</td>
<td align="center">90</td>
<td align="center">2</td>
</tr>
<tr class="odd">
<td align="center">11</td>
<td align="center">3</td>
<td align="center">31</td>
<td align="center">1</td>
<td align="center">51</td>
<td align="center">2</td>
<td align="center">71</td>
<td align="center">1</td>
<td align="center">91</td>
<td align="center">1</td>
</tr>
<tr class="even">
<td align="center">12</td>
<td align="center">2</td>
<td align="center">32</td>
<td align="center">1</td>
<td align="center">52</td>
<td align="center">4</td>
<td align="center">72</td>
<td align="center">3</td>
<td align="center">92</td>
<td align="center">3</td>
</tr>
<tr class="odd">
<td align="center">13</td>
<td align="center">3</td>
<td align="center">33</td>
<td align="center">1</td>
<td align="center">53</td>
<td align="center">1</td>
<td align="center">73</td>
<td align="center">1</td>
<td align="center">93</td>
<td align="center">3</td>
</tr>
<tr class="even">
<td align="center">14</td>
<td align="center">2</td>
<td align="center">34</td>
<td align="center">1</td>
<td align="center">54</td>
<td align="center">3</td>
<td align="center">74</td>
<td align="center">3</td>
<td align="center">94</td>
<td align="center">4</td>
</tr>
<tr class="odd">
<td align="center">15</td>
<td align="center">1</td>
<td align="center">35</td>
<td align="center">0</td>
<td align="center">55</td>
<td align="center">1</td>
<td align="center">75</td>
<td align="center">3</td>
<td align="center">95</td>
<td align="center">5</td>
</tr>
<tr class="even">
<td align="center">16</td>
<td align="center">4</td>
<td align="center">36</td>
<td align="center">2</td>
<td align="center">56</td>
<td align="center">2</td>
<td align="center">76</td>
<td align="center">4</td>
<td align="center">96</td>
<td align="center">1</td>
</tr>
<tr class="odd">
<td align="center">17</td>
<td align="center">2</td>
<td align="center">37</td>
<td align="center">3</td>
<td align="center">57</td>
<td align="center">0</td>
<td align="center">77</td>
<td align="center">2</td>
<td align="center">97</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center">18</td>
<td align="center">0</td>
<td align="center">38</td>
<td align="center">3</td>
<td align="center">58</td>
<td align="center">2</td>
<td align="center">78</td>
<td align="center">1</td>
<td align="center">98</td>
<td align="center">0</td>
</tr>
<tr class="odd">
<td align="center">19</td>
<td align="center">1</td>
<td align="center">39</td>
<td align="center">1</td>
<td align="center">59</td>
<td align="center">3</td>
<td align="center">79</td>
<td align="center">2</td>
<td align="center">99</td>
<td align="center">3</td>
</tr>
<tr class="even">
<td align="center">20</td>
<td align="center">4</td>
<td align="center">40</td>
<td align="center">2</td>
<td align="center">60</td>
<td align="center">3</td>
<td align="center">80</td>
<td align="center">3</td>
<td align="center">100</td>
<td align="center">2</td>
</tr>
</tbody>
</table>
</div>
<p>A Tabela a seguir apresenta o número de filhos ordenados, fornecendo ainda algumas frequências que auxiliam o entendimento da distribuição. Com a apresentação neste formato, facilmente observa-se o máximo de 6 filhos na amostra, ao contrário da tabela de dados brutos. Perde-se apenas a ordem na qual os dados foram observados, o que em geral não é do interesse do pesquisador.</p>
<table>
<thead>
<tr class="header">
<th align="center"><span class="math inline">\(i\)</span></th>
<th align="center"><span class="math inline">\(x_{i}\)</span></th>
<th align="center"><span class="math inline">\(f_{i}\)</span></th>
<th align="center"><span class="math inline">\(f_{r_{i}}\)</span></th>
<th align="center"><span class="math inline">\(F_{i}\)</span></th>
<th align="center"><span class="math inline">\(F_{r_{i}}\)</span></th>
<th align="center"><span class="math inline">\(\Finv_{i}\)</span></th>
<th align="center"><span class="math inline">\(\Finv_{r_{i}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">0</td>
<td align="center">11</td>
<td align="center"><span class="math inline">\(11/100=0.11\)</span></td>
<td align="center">11</td>
<td align="center"><span class="math inline">\(11/100=0.11\)</span></td>
<td align="center"><span class="math inline">\(89+11=100\)</span></td>
<td align="center"><span class="math inline">\(100/100=1\)</span></td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">1</td>
<td align="center">27</td>
<td align="center"><span class="math inline">\(27/100=0.27\)</span></td>
<td align="center"><span class="math inline">\(11+27=38\)</span></td>
<td align="center"><span class="math inline">\(38/100=0.38\)</span></td>
<td align="center"><span class="math inline">\(62+27=89\)</span></td>
<td align="center"><span class="math inline">\(89/100=0.89\)</span></td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">2</td>
<td align="center">30</td>
<td align="center"><span class="math inline">\(30/100=0.30\)</span></td>
<td align="center"><span class="math inline">\(38+30=68\)</span></td>
<td align="center"><span class="math inline">\(68/100=0.68\)</span></td>
<td align="center"><span class="math inline">\(32+30=62\)</span></td>
<td align="center"><span class="math inline">\(62/100=0.62\)</span></td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">3</td>
<td align="center">19</td>
<td align="center"><span class="math inline">\(19/100=0.19\)</span></td>
<td align="center"><span class="math inline">\(68+19=87\)</span></td>
<td align="center"><span class="math inline">\(87/100=0.87\)</span></td>
<td align="center"><span class="math inline">\(13+19=32\)</span></td>
<td align="center"><span class="math inline">\(32/100=0.32\)</span></td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">4</td>
<td align="center">11</td>
<td align="center"><span class="math inline">\(11/100=0.11\)</span></td>
<td align="center"><span class="math inline">\(87+11=98\)</span></td>
<td align="center"><span class="math inline">\(98/100=0.98\)</span></td>
<td align="center"><span class="math inline">\(2+11=13\)</span></td>
<td align="center"><span class="math inline">\(13/100=0.13\)</span></td>
</tr>
<tr class="even">
<td align="center">6</td>
<td align="center">5</td>
<td align="center">1</td>
<td align="center"><span class="math inline">\(1/100=0.01\)</span></td>
<td align="center"><span class="math inline">\(98+1=99\)</span></td>
<td align="center"><span class="math inline">\(99/100=0.99\)</span></td>
<td align="center"><span class="math inline">\(1+1=2\)</span></td>
<td align="center"><span class="math inline">\(2/100=0.02\)</span></td>
</tr>
<tr class="odd">
<td align="center">7</td>
<td align="center">6</td>
<td align="center">1</td>
<td align="center"><span class="math inline">\(1/100=0.01\)</span></td>
<td align="center"><span class="math inline">\(99+1=100\)</span></td>
<td align="center"><span class="math inline">\(100/100=1\)</span></td>
<td align="center">1</td>
<td align="center"><span class="math inline">\(1/100=0.01\)</span></td>
</tr>
<tr class="even">
<td align="center">Total</td>
<td align="center">-</td>
<td align="center">100</td>
<td align="center">1</td>
<td align="center">-</td>
<td align="center">-</td>
<td align="center">-</td>
<td align="center">-</td>
</tr>
</tbody>
</table>
<p>Note que a coluna <span class="math inline">\(i\)</span> da Tabela acima indica a ordem da mulher entrevistada, enquanto na Tabela de dados brutos <span class="math inline">\(i\)</span> indica a classe. Por exemplo, <span class="math inline">\(i=4\)</span> indica a quarta mulher entrevistada, que no caso informou ter <span class="math inline">\(x_{4}=2\)</span> filhos. Na Tabela acima, <span class="math inline">\(i=4\)</span> indica a quarta classe onde <span class="math inline">\(x_{4}=3\)</span>, i.e., a classe das mulheres que possuem 3 filhos.</p>
<p>As únicas colunas que exigem a leitura dos dados brutos são a da variável <span class="math inline">\(x_i\)</span> e a da frequência <span class="math inline">\(f_i\)</span>; as demais são calculadas a partir de <span class="math inline">\(f_i\)</span>. A seguir estão alguns exemplos de interpretação das frequências apresentadas na Tabela acima.<br />
- <span class="math inline">\(f_{5}=11\)</span>, i.e., 11 mulheres possuem 4 filhos<br />
- <span class="math inline">\(f_{r_{5}}=0.11=11\%\)</span>, i.e., 11% das mulheres possuem 4 filhos<br />
- <span class="math inline">\(F_{4}=87\)</span>, i.e., 87 mulheres possuem até 3 filhos (ou ‘de zero a 3 filhos’, mas esta alternativa é menos elegante)<br />
- <span class="math inline">\(F_{r_{3}}=0.68=68\%\)</span>, i.e., 68% das mulheres possuem até 2 filhos<br />
- <span class="math inline">\(\Finv_{3}=62\)</span>, i.e., 62 mulheres têm pelo menos 2 filhos<br />
- <span class="math inline">\(\Finv_{r_{2}}=0.89=89\%\)</span>, i.e., 89% das mulheres têm pelo menos 1 filho</p>

<div class="example">
<span id="exm:filhos-r" class="example"><strong>Example 2.14  </strong></span>(Número de filhos R-visitado) Exemplo <a href="estatistica-descritiva.html#exm:filhos">2.13</a> utilizando R/RStudio.
</div>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="estatistica-descritiva.html#cb34-1"></a>hosp &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&#39;http://www.filipezabala.com/data/hospital.txt&#39;</span>, <span class="dt">head =</span> T)</span>
<span id="cb34-2"><a href="estatistica-descritiva.html#cb34-2"></a><span class="kw">dim</span>(hosp)       <span class="co"># Dimensão: 100 linhas por 2 colunas</span></span></code></pre></div>
<pre><code>## [1] 100   2</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="estatistica-descritiva.html#cb36-1"></a><span class="kw">head</span>(hosp)      <span class="co"># Apresenta as 6 primeiras linhas do objeto &#39;hosp&#39;; teste tail(hosp, 10)</span></span></code></pre></div>
<pre><code>##   filhos altura
## 1      2   1.59
## 2      0   1.58
## 3      1   1.70
## 4      2   1.62
## 5      4   1.67
## 6      2   1.62</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="estatistica-descritiva.html#cb38-1"></a><span class="kw">attach</span>(hosp, <span class="dt">warn=</span>F)                      <span class="co"># Para deixar as colunas de &#39;hosp&#39; disponíveis</span></span>
<span id="cb38-2"><a href="estatistica-descritiva.html#cb38-2"></a>(tab &lt;-<span class="st"> </span><span class="kw">table</span>(filhos))                    <span class="co"># Frequência (simples/absoluta)</span></span></code></pre></div>
<pre><code>## filhos
##  0  1  2  3  4  5  6 
## 11 27 30 19 11  1  1</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="estatistica-descritiva.html#cb40-1"></a><span class="kw">prop.table</span>(tab)                           <span class="co"># Frequência relativa</span></span></code></pre></div>
<pre><code>## filhos
##    0    1    2    3    4    5    6 
## 0.11 0.27 0.30 0.19 0.11 0.01 0.01</code></pre>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="estatistica-descritiva.html#cb42-1"></a><span class="kw">cumsum</span>(tab)                               <span class="co"># Frequência acumulada</span></span></code></pre></div>
<pre><code>##   0   1   2   3   4   5   6 
##  11  38  68  87  98  99 100</code></pre>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="estatistica-descritiva.html#cb44-1"></a><span class="kw">round</span>(<span class="kw">cumsum</span>(tab)<span class="op">/</span><span class="kw">length</span>(filhos),<span class="dv">2</span>)       <span class="co"># Frequência acumulada relativa</span></span></code></pre></div>
<pre><code>##    0    1    2    3    4    5    6 
## 0.11 0.38 0.68 0.87 0.98 0.99 1.00</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="estatistica-descritiva.html#cb46-1"></a><span class="kw">cumsum</span>(<span class="kw">rev</span>(tab))                          <span class="co"># Frequência acumulada inversa</span></span></code></pre></div>
<pre><code>##   6   5   4   3   2   1   0 
##   1   2  13  32  62  89 100</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="estatistica-descritiva.html#cb48-1"></a><span class="kw">round</span>(<span class="kw">cumsum</span>(<span class="kw">rev</span>(tab))<span class="op">/</span><span class="kw">length</span>(filhos),<span class="dv">2</span>)  <span class="co"># Frequência acumulada inversa relativa</span></span></code></pre></div>
<pre><code>##    6    5    4    3    2    1    0 
## 0.01 0.02 0.13 0.32 0.62 0.89 1.00</code></pre>

<div class="exercise">
<p><span id="exr:ex-tab-fr1" class="exercise"><strong>Exercise 2.4  </strong></span>Em uma fábrica retirou-se uma amostra de 50 peças de um lote de certo material e contou-se o número de defeitos em cada peça, apresentados na tabela a seguir.</p>
<table>
<thead>
<tr class="header">
<th align="center"><span class="math inline">\(i\)</span></th>
<th align="center"># defeitos</th>
<th align="center"><span class="math inline">\(f_i\)</span></th>
<th align="center"><span class="math inline">\(fr_i\)</span></th>
<th align="center"><span class="math inline">\(F_i\)</span></th>
<th align="center"><span class="math inline">\(Fr_i\)</span></th>
<th align="center"><span class="math inline">\(\Finv_{i}\)</span></th>
<th align="center"><span class="math inline">\(\Finv_{r_{i}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">0</td>
<td align="center">17</td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">1</td>
<td align="center">10</td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">2</td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">3</td>
<td align="center">8</td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">4</td>
<td align="center">5</td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
</tr>
<tr class="even">
<td align="center">6</td>
<td align="center">5</td>
<td align="center">1</td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
</tr>
<tr class="odd">
<td align="center">Total</td>
<td align="center">-</td>
<td align="center">50</td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
</tr>
</tbody>
</table>
<ol style="list-style-type: lower-alpha">
<li>Classifique a variável ‘número de defeitos’.<br />
</li>
<li>Qual a frequência absoluta da classe 3? Interprete.<br />
</li>
<li>Qual a frequência relativa da classe 3? Interprete.<br />
</li>
<li>Qual a frequência acumulada da classe 4? Interprete.<br />
</li>
<li>Qual a frequência acumulada relativa da classe 5? Interprete.<br />
</li>
<li>Represente os dados utilizando o gráfico que você considerar mais adequado.<br />
</li>
</ol>
</div>
</div>
<div id="tab-freq-univ-cont" class="section level3" number="2.2.3">
<h3><span class="header-section-number">2.2.3</span> Tabela de frequência univariada contínua</h3>
<p>Quando uma variável assume mais de 10 diferentes valores, recomenda-se utilizar a <em>tabela de frequência univariada contínua</em>. A diferença para a tabela discreta da Seção <a href="estatistica-descritiva.html#tab-freq-univ-discr">2.2.2</a> é que na contínua distribuem-se os valores em <em>intervalos de classe</em>, i.e., faixas de valores com certa amplitude. A principal vantagem desta abordagem é a capacidade de apresentar os dados de maneira enxuta. O contraponto, como em qualquer resumo de dados, é a perda da informação original.</p>
<div id="amplitude-h-e-quantidade-k-de-classes" class="section level4 unnumbered" number="">
<h4>Amplitude (<span class="math inline">\(h\)</span>) e quantidade (<span class="math inline">\(k\)</span>) de classes</h4>
<p>Quando deseja-se apresentar a variável em intervalos de classe, é necessário determinar a <em>amplitude do intervalo de classe</em> (<span class="math inline">\(h\)</span>) e a <em>quantidade de classes</em> (<span class="math inline">\(k\)</span>) em que serão dispostos os dados. Apresentam-se a seguir três das principais regras para determinar <span class="math inline">\(h\)</span> e <span class="math inline">\(k\)</span>.</p>
<div id="sturges" class="section level5 unnumbered" number="">
<h5>1. Sturges</h5>
<p><span class="citation">(Sturges <a href="#ref-sturges1926choice" role="doc-biblioref">1926</a>)</span> sugere que a amplitude do intervalo de classe seja calculada por
<span class="math display" id="eq:h-sturges">\[\begin{equation}
h_{St} = \frac{A}{k_{St}} = \frac{\max{X}-\min{X}}{1 + \log_{2}{n}} \approx \frac{\max{X}-\min{X}}{1 + 3.322 \log_{10}{n}},
\tag{2.1}
\end{equation}\]</span></p>
<p>onde <span class="math inline">\(A\)</span> é a <em>amplitude (dos dados)</em> descrita na Seção <a href="estatistica-descritiva.html#amplitude">2.4.1</a>, não devendo ser confundida com <span class="math inline">\(h\)</span>. O denominador é obtido a partir da <em>expansão binomial</em>, na forma
<span class="math display" id="eq:exp-bin">\[\begin{equation}
n = \sum_{i=0}^{k-1} {k-1 \choose i} = (1+1)^{k-1} = 2^{k-1}.
\tag{2.2}
\end{equation}\]</span></p>
<p>Da Equação <a href="estatistica-descritiva.html#eq:exp-bin">(2.2)</a> pode-se obter</p>
<p><span class="math display" id="eq:k-sturges">\[\begin{equation}
k_{St} = \left\lceil 1 + \log_{2}{n} \right\rceil = \left\lceil 1 + 3.322 \log_{10}{n} \right\rceil,
\tag{2.3}
\end{equation}\]</span></p>
<p>onde <span class="math inline">\(\left\lceil \;\; \right\rceil\)</span> indica a função <em>teto</em>, o menor inteiro consecutivo denotado por <span class="math inline">\(\left\lceil x \right\rceil = min \{ n \in \mathbb{N} | n \ge x \}\)</span>. Alguns pacotes computacionais atribuem o número de classes aplicando regras que encontrem um valor ‘bonito’ para a divisão. Tais valores são obtidos computando números que sejam 0, 1, 2 ou 5 vezes uma potência de 10, i.e., <span class="math inline">\(a \times 10^b\)</span>, <span class="math inline">\(a \in \{0,1,2,5\}\)</span> e <span class="math inline">\(b \in \mathbb{N} \cup \{-1\}\)</span>.</p>

<div class="example">
<span id="exm:sturges" class="example"><strong>Example 2.15  </strong></span>(Sturges) Se forem observados <span class="math inline">\(n=100\)</span> valores com amplitude (dos dados) <span class="math inline">\(A=0.23\)</span>, a amplitude da classe sugerida por Sturges é <span class="math display">\[h_{St} = \frac{0.23}{1 + \log_{2}{100}} = 0.02875,\]</span> e a quantidade de classes <span class="math display">\[k_{St} = \left\lceil 1 + \log_{2}{100} \right\rceil = \left\lceil 7.644 \right\rceil = 8.\]</span>
</div>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="estatistica-descritiva.html#cb50-1"></a>n &lt;-<span class="st"> </span><span class="kw">length</span>(altura)               <span class="co"># n=100, número de dados a serem tabulados</span></span>
<span id="cb50-2"><a href="estatistica-descritiva.html#cb50-2"></a>A &lt;-<span class="st"> </span><span class="kw">diff</span>(<span class="kw">range</span>(altura))          <span class="co"># Amplitude (dos dados, não da classe!)</span></span>
<span id="cb50-3"><a href="estatistica-descritiva.html#cb50-3"></a><span class="kw">ceiling</span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span><span class="kw">log2</span>(n))              <span class="co"># Pela Equação (2.3), usando log2</span></span></code></pre></div>
<pre><code>## [1] 8</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="estatistica-descritiva.html#cb52-1"></a><span class="kw">ceiling</span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span><span class="fl">3.322</span><span class="op">*</span><span class="kw">log10</span>(n))       <span class="co"># Pela Equação (2.3), usando log10</span></span></code></pre></div>
<pre><code>## [1] 8</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="estatistica-descritiva.html#cb54-1"></a>(kSt &lt;-<span class="st"> </span><span class="kw">nclass.Sturges</span>(altura))   <span class="co"># Pela função &#39;nclass.Sturges&#39;</span></span></code></pre></div>
<pre><code>## [1] 8</code></pre>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="estatistica-descritiva.html#cb56-1"></a>(hSt &lt;-<span class="st"> </span>A<span class="op">/</span>kSt)                    <span class="co"># Pela Equação (2.1)</span></span></code></pre></div>
<pre><code>## [1] 0.02875</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="estatistica-descritiva.html#cb58-1"></a><span class="kw">pretty</span>(kSt)                       <span class="co"># Valores &#39;bonitos&#39;, (a=5, b=0) e (a=1, b=1)</span></span></code></pre></div>
<pre><code>## [1]  5 10</code></pre>
</div>
<div id="scott" class="section level5 unnumbered" number="">
<h5>2. Scott</h5>
<p><span class="citation">(Scott <a href="#ref-scott1979optimal" role="doc-biblioref">1979</a>)</span> incorpora <span class="math inline">\(s\)</span>, o desvio padrão amostral ao cálculo da amplitude do intervalo, na forma
<span class="math display" id="eq:h-scott">\[\begin{equation}
h_{Sc} = \dfrac{3.5s}{n^{1/3}}.
\tag{2.4}
\end{equation}\]</span></p>
<p>O número de classes de Scott pode ser obtido por
<span class="math display" id="eq:k-scott">\[\begin{equation}
k_{Sc} = \left\lceil \dfrac{A}{h_{Sc}} \right\rceil = \left\lceil \dfrac{max{X} - min{X}}{3.5sn^{-1/3}} \right\rceil.
\tag{2.5}
\end{equation}\]</span></p>

<div class="example">
<span id="exm:scott" class="example"><strong>Example 2.16  </strong></span>(Scott) Se forem observados <span class="math inline">\(n=100\)</span> valores com desvio padrão amostral <span class="math inline">\(s=0.045268559\)</span>, a amplitude da classe sugerida por Scott é <span class="math display">\[h_{Sc} = \dfrac{3.5 \times 0.045268559}{100^{1/3}} = 0.034134854.\]</span> Se <span class="math inline">\(A=0.23\)</span>, a quantidade de classes é <span class="math display">\[k_{Sc} =\left\lceil \dfrac{0.23}{0.034134854} \right\rceil = \left\lceil 6.7379811 \right\rceil = 7.\]</span>
</div>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="estatistica-descritiva.html#cb60-1"></a>n &lt;-<span class="st"> </span><span class="kw">length</span>(altura)                   <span class="co"># n=100, número de observações a serem tabuladas</span></span>
<span id="cb60-2"><a href="estatistica-descritiva.html#cb60-2"></a>s &lt;-<span class="st"> </span><span class="kw">sd</span>(altura)                       <span class="co"># s=0.045268559, desvio padrão amostral</span></span>
<span id="cb60-3"><a href="estatistica-descritiva.html#cb60-3"></a>A &lt;-<span class="st"> </span><span class="kw">diff</span>(<span class="kw">range</span>(altura))              <span class="co"># Amplitude (dos dados, não da classe!)</span></span>
<span id="cb60-4"><a href="estatistica-descritiva.html#cb60-4"></a>(hSc &lt;-<span class="st"> </span><span class="fl">3.5</span><span class="op">*</span>s<span class="op">/</span>n<span class="op">^</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">3</span>))                <span class="co"># Pela Equação (2.4)</span></span></code></pre></div>
<pre><code>## [1] 0.03413485378</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="estatistica-descritiva.html#cb62-1"></a><span class="kw">ceiling</span>(A<span class="op">/</span>hSc)                        <span class="co"># k sugerido por Scott, Equação (2.5)</span></span></code></pre></div>
<pre><code>## [1] 7</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="estatistica-descritiva.html#cb64-1"></a>(kSc &lt;-<span class="st"> </span><span class="kw">nclass.scott</span>(altura))         <span class="co"># k obtido pela função &#39;nclass.scott&#39;</span></span></code></pre></div>
<pre><code>## [1] 7</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="estatistica-descritiva.html#cb66-1"></a><span class="kw">pretty</span>(kSc)                           <span class="co"># Valores &#39;bonitos&#39;, (a=5, b=0) e (a=1, b=1)</span></span></code></pre></div>
<pre><code>## [1]  5 10</code></pre>
</div>
<div id="freedman-diaconis" class="section level5 unnumbered" number="">
<h5>3. Freedman-Diaconis</h5>
<p><span class="citation">(Freedman and Diaconis <a href="#ref-freedman1981histogram" role="doc-biblioref">1981</a>)</span> inserem a <em>amplitude interquartílica</em> no cálculo da amplitude do intervalo, na forma
<span class="math display" id="eq:h-fd">\[\begin{equation}
h_{FD} = 2 \dfrac{AI}{n^{1/3}},
\tag{2.6}
\end{equation}\]</span></p>
<p>onde <span class="math inline">\(AI = Q_{3} - Q_{1}\)</span> é a amplitude interquartílica. O número de classes obtido como consequência da aplicação da relação de Freedman-Diaconis é
<span class="math display" id="eq:k-fd">\[\begin{equation}
k_{FD} = \left\lceil \dfrac{A}{h_{FD}} \right\rceil = \left\lceil \dfrac{max{X} - min{X}}{2 \, AI \, n^{-1/3}} \right\rceil.
\tag{2.7}
\end{equation}\]</span></p>

<div class="example">
<span id="exm:fd" class="example"><strong>Example 2.17  </strong></span>(Freedman-Diaconis) Se forem observados <span class="math inline">\(n=100\)</span> valores com amplitude interquartílica de <span class="math inline">\(AI=0.0525\)</span>, a amplitude da classe sugerida por Freedman-Diaconis é <span class="math display">\[h_{FD} = \dfrac{2 \times 0.0525}{100^{1/3}} = 0.022621564.\]</span> Se <span class="math inline">\(A=0.23\)</span>, e a quantidade de classes <span class="math display">\[k_{FD} = \left\lceil \dfrac{0.23}{0.022621564} \right\rceil = \left\lceil 10.16729 \right\rceil = 11.\]</span>
</div>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="estatistica-descritiva.html#cb68-1"></a>n &lt;-<span class="st"> </span><span class="kw">length</span>(altura)                   <span class="co"># n=100, número de observações a serem tabuladas</span></span>
<span id="cb68-2"><a href="estatistica-descritiva.html#cb68-2"></a>(Q &lt;-<span class="st"> </span><span class="kw">quantile</span>(altura, <span class="kw">c</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">4</span>,<span class="dv">3</span><span class="op">/</span><span class="dv">4</span>)))   <span class="co"># Primeiro e terceiro quartis</span></span></code></pre></div>
<pre><code>##    25%    75% 
## 1.5975 1.6500</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="estatistica-descritiva.html#cb70-1"></a>(AI &lt;-<span class="st"> </span><span class="kw">diff</span>(<span class="kw">as.numeric</span>(Q)))     <span class="co"># Amplitude Interquatílica</span></span></code></pre></div>
<pre><code>## [1] 0.0525</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="estatistica-descritiva.html#cb72-1"></a>(hFD &lt;-<span class="st"> </span><span class="dv">2</span><span class="op">*</span>AI<span class="op">/</span>n<span class="op">^</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">3</span>))           <span class="co"># Pela Equação (2.6)</span></span></code></pre></div>
<pre><code>## [1] 0.02262156425</code></pre>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="estatistica-descritiva.html#cb74-1"></a>A &lt;-<span class="st"> </span><span class="kw">diff</span>(<span class="kw">range</span>(altura))        <span class="co"># Amplitude (dos dados, não da classe ou interquartílica!)</span></span>
<span id="cb74-2"><a href="estatistica-descritiva.html#cb74-2"></a><span class="kw">ceiling</span>(A<span class="op">/</span>hFD)                  <span class="co"># k sugerido por Freedman-Diaconis, Equação (2.7)</span></span></code></pre></div>
<pre><code>## [1] 11</code></pre>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="estatistica-descritiva.html#cb76-1"></a>(kFD &lt;-<span class="st"> </span><span class="kw">nclass.FD</span>(altura))      <span class="co"># Pela função &#39;nclass.FD&#39;</span></span></code></pre></div>
<pre><code>## [1] 11</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="estatistica-descritiva.html#cb78-1"></a><span class="kw">pretty</span>(kFD)                     <span class="co"># Valores &#39;bonitos&#39;, (a=1, b=1) e (a=2, b=1)</span></span></code></pre></div>
<pre><code>## [1] 10 20</code></pre>
<p><span class="citation">(Hyndman <a href="#ref-hyndman1995problem" role="doc-biblioref">1995</a>)</span> argumenta que as regras de Scott e Freedman-Diaconis são tão simples quanto a regra de Sturges, mas melhor fundamentadas na teoria estatística. Além disso, a regra de Sturges funciona bem para tamanhos de amostra moderados (<span class="math inline">\(n &lt; 200\)</span>), mas não para valores grandes de <span class="math inline">\(n\)</span>.</p>

<div class="example">
<span id="exm:hyndman" class="example"><strong>Example 2.18  </strong></span>(Comparando os três métodos) Foi realizada uma simulação com tamanhos de amostra <span class="math inline">\(n=10^{i}\)</span>, <span class="math inline">\(i \in \{1, 2, \ldots, 6 \}\)</span>, indicando o número de classes sugerido por cada método.
</div>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="estatistica-descritiva.html#cb80-1"></a>NC &lt;-<span class="st"> </span><span class="cf">function</span>(x) <span class="kw">c</span>(<span class="dt">i =</span> i, <span class="dt">n =</span> <span class="dv">10</span><span class="op">^</span>i,                <span class="co"># Quantidades simuladas</span></span>
<span id="cb80-2"><a href="estatistica-descritiva.html#cb80-2"></a>                    <span class="dt">Sturges =</span> <span class="kw">nclass.Sturges</span>(x),     <span class="co"># Sturges (1926)</span></span>
<span id="cb80-3"><a href="estatistica-descritiva.html#cb80-3"></a>                    <span class="dt">Scott =</span> <span class="kw">nclass.scott</span>(x),         <span class="co"># Scott (1979)</span></span>
<span id="cb80-4"><a href="estatistica-descritiva.html#cb80-4"></a>                    <span class="dt">FD =</span> <span class="kw">nclass.FD</span>(x))               <span class="co"># Freedman-Diaconis (1981)</span></span>
<span id="cb80-5"><a href="estatistica-descritiva.html#cb80-5"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">6</span>){<span class="kw">set.seed</span>(i); <span class="kw">print</span>(<span class="kw">NC</span>(<span class="kw">rnorm</span>(<span class="dv">10</span><span class="op">^</span>i)))}  <span class="co"># Pode ser demorado para i&gt;6</span></span></code></pre></div>
<pre><code>##       i       n Sturges   Scott      FD 
##       1      10       5       2       3 
##       i       n Sturges   Scott      FD 
##       2     100       8       6       7 
##       i       n Sturges   Scott      FD 
##       3    1000      11      19      25 
##       i       n Sturges   Scott      FD 
##       4   10000      15      44      56 
##       i       n Sturges   Scott      FD 
##       5  100000      18     112     145 
##       i       n Sturges   Scott      FD 
##       6 1000000      21     278     360</code></pre>

<div class="example">
<p><span id="exm:altura-mulheres" class="example"><strong>Example 2.19  </strong></span>(Alturas de mulheres) Seja a variável</p>
<blockquote>
<p><span class="math inline">\(Y\)</span>: ‘altura de mulheres atendidas em um hospital de Porto Alegre em 2019’.</p>
</blockquote>
<p>A Tabela abaixo apresenta os dados brutos. Este tipo de apresentação é bastante completo, mas dificulta a extração de informações relevantes. Como exercício, indique quantas mulheres têm altura entre 1.70m e 1.75m a partir desta tabela.</p>
<table>
<thead>
<tr class="header">
<th align="center"><span class="math inline">\(i\)</span></th>
<th align="center"><span class="math inline">\(y_{i}\)</span></th>
<th align="center"><span class="math inline">\(i\)</span></th>
<th align="center"><span class="math inline">\(y_{i}\)</span></th>
<th align="center"><span class="math inline">\(i\)</span></th>
<th align="center"><span class="math inline">\(y_{i}\)</span></th>
<th align="center"><span class="math inline">\(i\)</span></th>
<th align="center"><span class="math inline">\(y_{i}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">1.59</td>
<td align="center">26</td>
<td align="center">1.61</td>
<td align="center">51</td>
<td align="center">1.64</td>
<td align="center">76</td>
<td align="center">1.62</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">1.58</td>
<td align="center">27</td>
<td align="center">1.61</td>
<td align="center">52</td>
<td align="center">1.57</td>
<td align="center">77</td>
<td align="center">1.54</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">1.70</td>
<td align="center">28</td>
<td align="center">1.60</td>
<td align="center">53</td>
<td align="center">1.65</td>
<td align="center">78</td>
<td align="center">1.64</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">1.62</td>
<td align="center">29</td>
<td align="center">1.61</td>
<td align="center">54</td>
<td align="center">1.69</td>
<td align="center">79</td>
<td align="center">1.66</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">1.67</td>
<td align="center">30</td>
<td align="center">1.64</td>
<td align="center">55</td>
<td align="center">1.65</td>
<td align="center">80</td>
<td align="center">1.56</td>
</tr>
<tr class="even">
<td align="center">6</td>
<td align="center">1.62</td>
<td align="center">31</td>
<td align="center">1.59</td>
<td align="center">56</td>
<td align="center">1.62</td>
<td align="center">81</td>
<td align="center">1.64</td>
</tr>
<tr class="odd">
<td align="center">7</td>
<td align="center">1.69</td>
<td align="center">32</td>
<td align="center">1.60</td>
<td align="center">57</td>
<td align="center">1.68</td>
<td align="center">82</td>
<td align="center">1.60</td>
</tr>
<tr class="even">
<td align="center">8</td>
<td align="center">1.60</td>
<td align="center">33</td>
<td align="center">1.62</td>
<td align="center">58</td>
<td align="center">1.60</td>
<td align="center">83</td>
<td align="center">1.68</td>
</tr>
<tr class="odd">
<td align="center">9</td>
<td align="center">1.61</td>
<td align="center">34</td>
<td align="center">1.53</td>
<td align="center">59</td>
<td align="center">1.68</td>
<td align="center">84</td>
<td align="center">1.65</td>
</tr>
<tr class="even">
<td align="center">10</td>
<td align="center">1.58</td>
<td align="center">35</td>
<td align="center">1.58</td>
<td align="center">60</td>
<td align="center">1.59</td>
<td align="center">85</td>
<td align="center">1.65</td>
</tr>
<tr class="odd">
<td align="center">11</td>
<td align="center">1.64</td>
<td align="center">36</td>
<td align="center">1.60</td>
<td align="center">61</td>
<td align="center">1.70</td>
<td align="center">86</td>
<td align="center">1.64</td>
</tr>
<tr class="even">
<td align="center">12</td>
<td align="center">1.72</td>
<td align="center">37</td>
<td align="center">1.61</td>
<td align="center">62</td>
<td align="center">1.65</td>
<td align="center">87</td>
<td align="center">1.55</td>
</tr>
<tr class="odd">
<td align="center">13</td>
<td align="center">1.74</td>
<td align="center">38</td>
<td align="center">1.67</td>
<td align="center">63</td>
<td align="center">1.51</td>
<td align="center">88</td>
<td align="center">1.66</td>
</tr>
<tr class="even">
<td align="center">14</td>
<td align="center">1.63</td>
<td align="center">39</td>
<td align="center">1.68</td>
<td align="center">64</td>
<td align="center">1.66</td>
<td align="center">89</td>
<td align="center">1.59</td>
</tr>
<tr class="odd">
<td align="center">15</td>
<td align="center">1.64</td>
<td align="center">40</td>
<td align="center">1.56</td>
<td align="center">65</td>
<td align="center">1.52</td>
<td align="center">90</td>
<td align="center">1.66</td>
</tr>
<tr class="even">
<td align="center">16</td>
<td align="center">1.63</td>
<td align="center">41</td>
<td align="center">1.58</td>
<td align="center">66</td>
<td align="center">1.60</td>
<td align="center">91</td>
<td align="center">1.69</td>
</tr>
<tr class="odd">
<td align="center">17</td>
<td align="center">1.59</td>
<td align="center">42</td>
<td align="center">1.66</td>
<td align="center">67</td>
<td align="center">1.62</td>
<td align="center">92</td>
<td align="center">1.61</td>
</tr>
<tr class="even">
<td align="center">18</td>
<td align="center">1.64</td>
<td align="center">43</td>
<td align="center">1.59</td>
<td align="center">68</td>
<td align="center">1.68</td>
<td align="center">93</td>
<td align="center">1.58</td>
</tr>
<tr class="odd">
<td align="center">19</td>
<td align="center">1.59</td>
<td align="center">44</td>
<td align="center">1.67</td>
<td align="center">69</td>
<td align="center">1.65</td>
<td align="center">94</td>
<td align="center">1.73</td>
</tr>
<tr class="even">
<td align="center">20</td>
<td align="center">1.65</td>
<td align="center">45</td>
<td align="center">1.62</td>
<td align="center">70</td>
<td align="center">1.61</td>
<td align="center">95</td>
<td align="center">1.56</td>
</tr>
<tr class="odd">
<td align="center">21</td>
<td align="center">1.63</td>
<td align="center">46</td>
<td align="center">1.55</td>
<td align="center">71</td>
<td align="center">1.56</td>
<td align="center">96</td>
<td align="center">1.59</td>
</tr>
<tr class="even">
<td align="center">22</td>
<td align="center">1.64</td>
<td align="center">47</td>
<td align="center">1.64</td>
<td align="center">72</td>
<td align="center">1.65</td>
<td align="center">97</td>
<td align="center">1.65</td>
</tr>
<tr class="odd">
<td align="center">23</td>
<td align="center">1.64</td>
<td align="center">48</td>
<td align="center">1.62</td>
<td align="center">73</td>
<td align="center">1.62</td>
<td align="center">98</td>
<td align="center">1.63</td>
</tr>
<tr class="even">
<td align="center">24</td>
<td align="center">1.62</td>
<td align="center">49</td>
<td align="center">1.65</td>
<td align="center">74</td>
<td align="center">1.63</td>
<td align="center">99</td>
<td align="center">1.70</td>
</tr>
<tr class="odd">
<td align="center">25</td>
<td align="center">1.66</td>
<td align="center">50</td>
<td align="center">1.66</td>
<td align="center">75</td>
<td align="center">1.57</td>
<td align="center">100</td>
<td align="center">1.60</td>
</tr>
</tbody>
</table>
<p>Para colocar estes valores em uma tabela de frequência, obteve-se <span class="math inline">\(k_{St}=8\)</span> pela regra de Sturges, e pelo resultado de <code>pretty(8)</code> decidiu-se por 5 classes. Como exercício, obtenha <span class="math inline">\(k_{Sc}\)</span> e <span class="math inline">\(k_{FD}\)</span>.</p>
<p>A Tabela abaixo apresenta as alturas agrupadas em cinco classes de amplitude 5cm, fornecendo ainda algumas frequências que auxiliam o entendimento da distribuição. Facilmente observam-se 6 mulheres com altura entre 1.70m e 1.75m,<a href="#fn13" class="footnote-ref" id="fnref13"><sup>13</sup></a> ao contrário da tabela de dados brutos. Note, porém, que não é possível saber exatamente a altura de cada uma destas 6 mulheres. Isso acontece pois resumo implica em perda de informação, cabendo ao pesquisador decidir quando e como resumir os dados.</p>
<table>
<thead>
<tr class="header">
<th align="center"><span class="math inline">\(i\)</span></th>
<th align="center"><span class="math inline">\(y_{i}\)</span></th>
<th align="center"><span class="math inline">\(f_{i}\)</span></th>
<th align="center"><span class="math inline">\(f_{r_{i}}\)</span></th>
<th align="center"><span class="math inline">\(F_{i}\)</span></th>
<th align="center"><span class="math inline">\(F_{r_{i}}\)</span></th>
<th align="center"><span class="math inline">\(\Finv_{i}\)</span></th>
<th align="center"><span class="math inline">\(\Finv_{r_{i}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">1.50 <span class="math inline">\(\vdash\)</span> 1.55</td>
<td align="center">4</td>
<td align="center">0.04</td>
<td align="center">4</td>
<td align="center">0.04</td>
<td align="center"><span class="math inline">\(96+4=100\)</span></td>
<td align="center"><span class="math inline">\(100/100=1\)</span></td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">1.55 <span class="math inline">\(\vdash\)</span> 1.60</td>
<td align="center">21</td>
<td align="center">0.21</td>
<td align="center"><span class="math inline">\(4+21=25\)</span></td>
<td align="center">0.25</td>
<td align="center"><span class="math inline">\(75+21=96\)</span></td>
<td align="center"><span class="math inline">\(96/100=0.96\)</span></td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">1.60 <span class="math inline">\(\vdash\)</span> 1.65</td>
<td align="center">41</td>
<td align="center">0.41</td>
<td align="center"><span class="math inline">\(25+41=66\)</span></td>
<td align="center">0.66</td>
<td align="center"><span class="math inline">\(34+41=75\)</span></td>
<td align="center"><span class="math inline">\(75/100=0.75\)</span></td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">1.65 <span class="math inline">\(\vdash\)</span> 1.70</td>
<td align="center">28</td>
<td align="center">0.28</td>
<td align="center"><span class="math inline">\(66+28=94\)</span></td>
<td align="center">0.94</td>
<td align="center"><span class="math inline">\(6+28=34\)</span></td>
<td align="center"><span class="math inline">\(34/100=0.34\)</span></td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">1.70 <span class="math inline">\(\vdash\)</span> 1.75</td>
<td align="center">6</td>
<td align="center">0.06</td>
<td align="center"><span class="math inline">\(94+6=100\)</span></td>
<td align="center">1</td>
<td align="center">6</td>
<td align="center"><span class="math inline">\(6/100=0.06\)</span></td>
</tr>
<tr class="even">
<td align="center">Total</td>
<td align="center">-</td>
<td align="center">100</td>
<td align="center">1</td>
<td align="center">-</td>
<td align="center">-</td>
<td align="center">-</td>
<td align="center">-</td>
</tr>
</tbody>
</table>
A seguir estão alguns exemplos de interpretação das frequências apresentadas na Tabela acima.<br />
- <span class="math inline">\(f_{5}=6\)</span>, i.e., 6 mulheres têm entre 1.70m e 1.75m de altura<br />
- <span class="math inline">\(f_{r_{5}}=0.06=6\%\)</span>, i.e., 6% das mulheres tem entre 1.70m e 1.75m de altura<br />
- <span class="math inline">\(F_{4}=94\)</span>, i.e., 94 mulheres têm até 1.70m de altura, ou de 1.50m a 1.70m<br />
- <span class="math inline">\(F_{r_{2}}=0.25=25\%\)</span>, i.e., 25% das mulheres tem até 1.60m de altura, ou de 1.50m a 1.60m<br />
- <span class="math inline">\(\Finv_{3}=75\)</span>, i.e., 75 mulheres têm pelo menos 1.60m de altura<br />
- <span class="math inline">\(\Finv_{r_{4}}=0.34=34\%\)</span>, i.e., 34% das mulheres tem pelo menos 1.65m de altura <span class="math inline">\(\\\)</span>
</div>

<div class="example">
<span id="exm:altura-mulheres-r" class="example"><strong>Example 2.20  </strong></span>(Alturas de mulheres R-visitado) Exemplo <a href="estatistica-descritiva.html#exm:altura-mulheres">2.19</a> utilizando R/RStudio.
</div>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="estatistica-descritiva.html#cb82-1"></a>hosp &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&#39;http://www.filipezabala.com/data/hospital.txt&#39;</span>, <span class="dt">head =</span> T)</span>
<span id="cb82-2"><a href="estatistica-descritiva.html#cb82-2"></a><span class="kw">dim</span>(hosp)       <span class="co"># Dimensão: 100 linhas por 2 colunas</span></span></code></pre></div>
<pre><code>## [1] 100   2</code></pre>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="estatistica-descritiva.html#cb84-1"></a><span class="kw">head</span>(hosp)      <span class="co"># Apresenta as 6 primeiras linhas do objeto &#39;hosp&#39;; teste tail(hosp, 10)</span></span></code></pre></div>
<pre><code>##   filhos altura
## 1      2   1.59
## 2      0   1.58
## 3      1   1.70
## 4      2   1.62
## 5      4   1.67
## 6      2   1.62</code></pre>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="estatistica-descritiva.html#cb86-1"></a><span class="kw">attach</span>(hosp, <span class="dt">warn=</span>F)                  <span class="co"># Para deixar as colunas de &#39;hosp&#39; disponíveis</span></span>
<span id="cb86-2"><a href="estatistica-descritiva.html#cb86-2"></a><span class="kw">pretty</span>(<span class="kw">nclass.Sturges</span>(altura))        <span class="co"># Valores &#39;bonitos&#39; para o número de classes</span></span></code></pre></div>
<pre><code>## [1]  5 10</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="estatistica-descritiva.html#cb88-1"></a><span class="kw">hist</span>(altura)<span class="op">$</span>breaks                   <span class="co"># Quebras de valores gerados com a função &#39;hist&#39;</span></span></code></pre></div>
<pre><code>## [1] 1.50 1.55 1.60 1.65 1.70 1.75</code></pre>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="estatistica-descritiva.html#cb90-1"></a>(f &lt;-<span class="st"> </span><span class="kw">hist</span>(altura)<span class="op">$</span>counts)                <span class="co"># Frequências das classes</span></span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<pre><code>## [1]  6 27 43 21  3</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="estatistica-descritiva.html#cb92-1"></a><span class="kw">cumsum</span>(f)                                 <span class="co"># Frequência acumulada</span></span></code></pre></div>
<pre><code>## [1]   6  33  76  97 100</code></pre>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="estatistica-descritiva.html#cb94-1"></a><span class="kw">round</span>(<span class="kw">cumsum</span>(f)<span class="op">/</span><span class="kw">length</span>(altura),<span class="dv">2</span>)         <span class="co"># Frequência acumulada relativa</span></span></code></pre></div>
<pre><code>## [1] 0.06 0.33 0.76 0.97 1.00</code></pre>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="estatistica-descritiva.html#cb96-1"></a><span class="kw">cumsum</span>(<span class="kw">rev</span>(f))                            <span class="co"># Frequência acumulada inversa</span></span></code></pre></div>
<pre><code>## [1]   3  24  67  94 100</code></pre>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="estatistica-descritiva.html#cb98-1"></a><span class="kw">round</span>(<span class="kw">cumsum</span>(<span class="kw">rev</span>(f))<span class="op">/</span><span class="kw">length</span>(altura),<span class="dv">2</span>)    <span class="co"># Frequência acumulada inversa relativa</span></span></code></pre></div>
<pre><code>## [1] 0.03 0.24 0.67 0.94 1.00</code></pre>
</div>
</div>
</div>
</div>
<div id="posicao" class="section level2" number="2.3">
<h2><span class="header-section-number">2.3</span> Medidas de Posição (ou Localização)</h2>
<div id="minmax" class="section level3" number="2.3.1">
<h3><span class="header-section-number">2.3.1</span> Mínimo e Máximo</h3>
<p>O <em>mínimo</em> de uma distribuição é o menor valor observado desta distribuição; de forma análoga, o <em>máximo</em> é o maior valor. São estatísticas de ordem, mais especificamente os extremos de um conjunto de dados ordenado (rol). Para uma distribuição de <span class="math inline">\(n\)</span> elementos são denotadas por <span class="math inline">\(\min X = x_{(1)}\)</span> e <span class="math inline">\(\max X = x_{(n)}\)</span>.</p>
<p>Apesar da simplicidade destas medidas, existem considerações teóricas sofisticadas a seu respeito. Para maiores detalhes, vide <span class="citation">(Kotz and Nadarajah <a href="#ref-kotz2000extreme" role="doc-biblioref">2000</a>)</span>.</p>

<div class="example">
<span id="exm:minmax" class="example"><strong>Example 2.21  </strong></span>(Mínimo e máximo) Suponha novamente as <span class="math inline">\(n=100\)</span> observações da variável Y: ‘altura de mulheres atendidas em um certo hospital público de Porto Alegre em 2019’, apresentadas no Exemplo <a href="estatistica-descritiva.html#exm:altura-mulheres">2.19</a>. O mínimo e o máximo são denotados, respectivamente, por <span class="math inline">\(\min Y = y_{(1)} = 1.51\)</span> e <span class="math inline">\(\max Y = y_{(100)} = 1.74\)</span>. <span class="math inline">\(\\\)</span>
</div>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="estatistica-descritiva.html#cb100-1"></a><span class="kw">attach</span>(<span class="kw">read.table</span>(<span class="st">&#39;http://www.filipezabala.com/data/hospital.txt&#39;</span>, <span class="dt">head=</span>T), <span class="dt">warn=</span>F)</span>
<span id="cb100-2"><a href="estatistica-descritiva.html#cb100-2"></a><span class="kw">min</span>(altura)     <span class="co"># Mínimo</span></span></code></pre></div>
<pre><code>## [1] 1.51</code></pre>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="estatistica-descritiva.html#cb102-1"></a><span class="kw">max</span>(altura)     <span class="co"># Máximo</span></span></code></pre></div>
<pre><code>## [1] 1.74</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="estatistica-descritiva.html#cb104-1"></a><span class="kw">range</span>(altura)   <span class="co"># A função &#39;range&#39; fornece o mínimo e o máximo</span></span></code></pre></div>
<pre><code>## [1] 1.51 1.74</code></pre>
</div>
<div id="mas" class="section level3" number="2.3.2">
<h3><span class="header-section-number">2.3.2</span> Média (Aritmética Simples)</h3>
<p>A <em>média (aritmética simples)</em> ou <em>valor esperado</em> é uma das medidas mais importantes da Estatística devido às suas propriedades e relativa facilidade de cálculo. A média da variável <span class="math inline">\(X\)</span> é simbolizada genericamente por <span class="math inline">\(\mu\)</span> quando refere-se à média universal, e por <span class="math inline">\(\bar{x}_{n}\)</span> quando refere-se à média amostral. Pode-se utilizar a notação <span class="math inline">\(\bar{x}_{n}\)</span> para indicar o tamanho da amostra. Suas expressões no universo a na amostra são dadas respectivamente pelas equações <a href="estatistica-descritiva.html#eq:media-pop">(2.8)</a> e <a href="estatistica-descritiva.html#eq:media-am">(2.9)</a>. Por distribuir a soma dos valores da distribuição pelo número de observações, a média é uma medida que indica centro de massa.
<span class="math display" id="eq:media-pop">\[\begin{equation}
\mu = \frac {\sum_{i=1}^N x_i}{N}
\tag{2.8}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:media-am">\[\begin{equation}
\bar{x}_{n} = \frac {\sum_{i=1}^n x_i}{n}
\tag{2.9}
\end{equation}\]</span></p>

<div class="example">
<span id="exm:media-a-s" class="example"><strong>Example 2.22  </strong></span>(Média aritmética simples) Suponha novamente os dados do Exemplo <a href="introducao.html#exm:somatorio">1.2</a>. O número médio de passos até a lixeira mais próxima foi de <span class="math display">\[\bar{x}_6 = \frac {\sum_{i=1}^6 x_i}{6} = \frac {186+402+191+20+7+124}{6} = \frac{930}{6} = 155.\]</span>
</div>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="estatistica-descritiva.html#cb106-1"></a>x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">186</span>,<span class="dv">402</span>,<span class="dv">191</span>,<span class="dv">20</span>,<span class="dv">7</span>,<span class="dv">124</span>)      <span class="co"># Vetor de dados brutos</span></span>
<span id="cb106-2"><a href="estatistica-descritiva.html#cb106-2"></a><span class="kw">mean</span>(x)                           <span class="co"># Aplica as Equações (2.8) e (2.9). Veja ?mean</span></span></code></pre></div>
<pre><code>## [1] 155</code></pre>
</div>
<div id="total" class="section level3" number="2.3.3">
<h3><span class="header-section-number">2.3.3</span> Total</h3>
<p><em>Total</em> é a soma de todos os valores de uma variável. É expresso pelas equações <a href="estatistica-descritiva.html#eq:total-pop">(2.10)</a> e <a href="estatistica-descritiva.html#eq:total-am">(2.11)</a>.</p>
<p><span class="math display" id="eq:total-pop">\[\begin{equation}
\tau = \sum_{i=1}^N x_i
\tag{2.10}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:total-am">\[\begin{equation}
\hat{\tau} = \dfrac{N}{n} \sum_{i=1}^n x_i = N \bar{x}_{n},
\tag{2.11}
\end{equation}\]</span></p>
<p>onde <span class="math inline">\(\bar{x}_{n}\)</span> é a <em>média amostral</em>, apresentada na Equação <a href="estatistica-descritiva.html#eq:media-am">(2.9)</a>.</p>

<div class="example">
<span id="exm:total" class="example"><strong>Example 2.23  </strong></span>(Total) Suponha novamente os dados do Exemplo @ref{exm:media-a-s}. Se alguém precisar de uma lixeira 20 vezes na capital gaúcha, estima-se que o número total de passos a serem caminhados é de <span class="math display">\[\hat{\tau} = \dfrac{20}{6} \times 930 = 20 \times 155 = 3100.\]</span>
</div>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="estatistica-descritiva.html#cb108-1"></a>N &lt;-<span class="st"> </span><span class="dv">20</span>                         <span class="co"># Tamanho do universo</span></span>
<span id="cb108-2"><a href="estatistica-descritiva.html#cb108-2"></a>x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">186</span>,<span class="dv">402</span>,<span class="dv">191</span>,<span class="dv">20</span>,<span class="dv">7</span>,<span class="dv">124</span>)    <span class="co"># Vetor de dados brutos</span></span>
<span id="cb108-3"><a href="estatistica-descritiva.html#cb108-3"></a>N<span class="op">*</span><span class="kw">mean</span>(x)                       <span class="co"># Equação (2.11)</span></span></code></pre></div>
<pre><code>## [1] 3100</code></pre>
</div>
<div id="mquadr" class="section level3" number="2.3.4">
<h3><span class="header-section-number">2.3.4</span> Média Quadrática</h3>
<p>A <em>média quadrática</em> é a média dos valores ao quadrado, utilizada no cálculo das variâncias. É expressa por<br />
<span class="math display" id="eq:media-quad">\[\begin{equation}
Q^2 = \frac{\sum_{i=1}^n x_{i}^{2}}{n}.
\tag{2.12}
\end{equation}\]</span></p>
<p>O <em>valor quadrático médio</em> é a raiz quadrada da média quadrática, denotado por
<span class="math display" id="eq:vqm">\[\begin{equation}
Q=\sqrt{Q^2}.
\tag{2.13}
\end{equation}\]</span></p>

<div class="example">
<span id="exm:mq" class="example"><strong>Example 2.24  </strong></span>(Média quadrática e valor quadrático médio) A média quadrática dos valores 186, 402, 191, 20, 7 e 124 é <span class="math display">\[Q^2 = \frac {\sum_{i=1}^6 x_{i}^{2}}{6} = \frac {186^2+402^2+191^2+20^2+7^2+124^2}{6} = \frac{248506}{6} = 41417.\bar{6}.\]</span> O valor quadrático médio destes valores é <span class="math display">\[Q = \sqrt{41417.\bar{6}} \approx 203.5133.\]</span>
</div>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="estatistica-descritiva.html#cb110-1"></a>x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">186</span>,<span class="dv">402</span>,<span class="dv">191</span>,<span class="dv">20</span>,<span class="dv">7</span>,<span class="dv">124</span>)    <span class="co"># Vetor de dados brutos</span></span>
<span id="cb110-2"><a href="estatistica-descritiva.html#cb110-2"></a>(mq &lt;-<span class="st"> </span><span class="kw">mean</span>(x<span class="op">^</span><span class="dv">2</span>))               <span class="co"># Eq. (2.12), compare com mean(x)^2</span></span></code></pre></div>
<pre><code>## [1] 41417.66667</code></pre>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="estatistica-descritiva.html#cb112-1"></a><span class="kw">sqrt</span>(mq)                        <span class="co"># Eq. (2.13), valor quadrático médio</span></span></code></pre></div>
<pre><code>## [1] 203.5133083</code></pre>
</div>
<div id="moda" class="section level3" number="2.3.5">
<h3><span class="header-section-number">2.3.5</span> Moda</h3>
<p>A(s) <em>moda(s)</em> é (são) o(s) valor(es) mais frequente(s) de uma distribuição. Quando existe apenas uma moda, a distribuição é conhecida como <em>unimodal</em>. Se existirem duas modas, a distribuição é <em>bimodal</em>. Três modas configuram uma distribuição <em>trimodal</em>, e quatro ou mais modas indicam uma distribuição <em>multimodal</em>. Distribuições com frequências equivalentes para todos os valores são ditas <em>amodais</em>. Quando os dados estão agrupados deve-se indicar a <em>classe modal</em>, i.e., a classe de maior frequência. O esforço computacional para calcular a moda é realizar uma contagem.<br />
No R existe a função <code>Mode</code> do pacote <code>pracma</code>, mas ela só funciona bem no caso unimodal. Por isso a seguir está apresentada a função <code>Modes</code>, adaptada da sugestão de <a href="https://stackoverflow.com/users/316644/digemall">digEmAll</a> <a href="https://stackoverflow.com/questions/2547402/how-to-find-the-statistical-mode">nesta discussão do StackOverflow</a>. Nos exemplos a seguir são comparadas as duas abordagens.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="estatistica-descritiva.html#cb114-1"></a><span class="co"># Função Modes</span></span>
<span id="cb114-2"><a href="estatistica-descritiva.html#cb114-2"></a>Modes &lt;-<span class="st"> </span><span class="cf">function</span>(x) {</span>
<span id="cb114-3"><a href="estatistica-descritiva.html#cb114-3"></a>  ux &lt;-<span class="st"> </span><span class="kw">sort</span>(<span class="kw">unique</span>(x))</span>
<span id="cb114-4"><a href="estatistica-descritiva.html#cb114-4"></a>  tab &lt;-<span class="st"> </span><span class="kw">tabulate</span>(<span class="kw">match</span>(x, ux))</span>
<span id="cb114-5"><a href="estatistica-descritiva.html#cb114-5"></a>  ux[tab <span class="op">==</span><span class="st"> </span><span class="kw">max</span>(tab)]</span>
<span id="cb114-6"><a href="estatistica-descritiva.html#cb114-6"></a>}</span></code></pre></div>

<div class="example">
<span id="exm:moda1" class="example"><strong>Example 2.25  </strong></span>(Unimodal) A moda do conjunto de dados 4, 7, 1, 3, 3, 9 é <span class="math inline">\(Mo=3\)</span>, pois ele apresenta frequência 2 enquanto os demais valores têm frequência 1. Esta é uma distribuição unimodal.
</div>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="estatistica-descritiva.html#cb115-1"></a>dat &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">9</span>)</span>
<span id="cb115-2"><a href="estatistica-descritiva.html#cb115-2"></a><span class="kw">Modes</span>(dat)</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="estatistica-descritiva.html#cb117-1"></a>pracma<span class="op">::</span><span class="kw">Mode</span>(dat)</span></code></pre></div>
<pre><code>## [1] 3</code></pre>

<div class="example">
<span id="exm:moda2" class="example"><strong>Example 2.26  </strong></span>(Bimodal) As modas do conjunto de dados 4, 7, 1, 3, 3, 9, 7 são <span class="math inline">\(Mo&#39;=3\)</span> e <span class="math inline">\(Mo&#39;&#39;=7\)</span>, pois ambos têm frequência 2 enquanto os demais valores têm frequência 1. A ordem de apresentação é indiferente. Esta é uma distribuição bimodal.
</div>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="estatistica-descritiva.html#cb119-1"></a>dat &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">9</span>,<span class="dv">7</span>)</span>
<span id="cb119-2"><a href="estatistica-descritiva.html#cb119-2"></a><span class="kw">Modes</span>(dat)</span></code></pre></div>
<pre><code>## [1] 3 7</code></pre>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="estatistica-descritiva.html#cb121-1"></a>pracma<span class="op">::</span><span class="kw">Mode</span>(dat)</span></code></pre></div>
<pre><code>## [1] 3</code></pre>

<div class="example">
<span id="exm:moda3" class="example"><strong>Example 2.27  </strong></span>(Amodal) O conjunto de dados 4, 7, 1, 3, 9 é dito <em>amodal</em> pois todos os valores têm frequência 1.
</div>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="estatistica-descritiva.html#cb123-1"></a>dat &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">9</span>)</span>
<span id="cb123-2"><a href="estatistica-descritiva.html#cb123-2"></a><span class="kw">Modes</span>(dat)    <span class="co"># se todos são moda, ninguém é moda</span></span></code></pre></div>
<pre><code>## [1] 1 3 4 7 9</code></pre>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="estatistica-descritiva.html#cb125-1"></a>pracma<span class="op">::</span><span class="kw">Mode</span>(dat)</span></code></pre></div>
<pre><code>## [1] 1</code></pre>

<div class="example">
<span id="exm:moda4" class="example"><strong>Example 2.28  </strong></span>(Moda para dados agrupados) No Exemplo <a href="estatistica-descritiva.html#exm:altura-mulheres">2.19</a> observa-se que <span class="math inline">\(f_{3}=41\)</span> é a maior frequência. A classe modal é portanto a terceira, compreendida entre os valores 1.60 e 1.65.
</div>
</div>
<div id="separatrizes" class="section level3" number="2.3.6">
<h3><span class="header-section-number">2.3.6</span> Separatrizes</h3>
<p>Separatrizes ou quantis<a href="#fn14" class="footnote-ref" id="fnref14"><sup>14</sup></a> são medidas que dividem um conjunto de dados ordenados em <span class="math inline">\(k\)</span> partes iguais. O método básico consiste em obter um rol dos dados e encontrar (ainda que de forma aproximada) os valores que repartem a distribuição de acordo com o <span class="math inline">\(k\)</span> desejado. O esforço computacional para calcular quaisquer separatrizes é, portanto, o de realizar a ordenação dos dados.</p>
<div id="mediana-k2" class="section level4 unnumbered" number="">
<h4>Mediana (<span class="math inline">\(k=2\)</span>)</h4>
<p>A <em>mediana</em> é a medida que divide metade dos dados ordenados (rol) à sua esquerda e a outra metade à sua direita, i.e., é a medida central em termos de ordenação. Sua posição é a média entre a primeira e última posições, dada por
<span class="math display" id="eq:pos-mediana">\[\begin{equation}
Pos = \frac{1+n}{2}
\tag{2.14}
\end{equation}\]</span></p>

<div class="example">
<span id="exm:mediana-n-impar" class="example"><strong>Example 2.29  </strong></span>(Mediana para <span class="math inline">\(n\)</span> ímpar) Seja o conjunto de dados 10, -4, 11, 12, 1, 5, 15, formado por <span class="math inline">\(n=7\)</span> valores. Quando ordenado obtemos o rol -4, 1, 5, 10, 11, 12, 15. Considerando <span class="math inline">\(k=2\)</span>, obtém-se a separatriz <span class="math inline">\(Md=10\)</span>, pois ela divide o conjunto em duas partes de mesmo tamanho (três valores abaixo da mediana 10 e três valores acima). Sua posição é dada por <span class="math inline">\(Pos=\frac{1+7}{2}=4\)</span>.
</div>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="estatistica-descritiva.html#cb127-1"></a>x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">10</span>, <span class="dv">-4</span>, <span class="dv">11</span>, <span class="dv">12</span>, <span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">15</span>)</span>
<span id="cb127-2"><a href="estatistica-descritiva.html#cb127-2"></a>(n &lt;-<span class="st"> </span><span class="kw">length</span>(x))</span></code></pre></div>
<pre><code>## [1] 7</code></pre>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="estatistica-descritiva.html#cb129-1"></a>(pos &lt;-<span class="st"> </span>(n<span class="op">+</span><span class="dv">1</span>)<span class="op">/</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 4</code></pre>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="estatistica-descritiva.html#cb131-1"></a><span class="kw">sort</span>(x)</span></code></pre></div>
<pre><code>## [1] -4  1  5 10 11 12 15</code></pre>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="estatistica-descritiva.html#cb133-1"></a><span class="kw">median</span>(x)</span></code></pre></div>
<pre><code>## [1] 10</code></pre>
<p>Quando o número de observações é par, basta tomar a média dos dois valores centrais do rol.</p>

<div class="example">
<span id="exm:mediana-n-par" class="example"><strong>Example 2.30  </strong></span>(Mediana para <span class="math inline">\(n\)</span> par) Seja o conjunto de dados 15, -4, 11, 12, 1, 5, formado por <span class="math inline">\(n=6\)</span> valores. Quando ordenado obtemos o rol -4, 1, 5, 11, 12, 15. Considerando novamente <span class="math inline">\(k=2\)</span>, obtém-se a separatriz <span class="math inline">\(Md=\frac{5+11}{2}=8\)</span>, pois ela divide o conjunto em duas partes de mesmo tamanho (três valores abaixo de 8 e três valores acima). Sua posição é dada por <span class="math inline">\(Pos=\frac{1+6}{2}=3.5\)</span>, i.e., a mediana é um valor intermediário entre a terceira e quarta posições.
</div>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="estatistica-descritiva.html#cb135-1"></a>x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">15</span>, <span class="dv">-4</span>, <span class="dv">11</span>, <span class="dv">12</span>, <span class="dv">1</span>, <span class="dv">5</span>)</span>
<span id="cb135-2"><a href="estatistica-descritiva.html#cb135-2"></a>(n &lt;-<span class="st"> </span><span class="kw">length</span>(x))</span></code></pre></div>
<pre><code>## [1] 6</code></pre>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="estatistica-descritiva.html#cb137-1"></a>(pos &lt;-<span class="st"> </span>(n<span class="op">+</span><span class="dv">1</span>)<span class="op">/</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 3.5</code></pre>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="estatistica-descritiva.html#cb139-1"></a><span class="kw">sort</span>(x)</span></code></pre></div>
<pre><code>## [1] -4  1  5 11 12 15</code></pre>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="estatistica-descritiva.html#cb141-1"></a><span class="kw">median</span>(x)</span></code></pre></div>
<pre><code>## [1] 8</code></pre>
</div>
<div id="separatrizes-1" class="section level4 unnumbered" number="">
<h4>Separatrizes</h4>
<p>Pode-se dividir um conjunto de dados em <span class="math inline">\(k\)</span> setores, sendo os principais apresentados na tabela a seguir</p>
<table>
<thead>
<tr class="header">
<th align="center"><span class="math inline">\(k\)</span></th>
<th align="center">Nome</th>
<th align="center">Simbologia</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">2</td>
<td align="center">Mediana</td>
<td align="center">Md</td>
</tr>
<tr class="even">
<td align="center">3</td>
<td align="center">Tercil</td>
<td align="center"><span class="math inline">\(T_1\)</span>, <span class="math inline">\(T_2\)</span></td>
</tr>
<tr class="odd">
<td align="center">4</td>
<td align="center">Quartil</td>
<td align="center"><span class="math inline">\(Q_1\)</span>, <span class="math inline">\(Q_2\)</span>, <span class="math inline">\(Q_3\)</span></td>
</tr>
<tr class="even">
<td align="center">10</td>
<td align="center">Decil</td>
<td align="center"><span class="math inline">\(D_1\)</span>, <span class="math inline">\(D_2\)</span>, <span class="math inline">\(\ldots\)</span>, <span class="math inline">\(D_9\)</span></td>
</tr>
<tr class="odd">
<td align="center">100</td>
<td align="center">Percentil</td>
<td align="center"><span class="math inline">\(P_1\)</span>, <span class="math inline">\(P_2\)</span>, <span class="math inline">\(\ldots\)</span>, <span class="math inline">\(P_{99}\)</span></td>
</tr>
</tbody>
</table>

<div class="example">
<span id="exm:separatrizes" class="example"><strong>Example 2.31  </strong></span>(Separatrizes) A função <code>quantile</code> apresenta nove métodos para obtenção de separatrizes, portanto recomenda-se a leitura da documentação para maiores detalhes. Com ela pode-se facilmente obter os quantis desejados, bastando ajustar o argumento <span class="math inline">\(k\)</span>. Note que a função retorna as separatrizes expressas em percentis, onde <span class="math inline">\(0\%\)</span> equivale ao mínimo e <span class="math inline">\(100\%\)</span> ao máximo.
</div>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="estatistica-descritiva.html#cb143-1"></a>hosp &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&#39;http://www.filipezabala.com/data/hospital.txt&#39;</span>, <span class="dt">header =</span> T)</span>
<span id="cb143-2"><a href="estatistica-descritiva.html#cb143-2"></a><span class="kw">options</span>(<span class="dt">digits =</span> <span class="dv">3</span>)                                 <span class="co"># Para melhorar a apresentação</span></span>
<span id="cb143-3"><a href="estatistica-descritiva.html#cb143-3"></a><span class="kw">quantile</span>(hosp<span class="op">$</span>altura, <span class="dt">probs =</span> <span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span><span class="op">/</span><span class="dv">2</span>))       <span class="co"># Mediana</span></span></code></pre></div>
<pre><code>##   0%  50% 100% 
## 1.51 1.62 1.74</code></pre>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="estatistica-descritiva.html#cb145-1"></a><span class="kw">quantile</span>(hosp<span class="op">$</span>altura, <span class="dt">probs =</span> <span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span><span class="op">/</span><span class="dv">3</span>))       <span class="co"># Tercis</span></span></code></pre></div>
<pre><code>##    0% 33.3% 66.7%  100% 
##  1.51  1.61  1.65  1.74</code></pre>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="estatistica-descritiva.html#cb147-1"></a><span class="kw">quantile</span>(hosp<span class="op">$</span>altura, <span class="dt">probs =</span> <span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span><span class="op">/</span><span class="dv">4</span>))       <span class="co"># Quartis</span></span></code></pre></div>
<pre><code>##   0%  25%  50%  75% 100% 
## 1.51 1.60 1.62 1.65 1.74</code></pre>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="estatistica-descritiva.html#cb149-1"></a><span class="kw">quantile</span>(hosp<span class="op">$</span>altura, <span class="dt">probs =</span> <span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span><span class="op">/</span><span class="dv">10</span>))      <span class="co"># Decis</span></span></code></pre></div>
<pre><code>##   0%  10%  20%  30%  40%  50%  60%  70%  80%  90% 100% 
## 1.51 1.57 1.59 1.60 1.62 1.62 1.64 1.65 1.66 1.68 1.74</code></pre>

<div class="exercise">
<span id="exr:unnamed-chunk-27" class="exercise"><strong>Exercise 2.5  </strong></span>Interprete os quantis do Exemplo <a href="estatistica-descritiva.html#exm:separatrizes">2.31</a>. <span class="math inline">\(\\\)</span>
</div>

<div class="exercise">
<span id="exr:unnamed-chunk-28" class="exercise"><strong>Exercise 2.6  </strong></span>Considere as separatrizes discutidas nesta Seção.<br />
a. Verifique que as separatrizes mediana (Md), segundo quartil (<span class="math inline">\(Q_2\)</span>) são equivalentes.<br />
b. Existem outras medidas equivalentes às do item (a)? Justifique.<br />
c. Considere algum <span class="math inline">\(k\)</span> diferente dos apresentados e atribua um nome e uma simbologia.<br />
d. Se existem <span class="math inline">\(k\)</span> ‘fatias’, quantas são as separatrizes? <span class="math inline">\(\\\)</span>
</div>

<div class="exercise">
<span id="exr:unnamed-chunk-29" class="exercise"><strong>Exercise 2.7  </strong></span>Utilizando a função <code>quantile</code> calcule as separatrizes discutidas nesta Seção com os dados da coluna <code>filhos</code> disponível em <a href="http://www.filipezabala.com/data/hospital.txt" class="uri">http://www.filipezabala.com/data/hospital.txt</a>.
</div>
</div>
</div>
</div>
<div id="medidas-de-dispersão-ou-variabilidade" class="section level2" number="2.4">
<h2><span class="header-section-number">2.4</span> Medidas de Dispersão (ou Variabilidade)</h2>
<div id="amplitude" class="section level3" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> Amplitude</h3>
<p>A <em>amplitude</em> é a medida de dispersão mais simples de ser calculada, e fornece uma informação rápida sobre a variabilidade do conjunto de dados. É calculada pela expressão
<span class="math display" id="eq:amplitude">\[\begin{equation}
A = \max{X} - \min{X}
\tag{2.15}
\end{equation}\]</span></p>

<div class="example">
<span id="exm:ampl-termica-pos" class="example"><strong>Example 2.32  </strong></span>(Amplitude com valores positivos) A amplitude das temperaturas 6, 4, 9, 20, 7 e 12 é <span class="math display">\[A = 20-4 = 16.\]</span> <span class="math inline">\(\\\)</span>
</div>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="estatistica-descritiva.html#cb151-1"></a>temp &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">6</span>,<span class="dv">4</span>,<span class="dv">9</span>,<span class="dv">20</span>,<span class="dv">7</span>,<span class="dv">12</span>)  <span class="co"># dados</span></span>
<span id="cb151-2"><a href="estatistica-descritiva.html#cb151-2"></a><span class="kw">max</span>(temp)<span class="op">-</span><span class="kw">min</span>(temp)       <span class="co"># pela Eq. (2.15)</span></span></code></pre></div>
<pre><code>## [1] 16</code></pre>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="estatistica-descritiva.html#cb153-1"></a>A &lt;-<span class="st"> </span><span class="kw">range</span>(temp)          <span class="co"># a função &#39;range&#39; retorna o mínimo e o máximo</span></span>
<span id="cb153-2"><a href="estatistica-descritiva.html#cb153-2"></a><span class="kw">diff</span>(A)                   <span class="co"># a função &#39;diff&#39; calcula a diferença</span></span></code></pre></div>
<pre><code>## [1] 16</code></pre>

<div class="example">
<span id="exm:ampl-termica-neg" class="example"><strong>Example 2.33  </strong></span>(Amplitude com valores negativos) A amplitude das temperaturas 6, -4, 9, 20, 7 e 12 é <span class="math display">\[A = 20-(-4) = 24.\]</span> <span class="math inline">\(\\\)</span>
</div>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="estatistica-descritiva.html#cb155-1"></a>temp &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">6</span>,<span class="op">-</span><span class="dv">4</span>,<span class="dv">9</span>,<span class="dv">20</span>,<span class="dv">7</span>,<span class="dv">12</span>) <span class="co"># dados</span></span>
<span id="cb155-2"><a href="estatistica-descritiva.html#cb155-2"></a><span class="kw">diff</span>(<span class="kw">range</span>(temp))         <span class="co"># funções aninhadas (&#39;nested functions&#39;)</span></span></code></pre></div>
<pre><code>## [1] 24</code></pre>
</div>
<div id="variância" class="section level3" number="2.4.2">
<h3><span class="header-section-number">2.4.2</span> Variância</h3>
<p>A <em>variância</em> é a principal medida de dispersão da Estatística. É uma média quadrática em relação à média, i.e., avalia o quanto, em média, os dados variam ao quadrado em torno da média. A variância <em>universal</em> pode ser calculada pelas Equações <a href="estatistica-descritiva.html#eq:var-univ1">(2.16)</a> e <a href="estatistica-descritiva.html#eq:var-univ2">(2.17)</a>.</p>
<p><span class="math display" id="eq:var-univ1">\[\begin{equation}
\sigma^2 = \frac{\sum_{i=1}^N (x_i - \mu)^2}{N}
\tag{2.16}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:var-univ2">\[\begin{equation}
\sigma^2 = \frac{\sum_{i=1}^N x_{i}^2}{N} - \mu^2
\tag{2.17}
\end{equation}\]</span></p>

<div class="example">
<span id="exm:var-univ-descr" class="example"><strong>Example 2.34  </strong></span>A variância universal do conjunto de dados 186, 402, 191, 20, 7 e 124 é
</div>
<p><strong>Equação (2.16)</strong> <span class="math display">\[\sigma^2 = \frac{\sum_{i=1}^6 (x_i - 155)^2}{6} = \frac{(186-155)^2+(402-155)^2+ \cdots + (124-155)^2}{6} = \frac{104356}{6} = 17392.\bar{6}\]</span></p>
<p><strong>Equação (2.17)</strong> <span class="math display">\[\sigma^2 = \frac{186^2+402^2+191^2+20^2+7^2+124^2}{6} - 155^2 = \frac{248506}{6} - 24025 = 17392.\bar{6}\]</span></p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="estatistica-descritiva.html#cb157-1"></a>(var.p &lt;-<span class="st"> </span><span class="kw">var</span>(<span class="kw">c</span>(<span class="dv">186</span>,<span class="dv">402</span>,<span class="dv">191</span>,<span class="dv">20</span>,<span class="dv">7</span>,<span class="dv">124</span>))<span class="op">*</span>(<span class="dv">5</span><span class="op">/</span><span class="dv">6</span>))   <span class="co"># variância amostral*(1/fator de correção)</span></span></code></pre></div>
<pre><code>## [1] 17393</code></pre>
<p>A variância <em>amostral</em> pode ser calculada pelas Equações <a href="estatistica-descritiva.html#eq:var-am1">(2.18)</a> e <a href="estatistica-descritiva.html#eq:var-am2">(2.19)</a></p>
<p><span class="math display" id="eq:var-am1">\[\begin{equation}
\hat{\sigma}^2 = s_{n}^2 = \frac{\sum_{i=1}^n (x_i - \bar{x})^2}{n-1}
\tag{2.18}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:var-am2">\[\begin{equation}
\hat{\sigma}^2 = s_{n}^2 = \left( \frac{\sum_{i=1}^n x_{i}^2}{n} - \bar{x}^2 \right) \left( \frac{n}{n-1} \right) 
\tag{2.19}
\end{equation}\]</span></p>

<div class="example">
<span id="exm:var-am-descr" class="example"><strong>Example 2.35  </strong></span>A variância amostral do conjunto de dados 186, 402, 191, 20, 7 e 124 é
</div>
<p><strong>Equação (2.18)</strong> <span class="math display">\[s_{6}^2 = \frac{\sum_{i=1}^6 (x_i - 155)^2}{6-1} = \frac{(186-155)^2+(402-155)^2+ \cdots + (124-155)^2}{6-1} = \frac{104356}{5} = 20871.2\]</span></p>
<p><strong>Equação (2.19)</strong> <span class="math display">\[s_{6}^2 = \left( \frac{186^2+402^2+191^2+20^2+7^2+124^2}{6} - 155^2 \right) \left( \frac{6}{5} \right) = 17392.\bar{6} \times 1.2 = 20871.2\]</span></p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="estatistica-descritiva.html#cb159-1"></a>(var.a &lt;-<span class="st"> </span><span class="kw">var</span>(<span class="kw">c</span>(<span class="dv">186</span>,<span class="dv">402</span>,<span class="dv">191</span>,<span class="dv">20</span>,<span class="dv">7</span>,<span class="dv">124</span>)))     <span class="co"># &#39;var&#39; calcula a variância amostral</span></span></code></pre></div>
<pre><code>## [1] 20871</code></pre>
<p>Assim, se o conjunto de dados deste exemplo representar uma amostra observada em 6 vezes que se contou o número de passos até a lixeira mais próxima na capital do Rio Grande (do Sul), pode-se dizer que a variância amostral é 20871.2 passos<span class="math inline">\(^2\)</span>. Dica: não tente interpretar este valor.</p>
<p>Note pela Equação <a href="estatistica-descritiva.html#eq:var-am1">(2.18)</a> que a variância amostral é dividida por <span class="math inline">\(n-1\)</span> e não por <span class="math inline">\(n\)</span>. Isto faz com que a variância amostral seja maior ou igual à variância universal para os mesmos dados. Intuitivamente pode-se pensar como uma espécie de penalidade aplicada a esta medida quando observa-se apenas parte do universo (amostra). Da mesma forma pode-se pensar na variância amostral como o produto entre a variância universal <span class="math inline">\(\sigma^2\)</span> e o fator <span class="math inline">\(n/(n-1)\)</span>, descrito por</p>
<p><span class="math display" id="eq:var-univ-am">\[\begin{equation}
s_{n}^2 = \sigma^2 \left( \frac{n}{n-1} \right)
\tag{2.20}
\end{equation}\]</span></p>
</div>
<div id="desvio-padrão" class="section level3" number="2.4.3">
<h3><span class="header-section-number">2.4.3</span> Desvio Padrão</h3>
<p>O desvio padrão é a raiz quadrada da variância. O motivo de calcular o desvio padrão é que a sua interpretação é mais intuitiva se comparada à da variância, uma vez que a unidade de medida do desvio padrão é a mesma da variável <span class="math inline">\(X\)</span>. As fórmulas do desvio padrão universal e amostral são dadas respectivamente pelas equações<a href="#fn15" class="footnote-ref" id="fnref15"><sup>15</sup></a> <a href="estatistica-descritiva.html#eq:dp-univ">(2.21)</a> e <a href="estatistica-descritiva.html#eq:dp-am">(2.22)</a>.</p>
<p><span class="math display" id="eq:dp-univ">\[\begin{equation}
\sigma = \sqrt{\sigma^2} 
\tag{2.21}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:dp-am">\[\begin{equation}
s_{n} = \sqrt{s^{2}_{n}}
\tag{2.22}
\end{equation}\]</span></p>

<div class="example">
<span id="exm:dp-universal" class="example"><strong>Example 2.36  </strong></span>(Desvio padrão universal) Do Exemplo <a href="estatistica-descritiva.html#exm:var-univ-descr">2.34</a> sabe-se que a variância universal do conjunto de dados 186, 402, 191, 20, 7 e 124 é <span class="math inline">\(\sigma^2 = 17392.\bar{6}\)</span>. Assim, o desvio padrão universal é <span class="math display">\[\sigma = \sqrt{17392.\bar{6}} \approx 131.88126.\]</span>
</div>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="estatistica-descritiva.html#cb161-1"></a>dat &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">186</span>,<span class="dv">402</span>,<span class="dv">191</span>,<span class="dv">20</span>,<span class="dv">7</span>,<span class="dv">124</span>)    <span class="co"># dados</span></span>
<span id="cb161-2"><a href="estatistica-descritiva.html#cb161-2"></a>(dp.p &lt;-<span class="st"> </span><span class="kw">sd</span>(dat) <span class="op">*</span><span class="st"> </span><span class="kw">sqrt</span>(<span class="dv">5</span><span class="op">/</span><span class="dv">6</span>))     <span class="co"># s_n * raiz(1/fator de correção)</span></span></code></pre></div>
<pre><code>## [1] 132</code></pre>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="estatistica-descritiva.html#cb163-1"></a><span class="kw">all.equal</span>(dp.p, <span class="kw">sqrt</span>(var.p))      <span class="co"># &#39;dp.p&#39; é igual à raiz quadrada de &#39;var.p&#39;</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="estatistica-descritiva.html#cb165-1"></a><span class="kw">all.equal</span>(dp.p<span class="op">^</span><span class="dv">2</span>, var.p)          <span class="co"># &#39;dp.p&#39; ao quadrado é igual a &#39;var.p&#39;</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>

<div class="example">
<span id="exm:dp-amostral" class="example"><strong>Example 2.37  </strong></span>Do Exemplo <a href="estatistica-descritiva.html#exm:var-am-descr">2.35</a> sabe-se que a variância amostral do conjunto de dados 186, 402, 191, 20, 7 e 124 é <span class="math inline">\(s^{2}_{6}= 20871.2\)</span>. Assim, o desvio padrão amostral é <span class="math display">\[s_{6} = \sqrt{20871.2}  \approx 144.46868.\]</span>
</div>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="estatistica-descritiva.html#cb167-1"></a>dat &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">186</span>,<span class="dv">402</span>,<span class="dv">191</span>,<span class="dv">20</span>,<span class="dv">7</span>,<span class="dv">124</span>)    <span class="co"># dados</span></span>
<span id="cb167-2"><a href="estatistica-descritiva.html#cb167-2"></a>(dp.a &lt;-<span class="st"> </span><span class="kw">sd</span>(dat))                 <span class="co"># &#39;sd&#39; calcula o desvio padrão amostral</span></span></code></pre></div>
<pre><code>## [1] 144</code></pre>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="estatistica-descritiva.html#cb169-1"></a><span class="kw">all.equal</span>(dp.a, <span class="kw">sqrt</span>(var.a))      <span class="co"># &#39;dp.a&#39; é igual à raiz quadrada de &#39;var.a&#39;</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="estatistica-descritiva.html#cb171-1"></a><span class="kw">all.equal</span>(dp.a<span class="op">^</span><span class="dv">2</span>, var.a)          <span class="co"># &#39;dp.a&#39; ao quadrado é igual a &#39;var.a&#39;</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>Assim, se o conjunto de dados deste exemplo representar uma amostra observada em 6 vezes que se contou o número de passos até a lixeira mais próxima na capital do Rio Grande (do Sul), pode-se dizer que o desvio padrão (amostral, claro) é de aproximadamente 144.5 passos. Pode-se pensar neste valor como uma oscilação média aproximada em torno da média aritmética.</p>
</div>
<div id="coeficiente-de-variação" class="section level3" number="2.4.4">
<h3><span class="header-section-number">2.4.4</span> Coeficiente de variação</h3>
<p>O <em>coeficiente de variação</em> é uma medida de comparação de variabilidades, uma vez que ajusta o desvio padrão pela média. É preferível ao desvio padrão por ser um número adimensional, i.e., não possui unidade de medida, tornando quaisquer conjuntos de dados comparáveis em termos de variabilidade. É utilizado em diversas áreas da Estatística, mas é popularmente conhecido como medida de risco em carteiras de ativos.</p>
<p>As fórmulas do coeficiente de variação universal e amostral são dadas respectivamente pelas equações <a href="estatistica-descritiva.html#eq:cv-pop">(2.23)</a> e <a href="estatistica-descritiva.html#eq:cv-am">(2.24)</a>.
<span class="math display" id="eq:cv-pop">\[\begin{equation}
\gamma = \frac{\sigma}{\mu}
\tag{2.23}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:cv-am">\[\begin{equation}
\hat{\gamma} = g = \frac{s}{\bar{x}}
\tag{2.24}
\end{equation}\]</span></p>

<div class="example">
<span id="exm:cv" class="example"><strong>Example 2.38  </strong></span>(Coeficiente de variação) Duas variáveis são obtidas em um certo experimento químico. A variável X é medida em microgramas e possui média de 0.0045 <span class="math inline">\(\mu\)</span>g e desvio padrão de 0.0056 <span class="math inline">\(\mu\)</span>g. A variável Y é medida em mols e possui média de 3549 mols e desvio padrão de 419 mols. O coeficiente de variação de X é dado por <span class="math inline">\(g_X=\frac{0.0056}{0.0045} \approx 1.24\)</span>, e de Y por <span class="math inline">\(g_Y=\frac{419}{3549} \approx 0.12\)</span>. Portanto, como <span class="math inline">\(1.24 &gt; 0.12\)</span>, conclui-se que o conjunto de dados X varia mais do que Y.
</div>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="estatistica-descritiva.html#cb173-1"></a>mx &lt;-<span class="st"> </span><span class="fl">0.0045</span></span>
<span id="cb173-2"><a href="estatistica-descritiva.html#cb173-2"></a>dx &lt;-<span class="st"> </span><span class="fl">0.0056</span></span>
<span id="cb173-3"><a href="estatistica-descritiva.html#cb173-3"></a><span class="kw">round</span>(gx &lt;-<span class="st"> </span>dx<span class="op">/</span>mx, <span class="dv">2</span>)   <span class="co"># Coeficiente de variação de X</span></span></code></pre></div>
<pre><code>## [1] 1.24</code></pre>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="estatistica-descritiva.html#cb175-1"></a>my &lt;-<span class="st"> </span><span class="dv">3549</span></span>
<span id="cb175-2"><a href="estatistica-descritiva.html#cb175-2"></a>dy &lt;-<span class="st"> </span><span class="dv">419</span></span>
<span id="cb175-3"><a href="estatistica-descritiva.html#cb175-3"></a><span class="kw">round</span>(gy &lt;-<span class="st"> </span>dy<span class="op">/</span>my, <span class="dv">2</span>)   <span class="co"># Coeficiente de variação de Y</span></span></code></pre></div>
<pre><code>## [1] 0.12</code></pre>
</div>
</div>
<div id="outras-medidas" class="section level2" number="2.5">
<h2><span class="header-section-number">2.5</span> Outras medidas</h2>
<div id="assimetria-ou-obliquidade" class="section level3" number="2.5.1">
<h3><span class="header-section-number">2.5.1</span> Assimetria (ou Obliquidade)</h3>
<p><em>Assimetria</em> ou <em>obliquidade</em> é uma medida que avalia a assimetria de uma distribuição de frequência. Existem diversas definições na literatura, das quais apresentam-se três alternativas.
<span class="math display" id="eq:ass1">\[\begin{equation}
g_1 = \dfrac{m_3}{m_2^{3/2}} = \dfrac{\frac{1}{n} \sum_{i=1}^{n} (x_{i} - \bar{x}_n)^3}{\left[ \frac{1}{n} \sum_{i=1}^{n} (x_{i} - \bar{x}_n)^2 \right]^{3/2}}
\tag{2.25}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:ass3">\[\begin{equation}
b_1 = g_{1} \left( \dfrac{n-1}{n} \right)^{3/2} = \dfrac{m_3}{s^3} = \dfrac{\frac{1}{n} \sum_{i=1}^{n} (x_{i} - \bar{x}_n)^3 }{\left[ \frac{1}{n-1} \sum_{i=1}^{n} (x_{i} - \bar{x}_n)^2 \right]^{3/2}}
\tag{2.26}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:ass2">\[\begin{eqnarray}
G_1 = g_{1} \sqrt{\dfrac{n(n-1)}{n-2}} = b_{1} \dfrac{n^2}{(n-1)(n-2)}
\tag{2.27}
\end{eqnarray}\]</span></p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="estatistica-descritiva.html#cb177-1"></a><span class="kw">set.seed</span>(<span class="dv">1</span>); x &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>)    <span class="co"># Gerando 100 valores N(0,1) com semente fixa</span></span>
<span id="cb177-2"><a href="estatistica-descritiva.html#cb177-2"></a>e1071<span class="op">::</span><span class="kw">skewness</span>(x, <span class="dt">type =</span> <span class="dv">1</span>)    <span class="co"># Definição clássica de assimetria, Equação (2.25)</span></span></code></pre></div>
<pre><code>## [1] -0.0722</code></pre>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="estatistica-descritiva.html#cb179-1"></a>e1071<span class="op">::</span><span class="kw">skewness</span>(x, <span class="dt">type =</span> <span class="dv">2</span>)    <span class="co"># Utilizada no SAS, SPSS e Excel, Equação (2.27)</span></span></code></pre></div>
<pre><code>## [1] -0.0733</code></pre>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="estatistica-descritiva.html#cb181-1"></a>e1071<span class="op">::</span><span class="kw">skewness</span>(x, <span class="dt">type =</span> <span class="dv">3</span>)    <span class="co"># Padrão do R, utilizada no MINITAB e BMDP, Equação (2.26)</span></span></code></pre></div>
<pre><code>## [1] -0.0712</code></pre>
</div>
<div id="curtose" class="section level3" number="2.5.2">
<h3><span class="header-section-number">2.5.2</span> Curtose</h3>
<p>A <em>curtose</em> é uma medida de achatamento de uma distribuição de frequência. Assim como na assimetria, das diversas definições de curtose apresentam-se três alternativas.
<span class="math display" id="eq:cur1">\[\begin{eqnarray}
g_2 = \dfrac{m_4}{m_2^{2}} - 3 = \dfrac{\frac{1}{n} \sum_{i=1}^{n} (x_{i} - \bar{x}_n)^4}{\left[ \frac{1}{n} \sum_{i=1}^{n} (x_{i} - \bar{x}_n)^2 \right]^{2}} - 3
\tag{2.28}
\end{eqnarray}\]</span></p>
<p><span class="math display" id="eq:cur3">\[\begin{eqnarray}
b_2 = (g_2 + 3) \left( 1 - \dfrac{1}{n} \right)^{2} - 3 = \dfrac{m_4}{s^4} - 3 = \dfrac{\frac{1}{n} \sum_{i=1}^{n} (x_{i} - \bar{x}_n)^4 }{\left[ \frac{1}{n-1} \sum_{i=1}^{n} (x_{i} - \bar{x}_n)^2 \right]^{2}} - 3
\tag{2.29}
\end{eqnarray}\]</span></p>
<p><span class="math display" id="eq:cur2">\[\begin{eqnarray}
G_2 = \dfrac{ \left[ (n+1) g_2 + 6 \right] (n-1)}{(n-2)(n-3)}
\tag{2.30}
\end{eqnarray}\]</span></p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="estatistica-descritiva.html#cb183-1"></a><span class="kw">set.seed</span>(<span class="dv">1</span>); x &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>)    <span class="co"># Gerando 100 valores N(0,1) com semente fixa</span></span>
<span id="cb183-2"><a href="estatistica-descritiva.html#cb183-2"></a>e1071<span class="op">::</span><span class="kw">kurtosis</span>(x, <span class="dt">type =</span> <span class="dv">1</span>)    <span class="co"># Definição clássica de curtose, Equação (2.28)</span></span></code></pre></div>
<pre><code>## [1] 0.00765</code></pre>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="estatistica-descritiva.html#cb185-1"></a>e1071<span class="op">::</span><span class="kw">kurtosis</span>(x, <span class="dt">type =</span> <span class="dv">2</span>)    <span class="co"># Usada no SAS, SPSS e Excel, Equação (2.30)</span></span></code></pre></div>
<pre><code>## [1] 0.0705</code></pre>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="estatistica-descritiva.html#cb187-1"></a>e1071<span class="op">::</span><span class="kw">kurtosis</span>(x, <span class="dt">type =</span> <span class="dv">3</span>)    <span class="co"># Padrão do R, usada também no MINITAB e BMDP, Eq. (2.29)</span></span></code></pre></div>
<pre><code>## [1] -0.0522</code></pre>
</div>
</div>
<div id="visualização" class="section level2" number="2.6">
<h2><span class="header-section-number">2.6</span> Visualização</h2>
<p><em>Visualização</em> é o processo de representar informações ou ideias através de diagramas, gráficos e outros métodos de apresentação visual. De um modo geral, as ferramentas de visualização devem ser claras para o leitor, devendo-se evitar detalhes desnecessários. Um bom visualizador transmite a informação desejada de forma clara, precisa e eficiente. Ao apresentar informação de maneira visual deve-se considerar que ‘o menos é mais’. <a href="https://www.edwardtufte.com/">Edward Tufte</a>, “o Leonardo da Vinci dos dados” segundo <a href="https://www.nytimes.com/"><em>The New York Times</em></a>, ou “o Galileu dos gráficos” de acordo com a <a href="https://www.bloomberg.com/"><em>Bloomberg</em></a>, possui uma vasta obra sobre o tema. Em <span class="citation">(Tufte and Graves-Morris <a href="#ref-tufte1983visual" role="doc-biblioref">1983</a>)</span>, <span class="citation">(Tufte <a href="#ref-tufte1993envisioning" role="doc-biblioref">1993</a>)</span>, <span class="citation">(Tufte et al. <a href="#ref-tufte1998visual" role="doc-biblioref">1998</a>)</span> e <span class="citation">(Tufte <a href="#ref-tufte2006beautiful" role="doc-biblioref">2006</a>)</span> apresenta uma série de considerações e exemplos muito ricos e elegantes, algumas indicadas a seguir.</p>
<ul>
<li>o olho humano não diferencia muitas tonalidades de cor, por isso é interessante trabalhar com escalas em degradê, diferentes texturas e espessuras de linha<br />
</li>
<li>para apresentar dados categóricos é interessante ordenar as categorias de forma intuitiva para melhor apresentação<br />
</li>
<li>deve-se evitar o agrupamento de dados contínuos em categorias<br />
</li>
<li>é importante manter a notação coerente com o texto</li>
</ul>
<div id="menu-de-opções" class="section level3" number="2.6.1">
<h3><span class="header-section-number">2.6.1</span> Menu de opções</h3>
<ul>
<li><a href="https://plot.ly/r/" class="uri">https://plot.ly/r/</a></li>
<li><a href="https://www.r-graph-gallery.com/" class="uri">https://www.r-graph-gallery.com/</a></li>
<li><a href="https://github.com/d3/d3/wiki/Gallery" class="uri">https://github.com/d3/d3/wiki/Gallery</a></li>
<li><a href="http://kateto.net/network-visualization" class="uri">http://kateto.net/network-visualization</a></li>
<li><a href="https://www.shinyapps.org/apps/RGraphCompendium/index.php" class="uri">https://www.shinyapps.org/apps/RGraphCompendium/index.php</a></li>
<li><a href="http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html" class="uri">http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html</a></li>
<li><a href="https://d3js.org/" class="uri">https://d3js.org/</a> (JavaScript)</li>
</ul>
<!-- ### Exemplos -->
<!-- #### Correlograma {-} -->
<!-- Adaptado de http://www.r-graph-gallery.com/97-correlation-ellipses/. -->
<!-- ```{r} -->
<!-- # Bibliotecas -->
<!-- # install.packages(c('ellipse','RColorBrewer'), dep=T) -->
<!-- library(ellipse) -->
<!-- library(RColorBrewer) -->
<!-- # Usando o famoso banco de dados 'mtcars' -->
<!-- data <- cor(mtcars) -->
<!-- # Painel de 100 cores com Rcolor Brewer -->
<!-- my_colors <- brewer.pal(5, "Spectral") -->
<!-- my_colors <- colorRampPalette(my_colors)(100) -->
<!-- # Ordenando a matriz de correlação -->
<!-- ord <- order(data[1, ]) -->
<!-- data_ord <- data[ord, ord] -->
<!-- plotcorr(data_ord , col=my_colors[data_ord*50+50] , mar=c(1,1,1,1)) -->
<!-- ``` -->
<!-- Adaptado de http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html#Correlogram. -->
<!-- ```{r} -->
<!-- # Bibliotecas -->
<!-- # devtools::install_github("kassambara/ggcorrplot") -->
<!-- library(ggplot2) -->
<!-- library(ggcorrplot) -->
<!-- # Matriz de correlação -->
<!-- data(mtcars) -->
<!-- corr <- round(cor(mtcars), 1) -->
<!-- # Gráfico -->
<!-- ggcorrplot(corr, hc.order = TRUE,  -->
<!--            type = 'lower',  -->
<!--            lab = TRUE,  -->
<!--            lab_size = 3,  -->
<!--            method = 'circle',  -->
<!--            colors = c('tomato2', 'white', 'springgreen3'),  -->
<!--            title = 'Correlograma de mtcars',  -->
<!--            ggtheme = theme_bw) -->
<!-- ``` -->

</div>
</div>
</div>
<h3> Referências</h3>
<div id="refs" class="references">
<div id="ref-freedman1981histogram">
<p>Freedman, David, and Persi Diaconis. 1981. “On the Histogram as a Density Estimator: L2 Theory.” <em>Zeitschrift Für Wahrscheinlichkeitstheorie Und Verwandte Gebiete</em> 57 (4): 453–76. <a href="https://link.springer.com/content/pdf/10.1007/BF01025868.pdf">https://link.springer.com/content/pdf/10.1007/BF01025868.pdf</a>.</p>
</div>
<div id="ref-hyndman1995problem">
<p>Hyndman, Rob J. 1995. “The Problem with Sturges Rule for Constructing Histograms.” <a href="http://robjhyndman.com/papers/sturges.pdf">http://robjhyndman.com/papers/sturges.pdf</a>.</p>
</div>
<div id="ref-kotz2000extreme">
<p>Kotz, S., and S. Nadarajah. 2000. <em>Extreme Value Distributions</em>. World Scientific. <a href="https://books.google.com.br/books/about/Extreme_Value_Distributions.html?id=ZPW3CgAAQBAJ&amp;redir_esc=y">https://books.google.com.br/books/about/Extreme_Value_Distributions.html?id=ZPW3CgAAQBAJ&amp;redir_esc=y</a>.</p>
</div>
<div id="ref-scott1979optimal">
<p>Scott, David W. 1979. “On Optimal and Data-Based Histograms.” <em>Biometrika</em> 66 (3): 605–10. <a href="https://www.jstor.org/stable/2335182">https://www.jstor.org/stable/2335182</a>.</p>
</div>
<div id="ref-sturges1926choice">
<p>Sturges, Herbert A. 1926. “The Choice of a Class Interval.” <em>Journal of the American Statistical Association</em> 21 (153): 65–66.</p>
</div>
<div id="ref-tufte1993envisioning">
<p>Tufte, Edward R. 1993. “Envisioning Information.”</p>
</div>
<div id="ref-tufte2006beautiful">
<p>Tufte, Edward R. 2006. <em>Beautiful Evidence</em>. Graphis Pr.</p>
</div>
<div id="ref-tufte1983visual">
<p>Tufte, Edward R, and Peter R Graves-Morris. 1983. <em>The Visual Display of Quantitative Information</em>. Vol. 2. 9. Graphics press Cheshire, CT. <a href="https://www.cs.rug.nl/svcg/uploads/VisualAnalytics/Tufte01-2.pdf">https://www.cs.rug.nl/svcg/uploads/VisualAnalytics/Tufte01-2.pdf</a>.</p>
</div>
<div id="ref-tufte1998visual">
<p>Tufte, Edward R, Susan R McKay, Wolfgang Christian, and James R Matey. 1998. “Visual Explanations: Images and Quantities, Evidence and Narrative.” American Institute of Physics.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="9">
<li id="fn9"><p><a href="http://www.imdb.com/title/tt0995577" class="uri">http://www.imdb.com/title/tt0995577</a><a href="estatistica-descritiva.html#fnref9" class="footnote-back">↩︎</a></p></li>
<li id="fn10"><p>Um conjunto  é aquele em que se pode listar e contar os elementos.<a href="estatistica-descritiva.html#fnref10" class="footnote-back">↩︎</a></p></li>
<li id="fn11"><p>Passos Até a Bufunfa.<a href="estatistica-descritiva.html#fnref11" class="footnote-back">↩︎</a></p></li>
<li id="fn12"><p>Um conjunto <em>não enumerável</em> possui infinitos elementos, sendo impossível listá-los segundo alguma regra.<a href="estatistica-descritiva.html#fnref12" class="footnote-back">↩︎</a></p></li>
<li id="fn13"><p>Note que a simbologia 1.70 <span class="math inline">\(\vdash\)</span> 1.75 indica a inclusão de 1.70 e a exclusão de 1.75, i.e., este é um intervalo fechado à esquerda e aberto à direita. Equivale às notações <span class="math inline">\(\left[ 1.70, 1.75 \right[\)</span> (mais moderna) ou <span class="math inline">\(\left[ 1.70, 1.75 \right)\)</span> (mais antiga).<a href="estatistica-descritiva.html#fnref13" class="footnote-back">↩︎</a></p></li>
<li id="fn14"><p>Pronuncia-se <em>quantís</em>.<a href="estatistica-descritiva.html#fnref14" class="footnote-back">↩︎</a></p></li>
<li id="fn15"><p>Se você ficou confuso com a notação, escreva <span class="math inline">\(\sigma^2= V\)</span> e <span class="math inline">\(\sigma=D\)</span> (bem como <span class="math inline">\(s^2=v\)</span> e <span class="math inline">\(s=d\)</span>) e repense o problema.<a href="estatistica-descritiva.html#fnref15" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introducao.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="probabilidade.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
