<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7 Modelos Lineares | Fundamentos de Estatística para Ciência de Dados</title>
  <meta name="description" content="Este é o livro da disciplina Fundamentos de Estatística para Ciência de Dados da PUCRS-UOL escrito no RStudio. Sinta-se à vontade para compartilhar e colaborar https://github.com/filipezabala/fdepcdd" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="7 Modelos Lineares | Fundamentos de Estatística para Ciência de Dados" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Este é o livro da disciplina Fundamentos de Estatística para Ciência de Dados da PUCRS-UOL escrito no RStudio. Sinta-se à vontade para compartilhar e colaborar https://github.com/filipezabala/fdepcdd" />
  <meta name="github-repo" content="filipezabala/fdepcdd" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7 Modelos Lineares | Fundamentos de Estatística para Ciência de Dados" />
  
  <meta name="twitter:description" content="Este é o livro da disciplina Fundamentos de Estatística para Ciência de Dados da PUCRS-UOL escrito no RStudio. Sinta-se à vontade para compartilhar e colaborar https://github.com/filipezabala/fdepcdd" />
  

<meta name="author" content="Filipe J. Zabala" />


<meta name="date" content="2020-11-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="inferencia-bayesiana.html"/>
<link rel="next" href="aprendizadodemaquina.html"/>
<script src="libs/header-attrs-2.5/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.2/htmlwidgets.js"></script>
<link href="libs/rglwidgetClass-2/rgl.css" rel="stylesheet" />
<script src="libs/rglwidgetClass-2/rglClass.src.js"></script>
<script src="libs/CanvasMatrix4-2016/CanvasMatrix.src.js"></script>
<script src="libs/rglWebGL-binding-0.100.54/rglWebGL.js"></script>
<link href="libs/crosstalk-1.1.0.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.0.1/js/crosstalk.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefácio</a></li>
<li class="chapter" data-level="1" data-path="introducao.html"><a href="introducao.html"><i class="fa fa-check"></i><b>1</b> Introdução</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introducao.html"><a href="introducao.html#ferramentas"><i class="fa fa-check"></i><b>1.1</b> Ferramentas</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="introducao.html"><a href="introducao.html#r"><i class="fa fa-check"></i><b>1.1.1</b> R</a></li>
<li class="chapter" data-level="1.1.2" data-path="introducao.html"><a href="introducao.html#rstudio"><i class="fa fa-check"></i><b>1.1.2</b> RStudio</a></li>
<li class="chapter" data-level="1.1.3" data-path="introducao.html"><a href="introducao.html#python"><i class="fa fa-check"></i><b>1.1.3</b> Python</a></li>
<li class="chapter" data-level="1.1.4" data-path="introducao.html"><a href="introducao.html#jasp"><i class="fa fa-check"></i><b>1.1.4</b> JASP</a></li>
<li class="chapter" data-level="1.1.5" data-path="introducao.html"><a href="introducao.html#stan"><i class="fa fa-check"></i><b>1.1.5</b> Stan</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="introducao.html"><a href="introducao.html#materiais-de-apoio"><i class="fa fa-check"></i><b>1.2</b> Materiais de apoio</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="introducao.html"><a href="introducao.html#página-do-professor-filipe-zabala"><i class="fa fa-check"></i><b>1.2.1</b> Página do professor Filipe Zabala</a></li>
<li class="chapter" data-level="1.2.2" data-path="introducao.html"><a href="introducao.html#khan-academy"><i class="fa fa-check"></i><b>1.2.2</b> Khan Academy</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introducao.html"><a href="introducao.html#algarismos-e-numeros"><i class="fa fa-check"></i><b>1.3</b> Algarismos e Números</a></li>
<li class="chapter" data-level="1.4" data-path="introducao.html"><a href="introducao.html#porcentagens-decimais-e-milhares"><i class="fa fa-check"></i><b>1.4</b> Porcentagens, Decimais e Milhares</a></li>
<li class="chapter" data-level="1.5" data-path="introducao.html"><a href="introducao.html#o-senhor-x"><i class="fa fa-check"></i><b>1.5</b> O Senhor <span class="math inline">\(X\)</span></a></li>
<li class="chapter" data-level="1.6" data-path="introducao.html"><a href="introducao.html#somatorio"><i class="fa fa-check"></i><b>1.6</b> Somatório</a></li>
<li class="chapter" data-level="1.7" data-path="introducao.html"><a href="introducao.html#arredondamento-e-truncagem"><i class="fa fa-check"></i><b>1.7</b> Arredondamento e Truncagem</a></li>
<li class="chapter" data-level="1.8" data-path="introducao.html"><a href="introducao.html#outros"><i class="fa fa-check"></i><b>1.8</b> Outros símbolos e expressões</a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="introducao.html"><a href="introducao.html#alfabeto-grego"><i class="fa fa-check"></i><b>1.8.1</b> Alfabeto grego</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html"><i class="fa fa-check"></i><b>2</b> Estatística Descritiva</a>
<ul>
<li class="chapter" data-level="2.1" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#variáveis"><i class="fa fa-check"></i><b>2.1</b> Variáveis</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#variavel-qualitativa-nominal"><i class="fa fa-check"></i><b>2.1.1</b> Variável qualitativa nominal</a></li>
<li class="chapter" data-level="2.1.2" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#variavel-qualitativa-ordinal"><i class="fa fa-check"></i><b>2.1.2</b> Variável qualitativa ordinal</a></li>
<li class="chapter" data-level="2.1.3" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#variavel-quantitativa-discreta"><i class="fa fa-check"></i><b>2.1.3</b> Variável quantitativa discreta</a></li>
<li class="chapter" data-level="2.1.4" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#variavel-quantitativa-continua"><i class="fa fa-check"></i><b>2.1.4</b> Variável quantitativa contínua</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#distribuicao-de-frequencia"><i class="fa fa-check"></i><b>2.2</b> Distribuição de Frequência</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#db-rol-eo"><i class="fa fa-check"></i><b>2.2.1</b> Dados brutos, Rol e Estatísticas de Ordem</a></li>
<li class="chapter" data-level="2.2.2" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#tab-freq-univ-discr"><i class="fa fa-check"></i><b>2.2.2</b> Tabela de frequência univariada discreta</a></li>
<li class="chapter" data-level="2.2.3" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#tab-freq-univ-cont"><i class="fa fa-check"></i><b>2.2.3</b> Tabela de frequência univariada contínua</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#posicao"><i class="fa fa-check"></i><b>2.3</b> Medidas de Posição (ou Localização)</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#minmax"><i class="fa fa-check"></i><b>2.3.1</b> Mínimo e Máximo</a></li>
<li class="chapter" data-level="2.3.2" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#mas"><i class="fa fa-check"></i><b>2.3.2</b> Média (Aritmética Simples)</a></li>
<li class="chapter" data-level="2.3.3" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#total"><i class="fa fa-check"></i><b>2.3.3</b> Total</a></li>
<li class="chapter" data-level="2.3.4" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#mquadr"><i class="fa fa-check"></i><b>2.3.4</b> Média Quadrática</a></li>
<li class="chapter" data-level="2.3.5" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#moda"><i class="fa fa-check"></i><b>2.3.5</b> Moda</a></li>
<li class="chapter" data-level="2.3.6" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#separatrizes"><i class="fa fa-check"></i><b>2.3.6</b> Separatrizes</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#medidas-de-dispersão-ou-variabilidade"><i class="fa fa-check"></i><b>2.4</b> Medidas de Dispersão (ou Variabilidade)</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#amplitude"><i class="fa fa-check"></i><b>2.4.1</b> Amplitude</a></li>
<li class="chapter" data-level="2.4.2" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#variância"><i class="fa fa-check"></i><b>2.4.2</b> Variância</a></li>
<li class="chapter" data-level="2.4.3" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#desvio-padrão"><i class="fa fa-check"></i><b>2.4.3</b> Desvio Padrão</a></li>
<li class="chapter" data-level="2.4.4" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#coeficiente-de-variação"><i class="fa fa-check"></i><b>2.4.4</b> Coeficiente de variação</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#outras-medidas"><i class="fa fa-check"></i><b>2.5</b> Outras medidas</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#assimetria-ou-obliquidade"><i class="fa fa-check"></i><b>2.5.1</b> Assimetria (ou Obliquidade)</a></li>
<li class="chapter" data-level="2.5.2" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#curtose"><i class="fa fa-check"></i><b>2.5.2</b> Curtose</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#visualização"><i class="fa fa-check"></i><b>2.6</b> Visualização</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="estatistica-descritiva.html"><a href="estatistica-descritiva.html#menu-de-opções"><i class="fa fa-check"></i><b>2.6.1</b> Menu de opções</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="probabilidade.html"><a href="probabilidade.html"><i class="fa fa-check"></i><b>3</b> Probabilidade</a>
<ul>
<li class="chapter" data-level="3.1" data-path="probabilidade.html"><a href="probabilidade.html#propriedades"><i class="fa fa-check"></i><b>3.1</b> Propriedades</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="probabilidade.html"><a href="probabilidade.html#propriedades-fundamentais-axiomas-de-kolmogorov"><i class="fa fa-check"></i><b>3.1.1</b> Propriedades fundamentais (Axiomas de Kolmogorov)</a></li>
<li class="chapter" data-level="3.1.2" data-path="probabilidade.html"><a href="probabilidade.html#propriedades-secundárias"><i class="fa fa-check"></i><b>3.1.2</b> Propriedades secundárias</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="probabilidade.html"><a href="probabilidade.html#r-como-um-conjunto-de-tabelas-estatísticas"><i class="fa fa-check"></i><b>3.2</b> R como um conjunto de tabelas estatísticas</a></li>
<li class="chapter" data-level="3.3" data-path="probabilidade.html"><a href="probabilidade.html#distribuição-normal"><i class="fa fa-check"></i><b>3.3</b> Distribuição Normal</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="probabilidade.html"><a href="probabilidade.html#normal-univariada"><i class="fa fa-check"></i><b>3.3.1</b> Normal univariada</a></li>
<li class="chapter" data-level="3.3.2" data-path="probabilidade.html"><a href="probabilidade.html#normal-bivariada"><i class="fa fa-check"></i><b>3.3.2</b> Normal bivariada</a></li>
<li class="chapter" data-level="3.3.3" data-path="probabilidade.html"><a href="probabilidade.html#normal-multivariada"><i class="fa fa-check"></i><b>3.3.3</b> Normal multivariada</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="amostragem.html"><a href="amostragem.html"><i class="fa fa-check"></i><b>4</b> Amostragem</a>
<ul>
<li class="chapter" data-level="4.1" data-path="amostragem.html"><a href="amostragem.html#definições-básicas"><i class="fa fa-check"></i><b>4.1</b> Definições básicas</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="amostragem.html"><a href="amostragem.html#unidade-elementar"><i class="fa fa-check"></i><b>4.1.1</b> Unidade Elementar</a></li>
<li class="chapter" data-level="4.1.2" data-path="amostragem.html"><a href="amostragem.html#unidade-amostral"><i class="fa fa-check"></i><b>4.1.2</b> Unidade Amostral</a></li>
<li class="chapter" data-level="4.1.3" data-path="amostragem.html"><a href="amostragem.html#sistema-de-referências"><i class="fa fa-check"></i><b>4.1.3</b> Sistema de referências</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="amostragem.html"><a href="amostragem.html#universo-mathcalu"><i class="fa fa-check"></i><b>4.2</b> Universo <span class="math inline">\(\mathcal{U}\)</span></a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="amostragem.html"><a href="amostragem.html#parâmetros"><i class="fa fa-check"></i><b>4.2.1</b> Parâmetros</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="amostragem.html"><a href="amostragem.html#amostras"><i class="fa fa-check"></i><b>4.3</b> Amostras</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="amostragem.html"><a href="amostragem.html#plano-amostral"><i class="fa fa-check"></i><b>4.3.1</b> Plano Amostral</a></li>
<li class="chapter" data-level="4.3.2" data-path="amostragem.html"><a href="amostragem.html#distribuições-amostrais"><i class="fa fa-check"></i><b>4.3.2</b> Distribuições amostrais</a></li>
<li class="chapter" data-level="4.3.3" data-path="amostragem.html"><a href="amostragem.html#amostra-representativa"><i class="fa fa-check"></i><b>4.3.3</b> Amostra representativa</a></li>
<li class="chapter" data-level="4.3.4" data-path="amostragem.html"><a href="amostragem.html#tipos-de-amostras"><i class="fa fa-check"></i><b>4.3.4</b> Tipos de amostras</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="amostragem.html"><a href="amostragem.html#principais-técnicas-de-amostragem"><i class="fa fa-check"></i><b>4.4</b> Principais técnicas de amostragem</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="amostragem.html"><a href="amostragem.html#amostragem-aleatória-simples"><i class="fa fa-check"></i><b>4.4.1</b> Amostragem Aleatória Simples</a></li>
<li class="chapter" data-level="4.4.2" data-path="amostragem.html"><a href="amostragem.html#amostragem-sistemática"><i class="fa fa-check"></i><b>4.4.2</b> Amostragem Sistemática</a></li>
<li class="chapter" data-level="4.4.3" data-path="amostragem.html"><a href="amostragem.html#amostragem-estratificada"><i class="fa fa-check"></i><b>4.4.3</b> Amostragem Estratificada</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="amostragem.html"><a href="amostragem.html#cálculo-do-tamanho-da-amostra"><i class="fa fa-check"></i><b>4.5</b> Cálculo do tamanho da amostra</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="amostragem.html"><a href="amostragem.html#média"><i class="fa fa-check"></i><b>4.5.1</b> Média</a></li>
<li class="chapter" data-level="4.5.2" data-path="amostragem.html"><a href="amostragem.html#proporção"><i class="fa fa-check"></i><b>4.5.2</b> Proporção</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="amostragem.html"><a href="amostragem.html#para-saber-mais"><i class="fa fa-check"></i><b>4.6</b> Para saber mais</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="inferencia-classica.html"><a href="inferencia-classica.html"><i class="fa fa-check"></i><b>5</b> Inferência Clássica</a>
<ul>
<li class="chapter" data-level="5.1" data-path="inferencia-classica.html"><a href="inferencia-classica.html#estimação-pontual"><i class="fa fa-check"></i><b>5.1</b> Estimação Pontual</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="inferencia-classica.html"><a href="inferencia-classica.html#estimadores-e-suas-propriedades"><i class="fa fa-check"></i><b>5.1.1</b> Estimadores e suas propriedades</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="inferencia-classica.html"><a href="inferencia-classica.html#estimação-por-intervalo-de-confiança"><i class="fa fa-check"></i><b>5.2</b> (Estimação por) Intervalo de Confiança</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="inferencia-classica.html"><a href="inferencia-classica.html#média-1"><i class="fa fa-check"></i><b>5.2.1</b> Média</a></li>
<li class="chapter" data-level="5.2.2" data-path="inferencia-classica.html"><a href="inferencia-classica.html#proporção-1"><i class="fa fa-check"></i><b>5.2.2</b> Proporção</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="inferencia-classica.html"><a href="inferencia-classica.html#estimação-por-teste-de-hipóteses"><i class="fa fa-check"></i><b>5.3</b> (Estimação por) Teste de Hipóteses</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="inferencia-classica.html"><a href="inferencia-classica.html#testes-paramétricos-univariados"><i class="fa fa-check"></i><b>5.3.1</b> Testes Paramétricos Univariados</a></li>
<li class="chapter" data-level="5.3.2" data-path="inferencia-classica.html"><a href="inferencia-classica.html#testes-paramétricos-bivariados"><i class="fa fa-check"></i><b>5.3.2</b> Testes Paramétricos Bivariados</a></li>
<li class="chapter" data-level="5.3.3" data-path="inferencia-classica.html"><a href="inferencia-classica.html#testes-paramétricos-multivariados"><i class="fa fa-check"></i><b>5.3.3</b> Testes Paramétricos Multivariados</a></li>
<li class="chapter" data-level="5.3.4" data-path="inferencia-classica.html"><a href="inferencia-classica.html#testes-não-paramétricos-univariados"><i class="fa fa-check"></i><b>5.3.4</b> Testes Não Paramétricos Univariados</a></li>
<li class="chapter" data-level="5.3.5" data-path="inferencia-classica.html"><a href="inferencia-classica.html#testes-não-paramétricos-bivariados"><i class="fa fa-check"></i><b>5.3.5</b> Testes Não Paramétricos Bivariados</a></li>
<li class="chapter" data-level="5.3.6" data-path="inferencia-classica.html"><a href="inferencia-classica.html#testes-não-paramétricos-multivariados"><i class="fa fa-check"></i><b>5.3.6</b> Testes Não Paramétricos Multivariados</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="inferencia-classica.html"><a href="inferencia-classica.html#exercícios"><i class="fa fa-check"></i><b>5.4</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="inferencia-bayesiana.html"><a href="inferencia-bayesiana.html"><i class="fa fa-check"></i><b>6</b> Inferência Bayesiana</a>
<ul>
<li class="chapter" data-level="6.1" data-path="inferencia-bayesiana.html"><a href="inferencia-bayesiana.html#princípios-de-verossimilhança-suficiência-e-condicionalidade"><i class="fa fa-check"></i><b>6.1</b> Princípios de verossimilhança, suficiência e condicionalidade</a></li>
<li class="chapter" data-level="6.2" data-path="inferencia-bayesiana.html"><a href="inferencia-bayesiana.html#distribuição-a-priori"><i class="fa fa-check"></i><b>6.2</b> Distribuição a priori</a></li>
<li class="chapter" data-level="6.3" data-path="inferencia-bayesiana.html"><a href="inferencia-bayesiana.html#estimação-pontual-1"><i class="fa fa-check"></i><b>6.3</b> Estimação Pontual</a></li>
<li class="chapter" data-level="6.4" data-path="inferencia-bayesiana.html"><a href="inferencia-bayesiana.html#estimação-por-intervaloregiões-de-credibilidade"><i class="fa fa-check"></i><b>6.4</b> (Estimação por) Intervalo/Regiões de Credibilidade</a></li>
<li class="chapter" data-level="6.5" data-path="inferencia-bayesiana.html"><a href="inferencia-bayesiana.html#estimação-por-teste-de-hipóteses-1"><i class="fa fa-check"></i><b>6.5</b> (Estimação por) Teste de Hipóteses</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="inferencia-bayesiana.html"><a href="inferencia-bayesiana.html#fatores-de-bayes"><i class="fa fa-check"></i><b>6.5.1</b> Fatores de Bayes</a></li>
<li class="chapter" data-level="6.5.2" data-path="inferencia-bayesiana.html"><a href="inferencia-bayesiana.html#fbst---full-bayesian-significance-test"><i class="fa fa-check"></i><b>6.5.2</b> FBST - <em>Full Bayesian Significance Test</em></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="modelos-lineares.html"><a href="modelos-lineares.html"><i class="fa fa-check"></i><b>7</b> Modelos Lineares</a>
<ul>
<li class="chapter" data-level="7.1" data-path="modelos-lineares.html"><a href="modelos-lineares.html#correlacao"><i class="fa fa-check"></i><b>7.1</b> Correlação</a></li>
<li class="chapter" data-level="7.2" data-path="modelos-lineares.html"><a href="modelos-lineares.html#regressão-linear-simples"><i class="fa fa-check"></i><b>7.2</b> Regressão Linear Simples</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="modelos-lineares.html"><a href="modelos-lineares.html#modelo"><i class="fa fa-check"></i><b>7.2.1</b> Modelo</a></li>
<li class="chapter" data-level="7.2.2" data-path="modelos-lineares.html"><a href="modelos-lineares.html#estimativas-dos-parâmetros"><i class="fa fa-check"></i><b>7.2.2</b> Estimativas dos parâmetros</a></li>
<li class="chapter" data-level="7.2.3" data-path="modelos-lineares.html"><a href="modelos-lineares.html#análise-de-diagnóstico"><i class="fa fa-check"></i><b>7.2.3</b> Análise de diagnóstico</a></li>
<li class="chapter" data-level="7.2.4" data-path="modelos-lineares.html"><a href="modelos-lineares.html#modelo-rpo"><i class="fa fa-check"></i><b>7.2.4</b> Modelo RPO</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="modelos-lineares.html"><a href="modelos-lineares.html#regressão-linear-múltipla"><i class="fa fa-check"></i><b>7.3</b> Regressão Linear Múltipla</a></li>
<li class="chapter" data-level="7.4" data-path="modelos-lineares.html"><a href="modelos-lineares.html#regressão-logística"><i class="fa fa-check"></i><b>7.4</b> Regressão Logística</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="modelos-lineares.html"><a href="modelos-lineares.html#variáveis-bináriasdicotômicas"><i class="fa fa-check"></i><b>7.4.1</b> Variáveis binárias/dicotômicas</a></li>
<li class="chapter" data-level="7.4.2" data-path="modelos-lineares.html"><a href="modelos-lineares.html#o-modelo-de-regressão-logística"><i class="fa fa-check"></i><b>7.4.2</b> O modelo de regressão logística</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="aprendizadodemaquina.html"><a href="aprendizadodemaquina.html"><i class="fa fa-check"></i><b>8</b> Aprendizado de Máquina</a>
<ul>
<li class="chapter" data-level="8.1" data-path="aprendizadodemaquina.html"><a href="aprendizadodemaquina.html#análise-de-componentes-principais-pca"><i class="fa fa-check"></i><b>8.1</b> Análise de Componentes Principais (<em>PCA</em>)</a></li>
<li class="chapter" data-level="8.2" data-path="aprendizadodemaquina.html"><a href="aprendizadodemaquina.html#técnicas-de-agrupamento"><i class="fa fa-check"></i><b>8.2</b> Técnicas de Agrupamento</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="aprendizadodemaquina.html"><a href="aprendizadodemaquina.html#medidas-de-similaridade-e-dissimilaridade"><i class="fa fa-check"></i><b>8.2.1</b> Medidas de similaridade e dissimilaridade</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="aprendizadodemaquina.html"><a href="aprendizadodemaquina.html#métodos-hierárquicos"><i class="fa fa-check"></i><b>8.3</b> Métodos hierárquicos</a></li>
<li class="chapter" data-level="8.4" data-path="aprendizadodemaquina.html"><a href="aprendizadodemaquina.html#métodos-não-hierárquicos-de-particionamento"><i class="fa fa-check"></i><b>8.4</b> Métodos não hierárquicos (de particionamento)</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="aprendizadodemaquina.html"><a href="aprendizadodemaquina.html#k-médias"><i class="fa fa-check"></i><b>8.4.1</b> K-médias</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="seriestemporais.html"><a href="seriestemporais.html"><i class="fa fa-check"></i><b>9</b> Séries Temporais</a>
<ul>
<li class="chapter" data-level="9.1" data-path="seriestemporais.html"><a href="seriestemporais.html#impacto-causal"><i class="fa fa-check"></i><b>9.1</b> Impacto Causal</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="referências.html"><a href="referências.html"><i class="fa fa-check"></i><b>10</b> Referências</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Fundamentos de Estatística para Ciência de Dados</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="modelos-lineares" class="section level1" number="7">
<h1><span class="header-section-number">7</span> Modelos Lineares</h1>
<p>A classe de <em>Modelos Lineares</em> atende a uma ampla gama de problemas aplicados, apresentada em profundidade por <span class="citation">(Neter et al. <a href="#ref-neter2005applied" role="doc-biblioref">2005</a>)</span>. Para uma introdução à classe de <em>Modelos Lineares Generalizados</em> recomenda-se <span class="citation">(McCullagh and Nelder <a href="#ref-mccullagh1989generalized" role="doc-biblioref">1989</a>)</span>.</p>
<div id="correlacao" class="section level2" number="7.1">
<h2><span class="header-section-number">7.1</span> Correlação</h2>
<!-- ## Coeficiente de correlação (produto-momento) de Pearson -->
<!-- p. 1249 -->
<!-- ```{definition} -->
<!-- *Correlação* é o grau de associação linear entre duas variáves.  $\\$ -->
<!-- ``` -->
<!-- ## Coeficiente de correlação ordinal de Spearman -->
<!-- p. 1365 -->
<!-- ## Tau de Kendall??? -->
<!-- p. 1383 -->
<!-- ## Coeficiente de concordância de Kendall??? -->
<!-- p.1399 -->
</div>
<div id="regressão-linear-simples" class="section level2" number="7.2">
<h2><span class="header-section-number">7.2</span> Regressão Linear Simples</h2>
<div id="modelo" class="section level3" number="7.2.1">
<h3><span class="header-section-number">7.2.1</span> Modelo</h3>
<p>O modelo de <em>Regressão Linear Simples</em> universal/populacional é construído, pela abordagem clássica, com todos os <span class="math inline">\(N\)</span> pares ordenados do universo, e pode ser descrito pela relação a seguir.</p>
<p><span class="math display" id="eq:rls">\[\begin{equation}
Y_i = \beta_0 + \beta_1 X_i + \varepsilon_i,
\tag{7.1}
\end{equation}\]</span>
onde <span class="math inline">\(\varepsilon_i \sim \mathcal{N}(0,\sigma_{\varepsilon})\)</span>.</p>
<p>Na maioria dos casos práticos trabalha-se com amostras, sendo necessário estimar os valores de <span class="math inline">\(\beta_0\)</span> e <span class="math inline">\(\beta_1\)</span>. O método dos <em>mínimos quadrados (ordinários)</em> é utilizado para calcular estas estimativas. O princípio do método é minimizar a soma de quadrado dos erros, i.e.,
<span class="math display" id="eq:mqo">\[\begin{equation}
minimizar \sum_{i=1}^n \varepsilon_{i}^{2}.
\tag{7.2}
\end{equation}\]</span></p>
</div>
<div id="estimativas-dos-parâmetros" class="section level3" number="7.2.2">
<h3><span class="header-section-number">7.2.2</span> Estimativas dos parâmetros</h3>
<p>Basicamente utiliza-se <span class="math inline">\(\varepsilon_{i} = Y_{i} - \beta_0 - \beta_1 X_i\)</span> da Eq. <a href="modelos-lineares.html#eq:rls">(7.1)</a> e deriva-se (parcialmente) em relação a <span class="math inline">\(\beta_0\)</span> e <span class="math inline">\(\beta_1\)</span>, fazendo cada uma das derivadas parciais igual a zero. Para maiores detalhes recomenda-se <span class="citation">(DeGroot and Schervish <a href="#ref-degroot2012probability" role="doc-biblioref">2012</a>)</span>. As estimativas por mínimos quadrados são enfim dadas por
<span class="math display" id="eq:beta1">\[\begin{equation}
\hat{\beta}_1 = \frac{n \sum{x_i y_i} - \sum{x_i} \sum{y_i}}{n \sum{x_i^2} - (\sum{x_i})^2} 
\tag{7.3}
\end{equation}\]</span>
e
<span class="math display" id="eq:beta0">\[\begin{equation}
\hat{\beta}_0 = \bar{y} - \hat{\beta}_1 \bar{x}.
\tag{7.4}
\end{equation}\]</span></p>
</div>
<div id="análise-de-diagnóstico" class="section level3" number="7.2.3">
<h3><span class="header-section-number">7.2.3</span> Análise de diagnóstico</h3>
<div id="teste-para-beta_0" class="section level4 unnumbered" number="">
<h4>Teste para <span class="math inline">\(\beta_0\)</span></h4>
<p>As hipóteses usuais do teste para <span class="math inline">\(\beta_0\)</span> são <span class="math inline">\(H_0: \beta_0 = 0\)</span> <em>vs</em> <span class="math inline">\(H_1: \beta_0 \ne 0\)</span>. Sob <span class="math inline">\(H_0\)</span>
<span class="math display">\[\begin{equation}
T_0 = \frac{\hat{\beta}_0}{ep(\hat{\beta}_0)} \sim t_{n-2},
(\#eq:teste_b0)
\end{equation}\]</span>
onde
<span class="math display">\[\begin{equation}
ep(\hat{\beta}_0) = \sqrt{\hat{\sigma}^2 \left[ \frac{1}{n} + \frac{\bar{x}^2}{S_{xx}} \right] } = \sqrt{\frac{\sum_{i=i}^n (y_i - \hat{y}_i)^2}{n-2} \left[ \frac{1}{n} + \frac{\bar{x}^2}{\sum_{i=i}^n (x_i - \bar{x})^2} \right] }.
(\#eq:ep_b0)
\end{equation}\]</span></p>
</div>
<div id="teste-para-beta_1" class="section level4 unnumbered" number="">
<h4>Teste para <span class="math inline">\(\beta_1\)</span></h4>
<p>O teste para <span class="math inline">\(\beta_1\)</span> é fundamental na análise de diagnóstico. É com ele que decide-se a respeito da presença ou ausência de relação linear entre <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span>. As hipóteses usuais do teste para <span class="math inline">\(\beta_1\)</span> são <span class="math inline">\(H_0: \beta_1 = 0\)</span> <em>vs</em> <span class="math inline">\(H_1: \beta_1 \ne 0\)</span>. Sob <span class="math inline">\(H_0\)</span>
<span class="math display" id="eq:t1">\[\begin{equation}
T_1 = \frac{\hat{\beta}_1}{ep(\hat{\beta}_1)} \sim t_{n-2},
\tag{7.5}
\end{equation}\]</span>
onde
<span class="math display">\[\begin{equation}
ep(\hat{\beta}_1) = \sqrt{\frac{\hat{\sigma}^2}{S_{xx}}} = \sqrt{\frac{\sum_{i=i}^n (y_i - \hat{y}_i)^2 / (n-2)}{\sum_{i=i}^n (x_i - \bar{x})^2} }.
(\#eq:ep_t1)
\end{equation}\]</span></p>
</div>
</div>
<div id="modelo-rpo" class="section level3" number="7.2.4">
<h3><span class="header-section-number">7.2.4</span> Modelo RPO</h3>
<p>Um modelo na forma da Eq. <a href="modelos-lineares.html#eq:rls0">(7.6)</a> é chamado <em>regressão pela origem</em> pelo fato de a reta ajustada passar pelo ponto <span class="math inline">\((0,0)\)</span>, a <em>origem</em> do plano cartesiano.
<span class="math display" id="eq:rls0">\[\begin{equation}
Y_i = \beta_1 X_i + \varepsilon_i,
\tag{7.6}
\end{equation}\]</span>
onde <span class="math inline">\(\varepsilon_i \sim \mathcal{N}(0,\sigma_{\varepsilon})\)</span>. A estimativa do parâmetro <span class="math inline">\(\beta_1\)</span> é dada por
<span class="math display">\[\begin{equation}
\hat{\beta}_1 = \frac{\sum{x_i y_i} }{\sum{x_i^2} }.
(\#eq:beta1_rpo)
\end{equation}\]</span></p>
<div id="teste-para-beta_1-do-modelo-rpo" class="section level4 unnumbered" number="">
<h4>Teste para <span class="math inline">\(\beta_1\)</span> do modelo RPO</h4>
<p><span class="math display">\[\begin{equation}
T_1^{RPO} = \frac{\hat{\beta}_1}{ep(\hat{\beta}_1)} \sim t_{n-1},
(\#eq:teste_beta1_rpo)
\end{equation}\]</span>
onde
<span class="math display">\[\begin{equation}
ep(\hat{\beta}_1) = \sqrt{\frac{\hat{\sigma}^2}{S_{xx}}} = \sqrt{\frac{\sum_{i=i}^n (y_i - \hat{y}_i)^2 / (n-1)}{\sum_{i=i}^n x_{i}^{2} } }.
(\#eq:ep_beta1_rpo)
\end{equation}\]</span></p>

<div class="example">
<span id="exm:unnamed-chunk-125" class="example"><strong>Example 7.1  </strong></span>O dono de um bar decidiu modelar o número de garrafas de bebidas vendidas em seu estabelecimento (<span class="math inline">\(Y\)</span>) em função da temperatura máxima do dia (<span class="math inline">\(X\)</span>).
</div>
<div class="sourceCode" id="cb583"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb583-1"><a href="modelos-lineares.html#cb583-1"></a>x &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&#39;http://www.filipezabala.com/data/drinks.txt&#39;</span>, <span class="dt">header =</span> T, <span class="dt">sep =</span> <span class="st">&#39;</span><span class="ch">\t</span><span class="st">&#39;</span>)</span>
<span id="cb583-2"><a href="modelos-lineares.html#cb583-2"></a><span class="kw">dim</span>(x)  <span class="co"># dimensão de x</span></span></code></pre></div>
<pre><code>## [1] 30  2</code></pre>
<div class="sourceCode" id="cb585"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb585-1"><a href="modelos-lineares.html#cb585-1"></a><span class="kw">head</span>(x) <span class="co"># cabeçalho de x</span></span></code></pre></div>
<pre><code>##   temp gar
## 1 29.5 145
## 2 31.3 170
## 3 34.7 167
## 4 40.4 244
## 5 28.4 159
## 6 40.3 195</code></pre>
<div class="sourceCode" id="cb587"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb587-1"><a href="modelos-lineares.html#cb587-1"></a>fit &lt;-<span class="st"> </span><span class="kw">lm</span>(gar <span class="op">~</span><span class="st"> </span>temp, <span class="dt">data =</span> x)       <span class="co"># regressão linear simples</span></span>
<span id="cb587-2"><a href="modelos-lineares.html#cb587-2"></a><span class="kw">summary</span>(fit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = gar ~ temp, data = x)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -44.16  -8.96   3.58  10.81  33.60 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -19.334     22.944   -0.84     0.41    
## temp           5.920      0.674    8.78  1.6e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 18.3 on 28 degrees of freedom
## Multiple R-squared:  0.734,  Adjusted R-squared:  0.724 
## F-statistic: 77.1 on 1 and 28 DF,  p-value: 1.57e-09</code></pre>
<div class="sourceCode" id="cb589"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb589-1"><a href="modelos-lineares.html#cb589-1"></a>fit0 &lt;-<span class="st"> </span><span class="kw">lm</span>(gar <span class="op">~</span><span class="st"> </span>temp <span class="op">-</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> x)  <span class="co"># regressão pela origem</span></span>
<span id="cb589-2"><a href="modelos-lineares.html#cb589-2"></a><span class="kw">summary</span>(fit0)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = gar ~ temp - 1, data = x)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -45.78 -11.26   3.53  12.01  30.29 
## 
## Coefficients:
##      Estimate Std. Error t value Pr(&gt;|t|)    
## temp   5.3582     0.0975      55   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 18.2 on 29 degrees of freedom
## Multiple R-squared:  0.99,   Adjusted R-squared:  0.99 
## F-statistic: 3.02e+03 on 1 and 29 DF,  p-value: &lt;2e-16</code></pre>

<div class="exercise">
<span id="exr:unnamed-chunk-127" class="exercise"><strong>Exercise 7.1  </strong></span>Considere o Exemplo 5.1.<br />
(a) Indique os valores de <span class="math inline">\(n\)</span> e <span class="math inline">\(p\)</span>.<br />
(b) No modelo de regressão linear simples atribuído a <code>fit</code>, indique os números das equações para o cálculo das medidas <code>Estimate</code>, <code>Std. Error</code> e <code>t value</code>.<br />
(c) Utilizado a linguagem R, aplique as equações indicadas no item (b) de forma a obter os valores indicados em <code>summary(fit)</code>.<br />
(d) No modelo de regressão pela origem atribuído a <code>fit0</code>, indique os números das equações para o cálculo das medidas <code>Estimate</code>, <code>Std. Error</code> e <code>t value</code>.<br />
(e) Utilizado a linguagem R, aplique as equações indicadas no item (d) de forma a obter os valores indicados em <code>summary(fit0)</code>.<br />
(f) Qual o modelo mais indicado segundo a sua análise? Justifique.
</div>
</div>
</div>
</div>
<div id="regressão-linear-múltipla" class="section level2" number="7.3">
<h2><span class="header-section-number">7.3</span> Regressão Linear Múltipla</h2>
<p>O modelo de <em>regressão linear múltipla</em> universal/populacional é construído, pela abordagem clássica, com todos os <span class="math inline">\(N\)</span> pares ordenados do universo, e pode ser descrito pela relação a seguir.</p>
<p><span class="math display" id="eq:rlm">\[\begin{equation}
Y_i = \beta_0 + \beta_1 X_{i1} + \beta_2 X_{i2} + \cdots + \beta_p X_{ip} + \varepsilon_i,
\tag{7.7}
\end{equation}\]</span>
<span class="math inline">\(\varepsilon_i \sim \mathcal{N}(0,\sigma_{\varepsilon})\)</span>. Por ter dimensionalidade <span class="math inline">\(p\)</span> usualmente utiliza-se notação matricial na forma</p>
<p><span class="math display" id="eq:rlm2">\[\begin{equation}
\boldsymbol{Y} = \boldsymbol{X} \boldsymbol{\beta} + \boldsymbol{\varepsilon},
\tag{7.8}
\end{equation}\]</span>
onde <span class="math inline">\(\boldsymbol{Y} = \begin{bmatrix} Y_1 \\ Y_2 \\ \vdots \\ Y_n \end{bmatrix}\)</span>, <span class="math inline">\(\boldsymbol{X} = \begin{bmatrix} 1 &amp; X_{11} &amp; X_{12} &amp; \cdots &amp; X_{1p} \\ 1 &amp; X_{21} &amp; X_{22} &amp; \cdots &amp; X_{2p} \\ \vdots &amp; \vdots &amp; \vdots &amp; \ddots &amp; \vdots \\ 1 &amp; X_{n1} &amp; X_{n2} &amp; \cdots &amp; X_{np} \end{bmatrix}\)</span>, <span class="math inline">\(\boldsymbol{\beta} = \begin{bmatrix} \beta_1 \\ \beta_2 \\ \vdots \\ \beta_n \end{bmatrix}\)</span> e <span class="math inline">\(\boldsymbol{\varepsilon} = \begin{bmatrix} \varepsilon_1 \\ \varepsilon_2 \\ \vdots \\ \varepsilon_n \end{bmatrix}\)</span>.</p>
<p>Para a obtenção das estimativas dos parâmetros utiliza-se a Eq. <a href="modelos-lineares.html#eq:beta">(7.9)</a>.
<span class="math display" id="eq:beta">\[\begin{equation}
\boldsymbol{\hat{\beta}} = (\boldsymbol{X&#39;X})^{-1} (\boldsymbol{X&#39;X}) \boldsymbol{Y}
\tag{7.9}
\end{equation}\]</span></p>

<div class="example">
<p><span id="exm:unnamed-chunk-128" class="example"><strong>Example 7.2  </strong></span>No site <a href="http://archive.ics.uci.edu/ml/datasets/Energy+efficiency" class="uri">http://archive.ics.uci.edu/ml/datasets/Energy+efficiency</a> está disponível uma análise de energia feita por <span class="citation">(Tsanas and Xifara <a href="#ref-tsanas2012accurate" role="doc-biblioref">2012</a>)</span> usando 12 formas diferentes de construção simuladas no <a href="https://en.wikipedia.org/wiki/Autodesk_Ecotect_Analysis">Ecotect</a>. Os edifícios diferem em relação à área envidraçada, à distribuição da área envidraçada e à orientação, entre outros parâmetros. Foram simuladas várias configurações como funções das características acima mencionadas para obter 768 formas de construção. O conjunto de dados detalhado a seguir compreende 768 amostras e 8 características (<code>X1</code> a <code>X8</code>), com o objetivo de prever duas respostas reais (<code>Y1</code> e <code>Y2</code>).</p>
<code>X1</code>: Compactação Relativa<br />
<code>X2</code>: Superfície<br />
<code>X3</code>: Área da parede<br />
<code>X4</code>: Área do telhado<br />
<code>X5</code>: Altura total<br />
<code>X6</code>: Orientação<br />
<code>X7</code>: Área de Envidraçamento<br />
<code>X8</code>: Distribuição da Área de Envidraçamento<br />
<code>Y1</code>: Carga de aquecimento<br />
<code>Y2</code>: Carga de resfriamento
</div>
<div class="sourceCode" id="cb591"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb591-1"><a href="modelos-lineares.html#cb591-1"></a><span class="kw">library</span>(readxl)</span>
<span id="cb591-2"><a href="modelos-lineares.html#cb591-2"></a>url1 &lt;-<span class="st"> &#39;http://archive.ics.uci.edu/ml/machine-learning-databases/00242/ENB2012_data.xlsx&#39;</span></span>
<span id="cb591-3"><a href="modelos-lineares.html#cb591-3"></a><span class="kw">download.file</span>(url1, <span class="st">&#39;temp.xlsx&#39;</span>, <span class="dt">mode =</span> <span class="st">&#39;wb&#39;</span>)</span>
<span id="cb591-4"><a href="modelos-lineares.html#cb591-4"></a>energy &lt;-<span class="st"> </span><span class="kw">read_excel</span>(<span class="st">&#39;temp.xlsx&#39;</span>)</span>
<span id="cb591-5"><a href="modelos-lineares.html#cb591-5"></a><span class="kw">str</span>(energy)   <span class="co"># dando uma olhada nas variáveis</span></span></code></pre></div>
<pre><code>## tibble [768 × 10] (S3: tbl_df/tbl/data.frame)
##  $ X1: num [1:768] 0.98 0.98 0.98 0.98 0.9 0.9 0.9 0.9 0.86 0.86 ...
##  $ X2: num [1:768] 514 514 514 514 564 ...
##  $ X3: num [1:768] 294 294 294 294 318 ...
##  $ X4: num [1:768] 110 110 110 110 122 ...
##  $ X5: num [1:768] 7 7 7 7 7 7 7 7 7 7 ...
##  $ X6: num [1:768] 2 3 4 5 2 3 4 5 2 3 ...
##  $ X7: num [1:768] 0 0 0 0 0 0 0 0 0 0 ...
##  $ X8: num [1:768] 0 0 0 0 0 0 0 0 0 0 ...
##  $ Y1: num [1:768] 15.6 15.6 15.6 15.6 20.8 ...
##  $ Y2: num [1:768] 21.3 21.3 21.3 21.3 28.3 ...</code></pre>
<div class="sourceCode" id="cb593"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb593-1"><a href="modelos-lineares.html#cb593-1"></a><span class="kw">pairs</span>(energy) <span class="co"># matriz de dispersão</span></span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-129-1.png" width="672" /></p>
<div class="sourceCode" id="cb594"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb594-1"><a href="modelos-lineares.html#cb594-1"></a>fit0 &lt;-<span class="st"> </span><span class="kw">lm</span>(Y1 <span class="op">~</span><span class="st"> </span>X1 <span class="op">+</span><span class="st"> </span>X2 <span class="op">+</span><span class="st"> </span>X3 <span class="op">+</span><span class="st"> </span>X4 <span class="op">+</span><span class="st"> </span>X5 <span class="op">+</span><span class="st"> </span>X6 <span class="op">+</span><span class="st"> </span>X7 <span class="op">+</span><span class="st"> </span>X8, <span class="dt">data =</span> energy) <span class="co"># modelo saturado</span></span>
<span id="cb594-2"><a href="modelos-lineares.html#cb594-2"></a><span class="kw">summary</span>(fit0)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Y1 ~ X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8, data = energy)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -9.897 -1.320 -0.025  1.353  7.705 
## 
## Coefficients: (1 not defined because of singularities)
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  84.01342   19.03361    4.41  1.2e-05 ***
## X1          -64.77343   10.28945   -6.30  5.2e-10 ***
## X2           -0.08729    0.01708   -5.11  4.0e-07 ***
## X3            0.06081    0.00665    9.15  &lt; 2e-16 ***
## X4                 NA         NA      NA       NA    
## X5            4.16995    0.33799   12.34  &lt; 2e-16 ***
## X6           -0.02333    0.09470   -0.25   0.8055    
## X7           19.93274    0.81399   24.49  &lt; 2e-16 ***
## X8            0.20378    0.06992    2.91   0.0037 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.93 on 760 degrees of freedom
## Multiple R-squared:  0.916,  Adjusted R-squared:  0.915 
## F-statistic: 1.19e+03 on 7 and 760 DF,  p-value: &lt;2e-16</code></pre>
<div class="sourceCode" id="cb596"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb596-1"><a href="modelos-lineares.html#cb596-1"></a>fit1 &lt;-<span class="st"> </span><span class="kw">step</span>(fit0)  <span class="co"># filtrando as variáveis com stepwise</span></span></code></pre></div>
<pre><code>## Start:  AIC=1661
## Y1 ~ X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8
## 
## 
## Step:  AIC=1661
## Y1 ~ X1 + X2 + X3 + X5 + X6 + X7 + X8
## 
##        Df Sum of Sq   RSS  AIC
## - X6    1         1  6544 1659
## &lt;none&gt;               6544 1661
## - X8    1        73  6617 1668
## - X2    1       225  6769 1685
## - X1    1       341  6885 1698
## - X3    1       721  7264 1740
## - X5    1      1311  7854 1800
## - X7    1      5163 11707 2106
## 
## Step:  AIC=1659
## Y1 ~ X1 + X2 + X3 + X5 + X7 + X8
## 
##        Df Sum of Sq   RSS  AIC
## &lt;none&gt;               6544 1659
## - X8    1        73  6617 1666
## - X2    1       225  6769 1683
## - X1    1       341  6886 1697
## - X3    1       721  7265 1738
## - X5    1      1311  7855 1798
## - X7    1      5163 11707 2104</code></pre>
<div class="sourceCode" id="cb598"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb598-1"><a href="modelos-lineares.html#cb598-1"></a><span class="kw">summary</span>(fit1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Y1 ~ X1 + X2 + X3 + X5 + X7 + X8, data = energy)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -9.931 -1.319 -0.026  1.359  7.717 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  83.93176   19.01898    4.41  1.2e-05 ***
## X1          -64.77343   10.28310   -6.30  5.1e-10 ***
## X2           -0.08729    0.01706   -5.12  4.0e-07 ***
## X3            0.06081    0.00664    9.15  &lt; 2e-16 ***
## X5            4.16995    0.33778   12.35  &lt; 2e-16 ***
## X7           19.93274    0.81348   24.50  &lt; 2e-16 ***
## X8            0.20378    0.06987    2.92   0.0036 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.93 on 761 degrees of freedom
## Multiple R-squared:  0.916,  Adjusted R-squared:  0.916 
## F-statistic: 1.39e+03 on 6 and 761 DF,  p-value: &lt;2e-16</code></pre>
<p>Após o primeiro ajuste atribuído a <code>fit0</code> é possível notar que o coeficiente da variável <code>X4</code> não é possível de ser calculado devido a singularidades, i.e, impossibilidade de inversão das matrizes do modelo. Sendo assim, ao modelo saturado (contendo todas as variáveis candidatas) aplicou-se o método de <em>stepwise</em>, proposto por <span class="citation">(Efroymson <a href="#ref-efroymson1960multiple" role="doc-biblioref">1960</a>)</span> e utilizado para selecionar variáveis. Este método busca automaticamente o melhor conjunto de variáveis de maneira a minimizar alguma medida, usualmente o <em>Critério de Informação de Akaike</em> (AIC, na sigla em inglês), sugerido por <span class="citation">(Akaike <a href="#ref-akaike1974new" role="doc-biblioref">1974</a>)</span>. De acordo com a métrica do stepwise, quanto menor o valor de AIC, melhor a combinação das variáveis.</p>
<p>Pelos resultados obtidos pode-se verificar que o modelo ajustado em <code>fit1</code> possui todas as variávies significativas para um <span class="math inline">\(\alpha\)</span> inferior a 0.01, estatística F de 1387 para 6 e 761 graus de liberdade, levando a um p-value geral do modelo menor que <span class="math inline">\(2.2 \times 10^{-16}\)</span>, o que indica boa aderência aos dados. O valor do <code>Multiple R-squared</code> é de 0.9162, indicando que o modelo explica em torno de 92% da variação de <code>Y1</code>. Desta forma este é um modelo aceitável, que possui coeficientes de <code>X1</code> e <code>X2</code> negativos, indicando que um aumento destas variáveis (respectivamente compactação relativa e superfície) deve reduzir a carga de aquecimento. Mais especificamente, um aumento de uma unidade na compactação relativa (<code>X1</code>) gera uma redução esperada de 64.77 unidades na carga de aquecimento, mantidas constantes as demais variáveis. As variáveis <code>X3</code>, <code>X5</code>, <code>X7</code> e <code>X8</code> possuem coeficientes positivos, levando a um impacto esperado positivo em <code>Y1</code>. Como exemplo, para cada aumento de uma unidade na altura total (<code>X5</code>) espera-se um aumento aproximando de 4.17 unidades na carga de aquecimento. As outras variáveis possuem interpretação análoga, devendo-se sempre observar o sinal dos coeficientes.</p>

<div class="exercise">
<span id="exr:unnamed-chunk-130" class="exercise"><strong>Exercise 7.2  </strong></span>Refaça o Exemplo 5.2 utilizando a variável <code>Y2</code> como resposta, ajustando o modelo saturado, filtrando as variáveis com a função <code>step</code> e interpretando os resultados.
</div>
<!-- Note que boa parte dos testes de hipóteses podem ser escritos como modelos de regressão. Veja o link https://lindeloev.github.io/tests-as-linear/ para maiores detalhes. -->
</div>
<div id="regressão-logística" class="section level2" number="7.4">
<h2><span class="header-section-number">7.4</span> Regressão Logística</h2>
<div id="variáveis-bináriasdicotômicas" class="section level3" number="7.4.1">
<h3><span class="header-section-number">7.4.1</span> Variáveis binárias/dicotômicas</h3>
<p>Em problemas aplicados é comum fazer uso de variáveis aleatórias que admitam apenas dois valores, chamadas v.a. <em>binárias</em> ou <em>dicotômicas</em>. Empresas de serviços financeiros podem estar interessados em clientes adimplentes/inadimpletes, hospitais em pacientes com/sem melhora, cientistas da computação em servidores operantes/inoperantes, etc. Começamos com um exemplo numérico para ilustrar.</p>

<div class="example">
<span id="exm:unnamed-chunk-131" class="example"><strong>Example 7.3  </strong></span>Um banco está interessado na variável aleatória <span class="math inline">\(Y\)</span>: cliente inadimplente. Ela assume valor 1 se o cliente é inadimplente (sucesso) e 0 caso contrário (fracasso). Note que a terminologia sucesso/fracasso indica se a variável <span class="math inline">\(Y\)</span> foi observada (1) ou não (0), ainda que ‘sucesso’ possa não significar algo agradável.<br />
Se considerarmos 40 clientes, 20 inadimplentes e 20 adimplentes, pode-se calcular a probabilidade (incondicional) de observar um ciente inadimplente (sucesso) por <span class="math inline">\(Pr(Y=1)=\frac{20}{40}=0.5\)</span>. Da mesma forma, a probabilidade (incondicional) de observar um ciente adimplente (fracasso) é dada por <span class="math inline">\(Pr(Y=0)=\frac{20}{40}=0.5\)</span>. Utilizando a linguagem R pode-se gerar a sequência de zeros e uns descrita acima, bem como as respectivas probabilidades.
</div>
<div class="sourceCode" id="cb600"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb600-1"><a href="modelos-lineares.html#cb600-1"></a>n &lt;-<span class="st"> </span><span class="dv">20</span></span>
<span id="cb600-2"><a href="modelos-lineares.html#cb600-2"></a>(y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">rep</span>(<span class="dv">0</span>,n), <span class="kw">rep</span>(<span class="dv">1</span>,n)))</span></code></pre></div>
<pre><code>##  [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1</code></pre>
<div class="sourceCode" id="cb602"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb602-1"><a href="modelos-lineares.html#cb602-1"></a>(taby &lt;-<span class="st"> </span><span class="kw">table</span>(y))</span></code></pre></div>
<pre><code>## y
##  0  1 
## 20 20</code></pre>
<div class="sourceCode" id="cb604"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb604-1"><a href="modelos-lineares.html#cb604-1"></a><span class="kw">prop.table</span>(taby)</span></code></pre></div>
<pre><code>## y
##   0   1 
## 0.5 0.5</code></pre>
<p>Vendo a questão desta maneira pode-se considerar que a probablidade de um cliente ser inadimplente é de 50%. É possível, porém, considerar outras variáveis para refinar esta probabilidade. Suponha uma variável <span class="math inline">\(X_1\)</span>, que ocorre em aproximadamente 20% dos clientes adimplentes (<span class="math inline">\(Y=0\)</span>) e em aproximadamente 90% dos clientes inadimplentes (<span class="math inline">\(Y=1\)</span>). Assim, visto que presença da variável <span class="math inline">\(X_1\)</span> é maior entre os inadimplentes, intuitivamente devemos atribuir uma probabilidade maior de inadimplência a clientes que apresentem a característica <span class="math inline">\(X_1\)</span>, e menor para aquele onde a característica <span class="math inline">\(X_1\)</span> é ausente. Novamente podemos fazer uso da linguagem R para gerar sequências similares àquelas consideradas na teoria.</p>
<div class="sourceCode" id="cb606"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb606-1"><a href="modelos-lineares.html#cb606-1"></a><span class="kw">suppressMessages</span>(<span class="kw">library</span>(tidyverse))</span>
<span id="cb606-2"><a href="modelos-lineares.html#cb606-2"></a><span class="kw">set.seed</span>(<span class="dv">1</span>); (x1 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">rbinom</span>(n,<span class="dv">1</span>,.<span class="dv">2</span>), <span class="kw">rbinom</span>(n,<span class="dv">1</span>,.<span class="dv">9</span>)))  <span class="co"># gerando sequência pseudoaleatória</span></span></code></pre></div>
<pre><code>##  [1] 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1</code></pre>
<p>Note na saída abaixo que o segmento indicado por <span class="math inline">\(\texttt{\$}\)</span>`<span class="math inline">\(\texttt{0}\)</span>` refere-se ao grupo onde <span class="math inline">\(X_1=0\)</span>, e <span class="math inline">\(\texttt{\$}\)</span>`<span class="math inline">\(\texttt{1}\)</span>` onde <span class="math inline">\(X_1=1\)</span>.</p>
<div class="sourceCode" id="cb608"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb608-1"><a href="modelos-lineares.html#cb608-1"></a><span class="kw">by</span>(y,x1,table) <span class="op">%&gt;%</span><span class="st">   </span><span class="co"># contando o número de zeros e uns em y separado por x1</span></span>
<span id="cb608-2"><a href="modelos-lineares.html#cb608-2"></a><span class="st">  </span><span class="kw">lapply</span>(prop.table) <span class="co"># calculando as proporções </span></span></code></pre></div>
<pre><code>## $`0`
## 
##      0      1 
## 0.9412 0.0588 
## 
## $`1`
## 
##     0     1 
## 0.174 0.826</code></pre>
<p>Note que a probabilidade de inadimplência no grupo onde <span class="math inline">\(X_1\)</span> não é observada é igual a <span class="math inline">\(Pr(Y=1|X_1=0) = 0.05882353\)</span>. No grupo de clientes que apresentam a característica <span class="math inline">\(X_1\)</span> esta probabilidade sobe para <span class="math inline">\(Pr(Y=1|X_1=1) = 0.826087\)</span>.</p>
<p>Finalmente é considerada uma variável <span class="math inline">\(X_2\)</span>, que aparece em aproximadamente metade dos clientes inadimplentes e em aproximadamente metade dos adimplentes. Assim, observar a característica <span class="math inline">\(X_2\)</span> não deve trazer informação sobre a probabilidade de inadimplência, simbolizada pela probabilidade condicional <span class="math inline">\(Pr(Y=1|X_2 = x_2)\)</span>, <span class="math inline">\(x_2 \in \{0,1\}\)</span>.</p>
<div class="sourceCode" id="cb610"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb610-1"><a href="modelos-lineares.html#cb610-1"></a><span class="kw">set.seed</span>(<span class="dv">1</span>); (x2 &lt;-<span class="st"> </span><span class="kw">rbinom</span>(<span class="dv">2</span><span class="op">*</span>n,<span class="dv">1</span>,.<span class="dv">5</span>)) <span class="co"># simulando valores de X2</span></span></code></pre></div>
<pre><code>##  [1] 0 0 1 1 0 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 1 1 0 1 0</code></pre>
<div class="sourceCode" id="cb612"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb612-1"><a href="modelos-lineares.html#cb612-1"></a><span class="kw">by</span>(y,x2,table) <span class="op">%&gt;%</span><span class="st">  </span><span class="co"># contando os zeros e uns de y, separados pelos valores de X2</span></span>
<span id="cb612-2"><a href="modelos-lineares.html#cb612-2"></a><span class="st">  </span><span class="kw">lapply</span>(prop.table) <span class="co"># transformando a contagem em proporção</span></span></code></pre></div>
<pre><code>## $`0`
## 
##     0     1 
## 0.429 0.571 
## 
## $`1`
## 
##     0     1 
## 0.579 0.421</code></pre>
</div>
<div id="o-modelo-de-regressão-logística" class="section level3" number="7.4.2">
<h3><span class="header-section-number">7.4.2</span> O modelo de regressão logística</h3>
<p>A <em>regressão logística</em> pertence à classe dos <em>modelos lineares generalizados</em>, descrita em detalhes por <span class="citation">(McCullagh and Nelder <a href="#ref-mccullagh1989generalized" role="doc-biblioref">1989</a>)</span>, <span class="citation">(Agresti <a href="#ref-agresti2007introduction" role="doc-biblioref">2007</a>)</span> e <span class="citation">(Paula <a href="#ref-paula2013modelos" role="doc-biblioref">2013</a>)</span>. Seja <span class="math inline">\(Y\)</span> uma variável aleatória binária com distribuição binimial de probablidade de sucesso <span class="math inline">\(\pi(x)\)</span>. A notação <span class="math inline">\(\pi(x)\)</span> sugere que a probabilidade de sucesso está condicionada a um valor/categoria <span class="math inline">\(x\)</span>. Desta forma, <span class="math inline">\(\pi(x) = Pr(Y=1|X=x)\)</span>. Define-se a função <em>logito</em> conforme a Eq. @ref(eq:logit_uni), onde <span class="math inline">\(\mathrm{log}\)</span> indica o logaritmo na base <span class="math inline">\(e \approx 2.718281828459\)</span>.</p>
<p><span class="math display">\[\begin{equation}
\mathrm{logito}\left[ \pi(x) \right] = \mathrm{log} \left( \dfrac{\pi(x)}{1-\pi(x)} \right) = \beta_0 + \beta_1 x
(\#eq:logit_uni)
\end{equation}\]</span>
Isolando <span class="math inline">\(\pi(x)\)</span> na Eq. @ref(eq:logit_uni) obtém-se</p>
<p><span class="math display">\[\begin{equation}
\pi(x) = \dfrac{e^{\beta_0 + \beta_1 x}}{1+e^{\beta_0 + \beta_1 x}}
(\#eq:pix_uni)
\end{equation}\]</span></p>

<div class="example">
<span id="exm:unnamed-chunk-136" class="example"><strong>Example 7.4  </strong></span>Considerando novamente as informações do Exemplo 8.1, vamos agora utilizar a estrutura das Equações @ref(eq:logit_uni) e @ref(eq:pix_uni) para abordar o problema.
</div>
<div class="sourceCode" id="cb614"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb614-1"><a href="modelos-lineares.html#cb614-1"></a><span class="co"># modelo 1</span></span>
<span id="cb614-2"><a href="modelos-lineares.html#cb614-2"></a>x1 &lt;-<span class="st"> </span><span class="kw">as.factor</span>(x1)  <span class="co"># convertendo em fator para usar a função glm</span></span>
<span id="cb614-3"><a href="modelos-lineares.html#cb614-3"></a>fit1 &lt;-<span class="st"> </span><span class="kw">glm</span>(y <span class="op">~</span><span class="st"> </span>x1, <span class="dt">family =</span> <span class="st">&#39;binomial&#39;</span>) <span class="co"># ajustando modelo logístico</span></span>
<span id="cb614-4"><a href="modelos-lineares.html#cb614-4"></a><span class="kw">summary</span>(fit1) <span class="co"># detalhamento do modelo</span></span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = y ~ x1, family = &quot;binomial&quot;)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -1.870  -0.348   0.135   0.618   2.380  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)    -2.77       1.03   -2.69  0.00715 ** 
## x11             4.33       1.17    3.71  0.00021 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 55.452  on 39  degrees of freedom
## Residual deviance: 28.860  on 38  degrees of freedom
## AIC: 32.86
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Note que o intercepto <span class="math inline">\(\hat{\beta}_0 = -2.773\)</span> é significativo (<span class="math inline">\(p-value = 0.00715\)</span>), bem como o coeficiente que indica a presença do atributo <span class="math inline">\(X_1\)</span>, <span class="math inline">\(\hat{\beta}_1 = 4.331\)</span> (<span class="math inline">\(p-value = 0.00021\)</span>). Assim, pode-se considerar o modelo conforme Eq. @ref(eq:logit_uni), na forma <span class="math display">\[\mathrm{log} \left( \dfrac{\pi(x)}{1-\pi(x)} \right) = -2.773 + 4.331 I_{x_1}. \]</span> A simbologia <span class="math inline">\(I_{x_1}\)</span> indica uma variável <em>indicadora</em> da presença do atributo <span class="math inline">\(X_1\)</span>. Assim, se a pessoa possuir o atributo <span class="math inline">\(X_1\)</span> considera-se <span class="math inline">\(I_{x_1}=1\)</span>, e <span class="math inline">\(I_{x_1}=0\)</span> caso contrário. Este é um modelo conhecido como <em>casela de referência</em>, visto que a variável <span class="math inline">\(X_1\)</span> é categórica. Desta forma, uma das categorias/níveis da variável é escolhida como a (casela de) referência. Por padrão, o R utiliza a primeira da ordem numérica/alfabética, no caso <span class="math inline">\(X_1=0\)</span>. Desta forma, se a pessoa não possui a característica <span class="math inline">\(X_1\)</span>, pode-se calcular sua probabilidade de inadimplência pela Eq. @ref(eq:pix_uni), dada por <span class="math display">\[Pr(Y=1|X_1=0) = \pi(0) = \dfrac{e^{-2.773 + 4.331 \times 0}}{1+e^{-2.773 + 4.331 \times 0}} \approx 0.05882353.\]</span> No caso de alguém que possui a característica <span class="math inline">\(X_1\)</span>, <span class="math display">\[Pr(Y=1|X_1=1) = \pi(1) = \dfrac{e^{-2.773 + 4.331 \times 1}}{1+e^{-2.773 + 4.331 \times 1}} \approx 0.826087.\]</span></p>
<div class="sourceCode" id="cb616"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb616-1"><a href="modelos-lineares.html#cb616-1"></a><span class="co"># modelo 1</span></span>
<span id="cb616-2"><a href="modelos-lineares.html#cb616-2"></a><span class="kw">exp</span>(<span class="kw">coef</span>(fit1)[<span class="dv">1</span>])<span class="op">/</span>(<span class="dv">1</span><span class="op">+</span><span class="kw">exp</span>(<span class="kw">coef</span>(fit1)[<span class="dv">1</span>])) <span class="co"># Pr(Y = 1 | X1 = 0)</span></span></code></pre></div>
<pre><code>## (Intercept) 
##      0.0588</code></pre>
<div class="sourceCode" id="cb618"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb618-1"><a href="modelos-lineares.html#cb618-1"></a><span class="kw">exp</span>(<span class="kw">sum</span>(<span class="kw">coef</span>(fit1)))<span class="op">/</span>(<span class="dv">1</span><span class="op">+</span><span class="kw">exp</span>(<span class="kw">sum</span>(<span class="kw">coef</span>(fit1)))) <span class="co"># Pr(Y = 1 | X1 = 1)</span></span></code></pre></div>
<pre><code>## [1] 0.826</code></pre>
<p>O mesmo procedimento considerado para <span class="math inline">\(X_1\)</span> pode ser realizado para <span class="math inline">\(X_2\)</span>. Note que o intercepto <span class="math inline">\(\hat{\beta}_0 = 0.2877\)</span> é <strong>não</strong> significativo (<span class="math inline">\(p-value = 0.514\)</span>), bem como o coeficiente que indica a presença do atributo <span class="math inline">\(X_2\)</span>, <span class="math inline">\(\hat{\beta}_1 = -0.6061\)</span> (<span class="math inline">\(p-value = 0.344\)</span>).</p>
<div class="sourceCode" id="cb620"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb620-1"><a href="modelos-lineares.html#cb620-1"></a><span class="co"># modelo 2</span></span>
<span id="cb620-2"><a href="modelos-lineares.html#cb620-2"></a>x2 &lt;-<span class="st"> </span><span class="kw">as.factor</span>(x2)  <span class="co"># convertendo em fator para usar a função glm</span></span>
<span id="cb620-3"><a href="modelos-lineares.html#cb620-3"></a>fit2 &lt;-<span class="st"> </span><span class="kw">glm</span>(y <span class="op">~</span><span class="st"> </span>x2, <span class="dt">family =</span> <span class="st">&#39;binomial&#39;</span>) <span class="co"># ajustando modelo logístico</span></span>
<span id="cb620-4"><a href="modelos-lineares.html#cb620-4"></a><span class="kw">summary</span>(fit2) <span class="co"># detalhamento do modelo</span></span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = y ~ x2, family = &quot;binomial&quot;)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.3018  -1.0455   0.0062   1.0579   1.3153  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)    0.288      0.441    0.65     0.51
## x21           -0.606      0.641   -0.95     0.34
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 55.452  on 39  degrees of freedom
## Residual deviance: 54.546  on 38  degrees of freedom
## AIC: 58.55
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Desta maneira o modelo não deve ser utilizado, mas para efeito de comparação com os resultados do Exemplo 8.1 são calculadas as probabilidades de sucesso condicionadas a <span class="math inline">\(X_2=0\)</span> e <span class="math inline">\(X_2=1\)</span>.</p>
<div class="sourceCode" id="cb622"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb622-1"><a href="modelos-lineares.html#cb622-1"></a><span class="co"># modelo 2</span></span>
<span id="cb622-2"><a href="modelos-lineares.html#cb622-2"></a><span class="kw">exp</span>(<span class="kw">coef</span>(fit2)[<span class="dv">1</span>])<span class="op">/</span>(<span class="dv">1</span><span class="op">+</span><span class="kw">exp</span>(<span class="kw">coef</span>(fit2)[<span class="dv">1</span>])) <span class="co"># Pr(Y = 1 | X2 = 0)</span></span></code></pre></div>
<pre><code>## (Intercept) 
##       0.571</code></pre>
<div class="sourceCode" id="cb624"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb624-1"><a href="modelos-lineares.html#cb624-1"></a><span class="kw">exp</span>(<span class="kw">sum</span>(<span class="kw">coef</span>(fit2)))<span class="op">/</span>(<span class="dv">1</span><span class="op">+</span><span class="kw">exp</span>(<span class="kw">sum</span>(<span class="kw">coef</span>(fit2)))) <span class="co"># Pr(Y = 1 | X2 = 1)</span></span></code></pre></div>
<pre><code>## [1] 0.421</code></pre>

<div class="exercise">
<span id="exr:unnamed-chunk-141" class="exercise"><strong>Exercise 7.3  </strong></span>Considere o conjunto de dados apresentado por Ronny Kohavi e Barry Becker, disponível em <a href="https://archive.ics.uci.edu/ml/datasets/adult" class="uri">https://archive.ics.uci.edu/ml/datasets/adult</a>. Considere um modelo de regressão logística para avaliar as características que mais impactam no salario das pessoas (acima ou abaixo de 50 mil dólares).
</div>
<div class="sourceCode" id="cb626"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb626-1"><a href="modelos-lineares.html#cb626-1"></a><span class="co"># lendo e arrumando os dados</span></span>
<span id="cb626-2"><a href="modelos-lineares.html#cb626-2"></a>dat &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&#39;https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data&#39;</span>,</span>
<span id="cb626-3"><a href="modelos-lineares.html#cb626-3"></a>                  <span class="dt">sep =</span> <span class="st">&#39;,&#39;</span>)</span>
<span id="cb626-4"><a href="modelos-lineares.html#cb626-4"></a>dat &lt;-<span class="st"> </span>dat[,<span class="op">-</span><span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">9</span>)]</span>
<span id="cb626-5"><a href="modelos-lineares.html#cb626-5"></a><span class="kw">colnames</span>(dat) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;idade&#39;</span>,<span class="st">&#39;tipoTrabalho&#39;</span>,<span class="st">&#39;educacao&#39;</span>,<span class="st">&#39;anosEstudo&#39;</span>,<span class="st">&#39;estadoCivil&#39;</span>,<span class="st">&#39;ocupacao&#39;</span>,</span>
<span id="cb626-6"><a href="modelos-lineares.html#cb626-6"></a>                   <span class="st">&#39;relacao&#39;</span>,<span class="st">&#39;genero&#39;</span>,<span class="st">&#39;ganhoCapital&#39;</span>,<span class="st">&#39;perdaCapital&#39;</span>,<span class="st">&#39;horasPorSemana&#39;</span>,</span>
<span id="cb626-7"><a href="modelos-lineares.html#cb626-7"></a>                   <span class="st">&#39;paisOrigem&#39;</span>,<span class="st">&#39;salario&#39;</span>)</span></code></pre></div>

</div>
</div>
</div>
<h3> Referências</h3>
<div id="refs" class="references">
<div id="ref-agresti2007introduction">
<p>Agresti, Alan. 2007. <em>An Introduction to Categorical Data Analysis</em>. Wiley. <a href="https://mregresion.files.wordpress.com/2012/08/agresti-introduction-to-categorical-data.pdf">https://mregresion.files.wordpress.com/2012/08/agresti-introduction-to-categorical-data.pdf</a>.</p>
</div>
<div id="ref-akaike1974new">
<p>Akaike, Hirotugu. 1974. “A New Look at the Statistical Model Identification.” In <em>Selected Papers of Hirotugu Akaike</em>, 215–22. Springer.</p>
</div>
<div id="ref-degroot2012probability">
<p>DeGroot, Morris H, and Mark J Schervish. 2012. <em>Probability and Statistics</em>. Pearson Education.</p>
</div>
<div id="ref-efroymson1960multiple">
<p>Efroymson, MA. 1960. “Multiple Regression Analysis.” <em>Mathematical Methods for Digital Computers</em>, 191–203.</p>
</div>
<div id="ref-mccullagh1989generalized">
<p>McCullagh, Peter, and John Ashworth Nelder. 1989. <em>Generalized Linear Models</em>. <em>Chapman Hall, London</em>. 2nd ed. <a href="http://www.utstat.toronto.edu/~brunner/oldclass/2201s11/readings/glmbook.pdf">http://www.utstat.toronto.edu/~brunner/oldclass/2201s11/readings/glmbook.pdf</a>.</p>
</div>
<div id="ref-neter2005applied">
<p>Neter, John, Michael H Kutner, Christopher J Nachtsheim, and William Wasserman. 2005. <em>Applied Linear Statistical Models</em>. 5th ed. McGraw Hill/Irwin New York. <a href="https://mysite.science.uottawa.ca/rkulik/mat3378/mat3378-textbook.pdf">https://mysite.science.uottawa.ca/rkulik/mat3378/mat3378-textbook.pdf</a>.</p>
</div>
<div id="ref-paula2013modelos">
<p>Paula, Gilberto Alvarenga. 2013. <em>Modelos de Regressão: Com Apoio Computacional</em>. IME-USP São Paulo. <a href="https://www.ime.usp.br/~giapaula/texto_2013.pdf">https://www.ime.usp.br/~giapaula/texto_2013.pdf</a>.</p>
</div>
<div id="ref-tsanas2012accurate">
<p>Tsanas, Athanasios, and Angeliki Xifara. 2012. “Accurate Quantitative Estimation of Energy Performance of Residential Buildings Using Statistical Machine Learning Tools.” <em>Energy and Buildings</em> 49: 560–67. <a href="http://people.maths.ox.ac.uk/tsanas/Preprints/ENB2012.pdf">http://people.maths.ox.ac.uk/tsanas/Preprints/ENB2012.pdf</a>.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="inferencia-bayesiana.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="aprendizadodemaquina.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
